'use strict';const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),a=require('node:assert/strict'),vm=require('node:vm');const hash=x=>crypto.createHash('sha256').update(x).digest('hex');const h=fs.readFileSync(path.join(__dirname,'../guild-raid-locked-stage-v948/private-client-locked-stage.html'),'utf8');a.equal(hash(h),'6559a3d50837800f46a5593c874895f666b472492ac57fff46d2725d3df14d7f');const b=h.indexOf("'use strict';",h.indexOf('M.directory=(()=>')),e=h.indexOf('return module.exports})();',b);a(b>0&&e>b);let s=h.slice(b,e);const parent=s;
const change=(x,y)=>{a.equal(s.split(x).length,2);s=s.replace(x,y)};
change("['v','accountId','guildId','id','entry','state','confirmedPacket']","['v','accountId','guildId','id','entry','state','confirmedPacket','entryClosure']");
change("!['pending','confirmed'].includes(p.state)","!['pending','confirmed','entry-closed'].includes(p.state)");
change(" if(p.state==='pending'&&Object.prototype.hasOwnProperty.call(p,'confirmedPacket'))throw Error('Unexpected confirmed packet');"," if(p.state!=='confirmed'&&Object.prototype.hasOwnProperty.call(p,'confirmedPacket'))throw Error('Unexpected confirmed packet');\n if(p.state==='entry-closed')closedProof(p.entryClosure,p);else if(Object.prototype.hasOwnProperty.call(p,'entryClosure'))throw Error('Unexpected entry closure');");
const proof=`function closedProof(c,r){
 const exact=['v','kind','spent','accountId','guildId','entry','serverPeriod','packetHash'].sort().join(',');
 const date=x=>typeof x==='string'&&/^\\d{4}-\\d{2}-\\d{2}$/.test(x)&&Number.isFinite(Date.parse(x+'T00:00:00Z'))&&new Date(x+'T00:00:00Z').toISOString().slice(0,10)===x;
 if(!object(c)||Object.keys(c).sort().join(',')!==exact||c.v!==1||c.kind!=='period-closed'||c.spent!=='unknown'||c.accountId!==r.accountId||c.guildId!==r.guildId||!same(c.entry,r.entry)||!/^r3:\\d{4}-\\d{2}-\\d{2}:[-a-z0-9]{1,24}$/.test(r.entry.requestId)||!date(r.entry.requestId.slice(3,13))||!date(c.serverPeriod)||r.entry.requestId.slice(3,13)>=c.serverPeriod||typeof c.packetHash!=='string'||!/^[0-9a-f]{64}$/.test(c.packetHash))throw Error('Entry closure binding');return clone(c);
}
`;
change('function row(p){',proof+'function row(p){');
change('  retireConfirmed(p){',`  markEntryClosed(p,proof){let r,c;try{r=row(p);if(r.state!=='pending')throw Error('Entry closure requires pending row');c=closedProof(proof,r)}catch(e){return Promise.reject(e)}return tx('readwrite',(s,done,fail)=>{const q=s.get([r.accountId,r.id]);q.onerror=()=>fail(q.error);q.onsuccess=()=>{try{const old=row(q.result);if(!same(old,r))throw Error('Entry closure row changed');const next=row({...old,state:'entry-closed',entryClosure:c});const w=s.put(next);w.onerror=()=>fail(w.error);w.onsuccess=()=>done(true)}catch(e){fail(e)}}})},
  retireEntryClosed(p){let r;try{r=row(p);if(r.state!=='entry-closed')throw Error('Not entry closed')}catch(e){return Promise.reject(e)}return tx('readwrite',(s,done,fail)=>{const q=s.get([r.accountId,r.id]);q.onerror=()=>fail(q.error);q.onsuccess=()=>{try{if(!q.result)return done(false);if(!same(row(q.result),r))throw Error('Entry retirement row changed');const d=s.delete([r.accountId,r.id]);d.onerror=()=>fail(d.error);d.onsuccess=()=>done(true)}catch(e){fail(e)}}})},
  retireConfirmed(p){`);
new vm.Script(s);fs.writeFileSync(__dirname+'/directory.cjs',s);fs.writeFileSync(__dirname+'/directory-original.cjs',parent);fs.writeFileSync(__dirname+'/build-certificate.json',JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),parentHTMLSHA256:hash(h),parentDirectorySHA256:hash(parent),directorySHA256:hash(s),spans:5,status:'PRIVATE_DIRECTORY_COMPONENT_NOT_HTML_WIRED'},null,2));console.log(hash(s));
