'use strict';
const fs=require('node:fs'),a=require('node:assert/strict'),vm=require('node:vm'),crypto=require('node:crypto'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
let h=fs.readFileSync(__dirname+'/../guild-raid-locked-stage-v948/private-client-locked-stage.html','utf8');a.equal(hash(h),'6559a3d50837800f46a5593c874895f666b472492ac57fff46d2725d3df14d7f');const parent=hash(h);let spans=0;
const change=(x,y)=>{a.equal(h.split(x).length,2);h=h.replace(x,y);spans++};
for(const [name,sha] of [['hybrid','9cc1fbec5b4c1fda17686f041188cae4f1dddf61d5ba9b918dee81739278bead'],['directory','79bc979c5916a4c481818de7a399ed5afd82214a642344bfcbfe038c690fbc72'],['facade','61661ea0cb705be06da99c1f9084790e87e6646f57e833064fa1d5539fdf7c68']]){const s=fs.readFileSync(__dirname+'/'+name+'.cjs','utf8'),old=fs.readFileSync(__dirname+'/'+name+'-original.cjs','utf8');a.equal(hash(s),sha);change(old,s)}
change("M.hybrid=(()=>{const module={exports:{}},require=n=>{if(n!=='./hybrid-adapter.cjs')throw Error('Unexpected dependency');return M.hybrid};","M.hybrid=(()=>{const module={exports:{}},require=n=>{if(n==='./directory.cjs')return {row:r=>M.directory.row(r)};throw Error('Unexpected hybrid dependency')};");
const closure=fs.readFileSync(__dirname+'/../guild-raid-period-closure-v948/validator.cjs','utf8');a.equal(hash(closure),'17313a30157394660b61c2334bf62b4b53860a70cce1a18dae8e5dd9dbc82687');
change('M.facade=(()=>{',"M.closure=(()=>{const module={exports:{}};\n"+closure+"\nreturn module.exports})();\nM.facade=(()=>{");
change(" async function retireCompleted(id){",` async function closeSavedEntry(id){guard();if(busy||owner)throw Error('An owned fight or result must finish first');if(typeof facade.closeEntryRecovery!=='function')throw Error('Entry closure unavailable');busy=true;
  try{const reply=await facade.closeEntryRecovery(id);guard();if(owner||reply?.status!==200||reply.body?.cleanupOnly!==true||reply.body?.entryClosed!==true||Object.keys(reply.body).sort().join(',')!=='cleanupOnly,entryClosed')throw Error('Entry cleanup response refused');const choices=await facade.discover();guard();if(owner||choices.some(x=>x.id===id))throw Error('Entry directory not retired');return {cleanupOnly:true,entryClosed:true};}finally{busy=false;}
 }
 async function retireCompleted(id){`);
change('discover,stageAndSchedule,retireCompleted,owned:','discover,stageAndSchedule,retireCompleted,closeSavedEntry,owned:');
change('   validateEntryReply:M.entry.validateEntryReply,validateFreshEntryReply:M.fresh.validateFreshEntryReply,',"   validateEntryReply:M.entry.validateEntryReply,validateFreshEntryReply:M.fresh.validateFreshEntryReply,\n   validateEntryClosureReply:x=>M.closure.validate({...x,digest:async raw=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw))),n=>n.toString(16).padStart(2,'0')).join('')}),");
change("if(found.status==='entry-recovery-only')await runtime.bootstrap.resume(found.id);else raidSettlementRun(found.id,{});","if(found.status==='entry-recovery-only')await runtime.bootstrap.resume(found.id);else if(found.status==='entry-closed-cleanup'){await runtime.bootstrap.closeSavedEntry(found.id);if(runtime.current())bannerMsg('Saved entry cleanup completed. No new fight or reward was requested.');}else raidSettlementRun(found.id,{});");
change('function raidSettlementQueue(packet,RB){',`async function raidCloseSavedEntry(){try{if(RAID_SETTLEMENT&&RAID_SETTLEMENT.current())throw Error('Finish the saved raid result first.');const runtime=await raidGetV3(),choices=await runtime.bootstrap.discover();if(!runtime.current())return;if(choices.length!==1||!['entry-recovery-only','entry-closed-cleanup'].includes(choices[0].status))throw Error('One saved entry-only request is required. No result was discarded.');await runtime.bootstrap.closeSavedEntry(choices[0].id);if(runtime.current())bannerMsg('Saved entry is closed. No refund, new fight or reward was requested.');}catch(e){bannerMsg('Saved entry held: '+String(e.message||e));}}
function raidSettlementQueue(packet,RB){`);
change("  el.prepend(recoveryButton);","  const closureButton=document.createElement('button');closureButton.className='btn secondary';closureButton.textContent='Check saved entry closure';closureButton.onclick=()=>raidCloseSavedEntry();\n  el.prepend(recoveryButton,closureButton);");
const b=h.indexOf('const EW_RAID_V3_MODULES='),e=h.indexOf('// PRIVATE guarded v3 cutover.',b);const M=vm.runInNewContext(h.slice(b,e)+'\nEW_RAID_V3_MODULES;');a.equal(typeof M.bootstrap.create,'function');a.equal(typeof M.closure.validate,'function');a.equal(typeof M.facade.create,'function');
let scripts=0;for(const m of h.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)){if(m[1].trim()){new vm.Script(m[1]);scripts++}}fs.writeFileSync(__dirname+'/private-client-entry-closure.html',h);fs.writeFileSync(__dirname+'/html-build-certificate.json',JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),parentHTMLSHA256:parent,clientSHA256:hash(h),spans,inlineScriptsParsed:scripts,moduleKeys:Object.keys(M),status:'PRIVATE_HTML_PARSE_ONLY_NOT_HTTP_NATIVE_UI_VERIFIED'},null,2));console.log(hash(h));
