'use strict';
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),a=require('node:assert/strict'),crypto=require('node:crypto'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
let s=fs.readFileSync(path.join(__dirname,'../guild-raid-period-fence-v948/http.cjs'),'utf8');a.equal(hash(s),'21fae26ad5aed07ca4f6896b7b8b650c38a10b9208cf0df923876fd1f5025c3d');s=s.replace("process.env.PERIOD_FENCE_CONTROL?'../guild-raid-expired-identity-v948/private-server-expired-identity.js':'private-server-period-fence.js'","'../guild-raid-period-closure-v948/private-server-period-closure.js'");
const b=s.indexOf('const call=async p=>'),e=s.indexOf('\n}catch(err)',b);a(b>0&&e>b);
s=s.slice(0,b)+String.raw`
const vm=require('node:vm'),clone=x=>JSON.parse(JSON.stringify(x));a.equal(hash(fs.readFileSync(candidate)),'7d2cb9f199382ea77a31ed36bfead8fc03808c9559a40ed5b18bb17c5ef5dbe9');
const html=fs.readFileSync(path.join(__dirname,'private-client-entry-closure.html'),'utf8');a.equal(hash(html),'c4f330ca4ae0df11f56caa2fab3db6d6483adcaddb0a970c02953ae8516ff115');const mb=html.indexOf('const EW_RAID_V3_MODULES='),me=html.indexOf('// PRIVATE guarded v3 cutover.',mb),scope={accountId:'fixture-user',guildId:'own-guild'};
const E={requestId:'r3:2026-10-02:paidclosure',heroIds:['vael']};const paid=await f.call('/api/guild/raid/start',E);a.equal(paid.status,200);a.equal(paid.body.ok,true);a.equal(f.disk().users['fixture-user'].raidDay.n,1);
await f.stop();f.advanceClock(86400000);await f.launch();const before=f.bytes(),rows=new Map(),slots=new Map();let locked=false,retireFault=false,quota=false;
function seed(packet,id){const row={v:3,...scope,id,entry:clone(packet),state:'pending'};rows.set(id,row);return row}
function client(){const M=vm.runInNewContext(html.slice(mb,me)+'\nEW_RAID_V3_MODULES;',{structuredClone});const directory={async list(account){a(locked);return clone([...rows.values()].filter(x=>x.accountId===account))},async markEntryClosed(r,c){a(locked);a.deepEqual(rows.get(r.id),clone(r));rows.set(r.id,clone(M.directory.row({...clone(r),state:'entry-closed',entryClosure:clone(c)})))},async retireEntryClosed(r){a(locked);a.deepEqual(rows.get(r.id),clone(r));if(retireFault)throw Error('Injected retire interruption');rows.delete(r.id)}};
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.has(k)?slots.get(k):null,setItem(k,v){a(locked);if(quota)throw Error('Injected quota');slots.set(k,v)}};
 const context=()=>({...scope,token:'generic-fixture-token',epoch:1}),transport=M.transport.createTransport({context,fetch:async(route,opt)=>{a(locked);const packet=JSON.parse(opt.body);a.equal(packet.recoverOnly,true);const r=await f.call(route,packet,opt.headers['x-token']);calls.push({route,packet,status:r.status,body:r.body});return {status:r.status,json:async()=>clone(r.body)}}});
 return {M,facade:M.facade.create({directory,storage,context,transport,locks:{async request(name,opt,fn){a(!locked);locked=true;try{return await fn({name})}finally{locked=false}}},legacyWritersQuiescent:async()=>true,validateEntryClosureReply:x=>M.closure.validate({...x,digest:async raw=>hash(raw)})})};}
// Known paid but expired: closure honestly says UNKNOWN spend, never refund/grant.
seed(E,'paid');let c=client();retireFault=true;await a.rejects(c.facade.closeEntryRecovery('paid'),/Injected retire/);a.equal(calls.length,1);a.equal(calls[0].body.entryClosure.spent,'unknown');a.equal(rows.get('paid').state,'entry-closed');a.equal(slots.size,1);a.equal(f.bytes(),before);
await f.stop();await f.launch();retireFault=false;c=client();const out=await c.facade.closeEntryRecovery('paid');a.equal(out.body.cleanupOnly,true);a.equal(out.body.entryClosed,true);a.equal(calls.length,1,'persisted confirmation cleanup must use zero network');a.equal(rows.size,0);a.equal(slots.size,1);a.equal(f.bytes(),before);
// Never committed entry: exact same unknown-spend proof, quota keeps directory until retry.
const U={requestId:'r3:2026-10-02:uncommitted',heroIds:['vael']};seed(U,'uncommitted');quota=true;c=client();await a.rejects(c.facade.closeEntryRecovery('uncommitted'),/Injected quota/);a.equal(calls.length,2);a.equal(rows.get('uncommitted').state,'entry-closed');a.equal(f.bytes(),before);await f.stop();await f.launch();quota=false;c=client();await c.facade.closeEntryRecovery('uncommitted');a.equal(calls.length,2);a.equal(rows.size,0);a.equal(slots.size,2);a.equal(f.bytes(),before);
// A staged result is immutable and cannot be discarded by the new entry button.
const r=seed({...U,requestId:'r3:2026-10-02:staged'},'staged'),P={requestId:'saved-result',attemptId:paid.body.attemptId,inputLog:[],dmg:1},raw=JSON.stringify({v:3,...scope,instanceId:r.id,entryRequestId:r.entry.requestId,packet:P});slots.set(c.M.hybrid.key(r),raw);const n=calls.length;await a.rejects(c.facade.closeEntryRecovery('staged'),/No entry-only/);a.equal(calls.length,n);a.equal(slots.get(c.M.hybrid.key(r)),raw);a.equal(rows.get('staged').state,'pending');a.equal(f.bytes(),before);
a.equal(f.disk().users['fixture-user'].raidDay.n,1);a.equal(f.disk().users['fixture-user'].led.txs.filter(t=>t.src==='guild-raid').length,0);
console.log('PASS current embedded c4f330/7d2cb9 authHTTP: paid-expired and nevercommitted closure, quota/retire interruptions freshVM+serverrestart cleanup zero network, retained markers, immutable staged result, wholeDB unchanged/no new charge/refund/grant');
`+s.slice(e);
s=s.replace("'certificate.json'","'closure-http-certificate.json'").replace("calls,failure,fixtureRestored:true","clientSHA256:'c4f330ca4ae0df11f56caa2fab3db6d6483adcaddb0a970c02953ae8516ff115',calls,failure,fixtureRestored:true").replace('Client namespace/day acquisition NOTwired; legacy bare IDs unchanged, no native/fullsuite/balance/terminal retirement proof.','Current embedded facade/hybrid/directory structuralvalidator/closure digestvalidator and authenticatedprivateHTTP, modeled directory/storage/locks/testquiescence ONLY; not native/fullcombat/UI/phone/fullsuite/balance.');
const file=path.join(__dirname,'closure-http-wrapper.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m._compile(s,file);
