'use strict';
const fs=require('node:fs'),vm=require('node:vm'),a=require('node:assert/strict'),crypto=require('node:crypto'),copy=x=>JSON.parse(JSON.stringify(x)),D=require('./directory.cjs'),H=require('./hybrid.cjs'),V=require('../guild-raid-period-closure-v948/validator.cjs');
const source=fs.readFileSync(__dirname+'/facade.cjs','utf8'),moduleBox={exports:{}};vm.runInNewContext(source,{module:moduleBox,require:n=>{a.equal(n,'./hybrid-adapter.cjs');return H}});const F=moduleBox.exports;
const p={v:3,accountId:'actor',guildId:'guild',id:'slot',entry:{requestId:'r3:2026-10-02:one',heroIds:['hero1','hero2']},state:'pending'},scope={accountId:p.accountId,guildId:p.guildId},digest=async x=>crypto.createHash('sha256').update(x).digest('hex');
const proof={v:1,kind:'period-closed',spent:'unknown',...scope,entry:copy(p.entry),serverPeriod:'2026-10-03',packetHash:crypto.createHash('sha256').update(JSON.stringify(p.entry)).digest('hex')},closed={...copy(p),state:'entry-closed',entryClosure:proof};
const reply={status:409,body:{ok:false,entryPeriodHeld:true,entryClosure:{v:1,kind:'period-closed',spent:'unknown',...scope,requestId:p.entry.requestId,heroIds:copy(p.entry.heroIds),serverPeriod:proof.serverPeriod,packetHash:proof.packetHash}}};
function rig(initial=p){let row=copy(initial),ctx={...scope,token:'fixture-session',epoch:1},count=0,quiescent=true,available=true,retireFault=false,quota=false,afterTransport=()=>{},afterValidate=()=>{},response=copy(reply),locked=false;const data=new Map();
 const storage={get length(){return data.size},key:i=>Array.from(data.keys())[i]??null,getItem:k=>data.has(k)?data.get(k):null,setItem(k,v){a.equal(locked,true);if(quota)throw Error('Quota');data.set(k,v)}};
 const directory={async list(){a.equal(locked,true);return row?[D.row(row)]:[]},async markEntryClosed(r,c){a.equal(locked,true);a.deepEqual(row,r);row=D.row({...copy(r),state:'entry-closed',entryClosure:copy(c)})},async retireEntryClosed(r){a.equal(locked,true);a.deepEqual(row,r);if(retireFault)throw Error('Retirement abort');row=null}};
 const options={directory,storage,context:()=>ctx,locks:{async request(name,options,fn){a.equal(name,'ew_raid_pending_v1_actor');a.equal(options.ifAvailable,true);a.equal(locked,false);locked=true;try{return await fn(available?{}:null)}finally{locked=false}}},legacyWritersQuiescent:async()=>quiescent,transport:async request=>{a.equal(locked,true);a.equal(request.mode,'entry-recovery-only');a.deepEqual(JSON.parse(JSON.stringify(request.packet)),p.entry);count++;afterTransport();return copy(response)},validateEntryClosureReply:async args=>{a.equal(locked,true);const result=await V.validate({...args,digest});afterValidate();return result}};
 return {make:()=>F.create(options),data,get row(){return copy(row)},get requests(){return count},stale(){ctx={...ctx,epoch:2}},busy(){available=false},notQuiescent(){quiescent=false},retireFault(v){retireFault=v},quota(v){quota=v},response(v){response=copy(v)},afterTransport(fn){afterTransport=fn},afterValidate(fn){afterValidate=fn},putResult(){data.set(H.key(p),JSON.stringify({v:3,...scope,instanceId:p.id,entryRequestId:p.entry.requestId,packet:{requestId:'result',attemptId:'attempt',inputLog:[],dmg:12}}))},legacyPending(){data.set('ew_raid_pending_v1_actor','held')},setRow(r){row=copy(r)}}}
let pass=0,fail=0,cases=[];async function test(name,f){try{await f();pass++;cases.push({name,status:'PASS'})}catch(e){fail++;cases.push({name,status:'FAIL',error:e.message})}console.log(cases.at(-1))}
(async()=>{
 await test('exact saved entry authenticated proof closes under shared lock',async()=>{const r=rig(),out=await r.make().closeEntryRecovery(p.id);a.equal(out.body.cleanupOnly,true);a.equal(out.body.entryClosed,true);a.equal(r.requests,1);a.equal(r.row,null);a.equal(r.data.size,1)});
 await test('persisted closure retries cleanup with zero transport after retirement fault',async()=>{const r=rig();r.retireFault(true);await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.deepEqual(r.row,closed);a.equal(r.requests,1);r.retireFault(false);await r.make().closeEntryRecovery(p.id);a.equal(r.requests,1);a.equal(r.row,null);a.equal(r.data.size,1)});
 await test('persisted closure quota failure retains discovery and retries zero transport',async()=>{const r=rig(closed);r.quota(true);await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.deepEqual(r.row,closed);a.equal(r.requests,0);r.quota(false);await r.make().closeEntryRecovery(p.id);a.equal(r.requests,0);a.equal(r.row,null)});
 await test('staged result blocks closure before any transport',async()=>{const r=rig();r.putResult();const raw=r.data.get(H.key(p));await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.equal(r.requests,0);a.deepEqual(r.row,p);a.equal(r.data.get(H.key(p)),raw)});
 await test('busy account lock blocks transport and all writes',async()=>{const r=rig();r.busy();await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.equal(r.requests,0);a.deepEqual(r.row,p);a.equal(r.data.size,0)});
 await test('unproven legacy quiescence blocks transport',async()=>{const r=rig();r.notQuiescent();await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.equal(r.requests,0);a.deepEqual(r.row,p)});
 await test('legacy pending packet is not migrated or discarded',async()=>{const r=rig();r.legacyPending();await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.equal(r.requests,0);a.equal(r.data.get('ew_raid_pending_v1_actor'),'held')});
 await test('stale session after HTTP refuses proof mutation',async()=>{const r=rig();r.afterTransport(()=>r.stale());await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.deepEqual(r.row,p);a.equal(r.data.size,0)});
 await test('stale session after digest refuses proof mutation',async()=>{const r=rig();r.afterValidate(()=>r.stale());await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.deepEqual(r.row,p);a.equal(r.data.size,0)});
 await test('result appearing during validation stays immutable and blocks closure',async()=>{const r=rig();r.afterValidate(()=>r.putResult());await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.deepEqual(r.row,p);a.equal(r.data.size,1);a.equal(JSON.parse(r.data.get(H.key(p))).packet.dmg,12)});
 for(const [name,mutate] of [['generic429',x=>{x.status=429;x.body={error:'Slow down'}}],['wrong hash',x=>x.body.entryClosure.packetHash='0'.repeat(64)],['wrong guild',x=>x.body.entryClosure.guildId='other'],['current period',x=>x.body.entryClosure.serverPeriod='2026-10-02']])await test('unproven '+name+' retains pending intent',async()=>{const r=rig(),x=copy(reply);mutate(x);r.response(x);await a.rejects(()=>r.make().closeEntryRecovery(p.id));a.deepEqual(r.row,p);a.equal(r.data.size,0);a.equal(r.requests,1)});
 await test('generic recover will not send persisted closure as result',async()=>{const r=rig(closed);await a.rejects(()=>r.make().recover(p.id));a.equal(r.requests,0);a.deepEqual(r.row,closed)});
 const cert={atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),facadeSHA256:crypto.createHash('sha256').update(source).digest('hex'),pass,fail,cases,scope:'Actual extracted facade and hybrid, actual pure digest validator+directory row validator, modeled directory/storage/WebLock and authenticated-channel reply fixture. NOT actual HTTP/native/HTML/UI integration or balance. No grant/render functions supplied'};fs.writeFileSync(__dirname+'/facade-certificate.json',JSON.stringify(cert,null,2));process.exitCode=fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=2});
