'use strict';
const fs=require('node:fs'),vm=require('node:vm'),a=require('node:assert/strict'),crypto=require('node:crypto'),Module=require('node:module'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const html=fs.readFileSync(__dirname+'/private-client-entry-closure.html','utf8');a.equal(hash(html),'c4f330ca4ae0df11f56caa2fab3db6d6483adcaddb0a970c02953ae8516ff115');const b=html.indexOf('const EW_RAID_V3_MODULES='),e=html.indexOf('// PRIVATE guarded v3 cutover.',b),M=vm.runInNewContext(html.slice(b,e)+'\nEW_RAID_V3_MODULES;',{structuredClone});
let pass=0,fail=0,cases=[];async function test(name,f){try{await f();pass++;cases.push({name,status:'PASS'})}catch(e){fail++;cases.push({name,status:'FAIL',error:e.message})}console.log(cases.at(-1))}
function rig(){let calls=0,fights=0,schedules=0,release,reply={status:200,body:{cleanupOnly:true,entryClosed:true}},choices=[],defer=false;const row={id:'slot',entry:{requestId:'entry'}},f={current:()=>true,start:async()=>({row,reply:{status:200,body:{ok:true,attemptId:'attempt'}}}),resume(){},stage(){},discover:async()=>choices,closeEntryRecovery:async()=>{calls++;if(defer)await new Promise(r=>release=r);return reply}};const boot=M.bootstrap.create({facade:f,current:()=>true,onFight:()=>fights++,scheduleSettlement:()=>schedules++});return{boot,get counts(){return {calls,fights,schedules}},setDeferred(){defer=true},release:()=>release(),setReply:r=>reply=r,setChoices:x=>choices=x}}
(async()=>{
 await test('bootstrap entrycleanup never starts fight or schedules reward',async()=>{const r=rig();await r.boot.closeSavedEntry('slot');a.deepEqual(r.counts,{calls:1,fights:0,schedules:0});a.equal(r.boot.owned(),null)});
 await test('owned active fight blocks entry closure before facade',async()=>{const r=rig();await r.boot.launch({},'slot');await a.rejects(()=>r.boot.closeSavedEntry('slot'));a.deepEqual(r.counts,{calls:0,fights:1,schedules:0});a.equal(r.boot.owned().phase,'fight')});
 await test('closure button calls are singleflight',async()=>{const r=rig();r.setDeferred();const first=r.boot.closeSavedEntry('slot');await Promise.resolve();await a.rejects(()=>r.boot.closeSavedEntry('slot'));a.equal(r.counts.calls,1);r.release();await first});
 await test('forged reward body does not pass cleanup-only contract',async()=>{const r=rig();r.setReply({status:200,body:{cleanupOnly:true,entryClosed:true,gold:100}});await a.rejects(()=>r.boot.closeSavedEntry('slot'));a.equal(r.counts.fights,0);a.equal(r.counts.schedules,0)});
 await test('retained discovery keeps bootstrap cleanup held',async()=>{const r=rig();r.setChoices([{id:'slot',status:'entry-closed-cleanup'}]);await a.rejects(()=>r.boot.closeSavedEntry('slot'));a.equal(r.boot.owned(),null)});
 fs.writeFileSync(__dirname+'/html-bootstrap-certificate.json',JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),clientSHA256:hash(html),pass,fail,cases,scope:'Actual embedded bootstrap in VM with fake facade; not DOM/native/currentHTTP'},null,2));if(fail)process.exitCode=1;
 // Reuse all fifteen assertions against actual embedded module objects, not standalone exports.
 let s=fs.readFileSync(__dirname+'/facade-tests.cjs','utf8');const old="D=require('./directory.cjs'),H=require('./hybrid.cjs'),V=require('../guild-raid-period-closure-v948/validator.cjs');";a.equal(s.split(old).length,2);s=s.replace(old,'D=globalThis.__closureModules.directory,H=globalThis.__closureModules.hybrid,V=globalThis.__closureModules.closure;');s=s.replace('const F=moduleBox.exports;','const F=globalThis.__closureModules.facade;').replaceAll('a.deepEqual(row,r)','a.equal(JSON.stringify(row),JSON.stringify(r))').replace("'/facade-certificate.json'","'/embedded-facade-certificate.json'").replace("facadeSHA256:crypto.createHash('sha256').update(source).digest('hex')","clientSHA256:'"+hash(html)+"',facadeSHA256:crypto.createHash('sha256').update(source).digest('hex')");globalThis.__closureModules=M;const file=__dirname+'/embedded-facade-wrapper.cjs',m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m._compile(s,file);
})().catch(e=>{console.error(e);process.exitCode=2});
