'use strict';
const fs=require('node:fs'),a=require('node:assert/strict'),crypto=require('node:crypto'),copy=x=>JSON.parse(JSON.stringify(x)),D=require('./directory.cjs'),H=require('./hybrid.cjs');
const p={v:3,accountId:'actor',guildId:'guild',id:'slot',entry:{requestId:'r3:2026-10-02:one',heroIds:['hero1','hero2']},state:'pending'},scope={accountId:p.accountId,guildId:p.guildId};
const proof={v:1,kind:'period-closed',spent:'unknown',...scope,entry:copy(p.entry),serverPeriod:'2026-10-03',packetHash:crypto.createHash('sha256').update(JSON.stringify(p.entry)).digest('hex')},closed={...copy(p),state:'entry-closed',entryClosure:proof};
function rig(initial=p){let row=copy(initial),current=true,storageFail=false,retireFail=false,marks=0,retires=0;const data=new Map(),storage={getItem:k=>data.has(k)?data.get(k):null,setItem(k,v){if(storageFail)throw Error('Quota');data.set(k,v)}};
 const directory={async insertBounded(r,cap){a.equal(cap,4);a.equal(row,null);row=D.row(r)},async list(){return row?[D.row(row)]:[]},async markEntryClosed(r,c){a.deepEqual(row,r);a.equal(r.state,'pending');row=D.row({...copy(r),state:'entry-closed',entryClosure:copy(c)});marks++},async retireEntryClosed(r){a.deepEqual(row,r);retires++;if(retireFail)throw Error('Injected retirement abort');row=null;return true}};
 const make=()=>H.create(directory,storage,{isCurrent:()=>current,legacyCheck:async()=> 'clear'});
 return {make,data,storage,get row(){return copy(row)},get counts(){return {marks,retires}},quota(v){storageFail=v},retireFault(v){retireFail=v},stale(){current=false},setRow(r){row=copy(r)}}}
let pass=0,fail=0,cases=[];async function test(name,f){try{await f();pass++;cases.push({name,status:'PASS'})}catch(e){fail++;cases.push({name,status:'FAIL',error:e.message})}console.log(cases.at(-1))}
(async()=>{
 await test('entry-only closure persists proof; fresh adapter returns cleanup-only',async()=>{const r=rig();await r.make().closeEntry(scope,p.id,proof);a.deepEqual(r.row,closed);a.equal((await r.make().recover(scope))[0].status,'entry-closed-cleanup');a.equal(r.data.size,0)});
 await test('missing marker rebuilt before retirement and retained afterward',async()=>{const r=rig(closed);await r.make().cleanupClosed(scope,p.id);a.equal(r.row,null);const m=JSON.parse(r.storage.getItem(H.key(p)));a.equal(m.entryClosed,true);a.deepEqual(m.entryClosure,proof);a.equal(await r.make().cleanupClosed(scope,p.id),false);a.equal(r.data.size,1)});
 await test('quota failure preserves closed proof and discovery',async()=>{const r=rig(closed);r.quota(true);await a.rejects(()=>r.make().cleanupClosed(scope,p.id));a.deepEqual(r.row,closed);a.equal(r.counts.retires,0);r.quota(false);await r.make().cleanupClosed(scope,p.id);a.equal(r.row,null)});
 await test('retirement failure preserves marker/proof; fresh cleanup retry needs no transport',async()=>{const r=rig(closed);r.retireFault(true);await a.rejects(()=>r.make().cleanupClosed(scope,p.id));a.deepEqual(r.row,closed);a.equal(r.data.size,1);a.equal((await r.make().recover(scope))[0].status,'entry-closed-cleanup');r.retireFault(false);await r.make().cleanupClosed(scope,p.id);a.equal(r.row,null);a.equal(r.data.size,1)});
 await test('staged result blocks closure and preserves exact packet',async()=>{const r=rig(),packet={requestId:'result',attemptId:'attempt',inputLog:[],dmg:12},raw=JSON.stringify({v:3,...scope,instanceId:p.id,entryRequestId:p.entry.requestId,packet});r.data.set(H.key(p),raw);await a.rejects(()=>r.make().closeEntry(scope,p.id,proof));a.deepEqual(r.row,p);a.equal(r.counts.marks,0);a.equal(r.data.get(H.key(p)),raw)});
 await test('closed row conflicting result marker refuses retirement',async()=>{const r=rig(closed),raw=JSON.stringify({v:3,...scope,instanceId:p.id,entryRequestId:p.entry.requestId,packet:{requestId:'r',attemptId:'a',inputLog:[],dmg:1}});r.data.set(H.key(p),raw);await a.rejects(()=>r.make().cleanupClosed(scope,p.id));a.deepEqual(r.row,closed);a.equal(r.counts.retires,0);a.equal(r.data.get(H.key(p)),raw)});
 await test('stale context refuses cleanup without marker/retirement',async()=>{const r=rig(closed);r.stale();await a.rejects(()=>r.make().cleanupClosed(scope,p.id));a.equal(r.data.size,0);a.equal(r.counts.retires,0)});
 await test('pending row cleanup cannot be used as terminal proof',async()=>{const r=rig();await a.rejects(()=>r.make().cleanupClosed(scope,p.id));a.deepEqual(r.row,p);a.equal(r.data.size,0)});
 await test('retained marker blocks different adapter old writer after retirement',async()=>{const r=rig(null),old=r.make(),lease=await old.enroll(scope,p.entry,p.id),newer=r.make();await newer.closeEntry(scope,p.id,proof);await newer.cleanupClosed(scope,p.id);const raw=r.data.get(H.key(p));a.throws(()=>old.stage(lease,{requestId:'late-result',attemptId:'late-attempt',inputLog:[],dmg:12}));a.equal(r.data.get(H.key(p)),raw);a.equal(r.row,null)});
 const cert={atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),hybridSHA256:crypto.createHash('sha256').update(fs.readFileSync(__dirname+'/hybrid.cjs')).digest('hex'),pass,fail,cases,scope:'Actual extracted hybrid source, structural actual directory validator, modeled async directory and storage; no transport/grant functions provided. NOT native, facade-lock/session/auth/digest or HTML integration proof'};fs.writeFileSync(__dirname+'/hybrid-certificate.json',JSON.stringify(cert,null,2));process.exitCode=fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=2});
