'use strict';
const fs=require('node:fs'),a=require('node:assert/strict'),crypto=require('node:crypto');
const control=process.env.DIRECTORY_CONTROL==='1',A=require(control?'./directory-original.cjs':'./directory.cjs'),copy=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
const p={v:3,accountId:'actor',guildId:'guild',id:'slot',entry:{requestId:'r3:2026-10-02:one',heroIds:['hero1','hero2']},state:'pending'};
const proof={v:1,kind:'period-closed',spent:'unknown',accountId:p.accountId,guildId:p.guildId,entry:copy(p.entry),serverPeriod:'2026-10-03',packetHash:crypto.createHash('sha256').update(JSON.stringify(p.entry)).digest('hex')};
const closed={...copy(p),state:'entry-closed',entryClosure:copy(proof)},result={requestId:'result',attemptId:'attempt',inputLog:[],dmg:10};
// Transactional fault model, NOT native IndexedDB. Request success precedes commit.
function model(initial,abortCommit=false){let saved=copy(initial),writes=0;return {get saved(){return copy(saved)},get writes(){return writes},transaction(){let pending=copy(saved),aborted=false;const t={abort(){aborted=true;queueMicrotask(()=>t.onabort?.())},objectStore(){return {get(){const q={};queueMicrotask(()=>{q.result=copy(pending);q.onsuccess?.();setImmediate(()=>{if(aborted)return;if(abortCommit){t.error=Error('Injected commit abort');t.onabort?.()}else{saved=copy(pending);t.oncomplete?.()}})});return q},put(v){writes++;pending=copy(v);const q={};queueMicrotask(()=>q.onsuccess?.());return q},delete(){writes++;pending=undefined;const q={};queueMicrotask(()=>q.onsuccess?.());return q}}}};return t}}}
let pass=0,fail=0;const cases=[];async function test(name,fn){try{await fn();pass++;cases.push({name,status:'PASS'})}catch(e){fail++;cases.push({name,status:'FAIL',error:e.message})}console.log(cases.at(-1))}
(async()=>{
 await test('persists exact closed proof only after transaction complete',async()=>{const db=model(p),op=A.create(db).markEntryClosed(p,proof);let resolved=false;op.then(()=>resolved=true);await new Promise(r=>queueMicrotask(r));a.equal(resolved,false);a.deepEqual(db.saved,p);await op;a.deepEqual(db.saved,closed)});
 await test('request success then commit abort retains pending row',async()=>{const db=model(p,true);await a.rejects(()=>A.create(db).markEntryClosed(p,proof));a.equal(db.writes,1);a.deepEqual(db.saved,p)});
 await test('fresh directory reads persisted closure structurally',async()=>{a.deepEqual(A.row(copy(closed)),closed)});
 await test('exact closed row retirement after commit',async()=>{const db=model(closed);a.equal(await A.create(db).retireEntryClosed(closed),true);a.equal(db.saved,undefined)});
 await test('retirement commit abort retains proof for cleanup-only retry',async()=>{const db=model(closed,true);await a.rejects(()=>A.create(db).retireEntryClosed(closed));a.deepEqual(db.saved,closed)});
 await test('absent closed row retirement is idempotent false',async()=>{const db=model(undefined);a.equal(await A.create(db).retireEntryClosed(closed),false);a.equal(db.writes,0)});
 await test('stale row refuses closure without write',async()=>{const changed={...copy(p),entry:{...copy(p.entry),heroIds:['hero2','hero1']}},db=model(changed);await a.rejects(()=>A.create(db).markEntryClosed(p,proof));a.equal(db.writes,0);a.deepEqual(db.saved,changed)});
 await test('stale closed proof refuses retirement without delete',async()=>{const changed={...copy(closed),entryClosure:{...copy(proof),serverPeriod:'2026-10-04'}},db=model(changed);await a.rejects(()=>A.create(db).retireEntryClosed(closed));a.equal(db.writes,0);a.deepEqual(db.saved,changed)});
 for(const [name,mutate] of [['wrong account',x=>x.accountId='other'],['wrong guild',x=>x.guildId='other'],['reordered squad',x=>x.entry.heroIds.reverse()],['current period',x=>x.serverPeriod='2026-10-02'],['invalid date',x=>x.serverPeriod='2026-02-30'],['false unspent',x=>x.spent='never'],['extra key',x=>x.token='not-a-secret'],['bad hash',x=>x.packetHash='bad']])await test('proof rejects '+name+' before transaction writes',async()=>{const c=copy(proof);mutate(c);const db=model(p);await a.rejects(()=>A.create(db).markEntryClosed(p,c));a.equal(db.writes,0);a.deepEqual(db.saved,p)});
 await test('confirmed result row cannot be closed',async()=>{const r={...copy(p),state:'confirmed',confirmedPacket:result},db=model(r);await a.rejects(()=>A.create(db).markEntryClosed(r,proof));a.equal(db.writes,0);a.deepEqual(db.saved,r)});
 await test('closed row cannot accept later result confirmation',async()=>{const db=model(closed);await a.rejects(()=>A.create(db).markConfirmed(closed,result));a.equal(db.writes,0);a.deepEqual(db.saved,closed)});
 await test('pending row cannot carry closure',async()=>{a.throws(()=>A.row({...copy(p),entryClosure:proof}))});
 await test('closed row cannot carry staged result',async()=>{a.throws(()=>A.row({...copy(closed),confirmedPacket:result}))});
 const cert={atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),control,sourceSHA256:crypto.createHash('sha256').update(fs.readFileSync(__dirname+(control?'/directory-original.cjs':'/directory.cjs'))).digest('hex'),pass,fail,cases,scope:'Actual extracted directory source in synthetic transactional fault model; not native IndexedDB, authenticated closure, hybrid recovery, marker, HTML wiring, network or balance verification',excluded:'Initial build extraction used incorrect module end marker; harness-only assertion failed before candidate output. Corrected against actual HTML return module.exports})();.'};fs.writeFileSync(__dirname+(control?'/control-certificate.json':'/certificate.json'),JSON.stringify(cert,null,2));console.log({pass,fail});process.exitCode=fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=2});
