'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),{create}=require(process.env.MODEL_CONTROL?'./model-before-period-order.cjs':'./model.cjs');
const X={accountId:'actor',guildId:'guild',period:'2026-10-03',requestId:'one',heroIds:['vael']};
test('future period is HELD, never receives a terminal proof before its future starts are fenced',async()=>{const f=fixture(),s=create(f.store,{period:'2026-10-03'}),r=await s.cancel({...X,period:'2026-10-04'});a.equal(r.status,400);a.equal(r.terminal,undefined)});
function fixture(){let db={users:{actor:{guildId:'guild'}}},fail=false,tail=Promise.resolve();const store={atomic(fn){const run=tail.then(async()=>{const next=structuredClone(db),reply=await fn(next);if(fail)throw Error('Save refused');db=next;return reply});tail=run.catch(()=>{});return run}};return {store,read:()=>structuredClone(db),fault:x=>fail=x,service:()=>create(store,{period:'2026-10-03'})};}
test('cancel missing intent commits terminal proof and delayed identical start never spends',async()=>{const f=fixture(),s=f.service(),c=await s.cancel(X);a.equal(c.terminal.spent,false);a.deepEqual(await s.start(X),c);a.equal(f.read().users.actor.spent,undefined)});
test('committed start then cancel returns original accepted identity, not a no-spend proof',async()=>{const f=fixture(),s=f.service(),r=await s.start(X);a.deepEqual(await s.cancel(X),r);a.equal(f.read().users.actor.spent,1)});
test('failed cancellation save returns no proof; later retry commits before late start refusal',async()=>{const f=fixture(),s=f.service(),before=f.read();f.fault(true);await a.rejects(s.cancel(X),/Save refused/);a.deepEqual(f.read(),before);f.fault(false);const c=await s.cancel(X);a.deepEqual(await f.service().start(X),c);a.equal(f.read().users.actor.spent,undefined)});
test('same request with altered squad or guild cannot overwrite disposition',async()=>{const f=fixture(),s=f.service(),before=await s.cancel(X);a.equal((await s.start({...X,heroIds:['other']})).status,409);a.equal((await s.start({...X,guildId:'other'})).status,403);a.deepEqual(await s.cancel(X),before)});
test('bounded active records refuse without eviction; old period remains fenced after rollover',async()=>{const f=fixture(),s=create(f.store,{period:'2026-10-03',maxRecords:1});await s.cancel(X);a.equal((await s.cancel({...X,requestId:'two'})).status,503);a.equal(f.read().users.actor.raidEntryDispositions.length,1);const newer=create(f.store,{period:'2026-10-04',maxRecords:1});await newer.cancel({...X,period:'2026-10-04',requestId:'new'});const old=await newer.start(X);a.equal(old.terminal.kind,'period-closed');a.equal(old.terminal.spent,'unknown');a.equal(f.read().users.actor.spent,undefined)});
test('racing start and cancel linearize to one durable disposition',async()=>{for(const reverse of [false,true]){const f=fixture(),s=f.service(),r=await Promise.all(reverse?[s.start(X),s.cancel(X)]:[s.cancel(X),s.start(X)]);a.deepEqual(r[0],r[1]);a.equal(f.read().users.actor.spent||0,reverse?1:0)}});
