'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),B=require('./bootstrap.cjs'),A=require('./composition-facade.cjs'),{validateFreshEntryReply}=require('./fresh-entry-validator.cjs'),{validateEntryReply}=require('../guild-raid-response-binding-v942/validator.cjs');
function rig(){const rows=[],slots=new Map(),s={calls:[],fight:[],scheduled:[],current:true,deny:false},entry={requestId:'entry',heroIds:['hero']};
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.get(k)??null,setItem:(k,v)=>{if(s.deny)throw Error('Quota refused');slots.set(k,v)}},directory={list:async()=>rows,insertBounded:async r=>rows.push(r)};
 const context=()=>({accountId:'actor',guildId:'guild',token:'memory',epoch:s.current?1:2});
 const facade=A.create({storage,directory,context,locks:{request:async(_k,_o,fn)=>fn({})},legacyWritersQuiescent:async()=>true,validateFreshEntryReply,validateEntryReply,transport:async request=>{s.calls.push(request);if(s.send)await s.send();return {status:200,body:{ok:true,resumed:request.mode==='entry-recovery-only',seed:7,attemptId:'attempt',entryBinding:{v:1,accountId:'actor',guildId:'guild',requestId:'entry',heroIds:['hero']}}}}});
 const ui=B.create({facade,current:()=>s.current,onFight:x=>{s.fight.push(x);if(s.fightThrow)throw Error('Fight UI failed')},scheduleSettlement:x=>{a.equal(slots.size,1,'result saved BEFORE schedule');s.scheduled.push(x);if(s.scheduleThrow)throw Error('Timer failed')}});
 return {s,ui,rows,slots,entry,packet:{requestId:'result',attemptId:'attempt',inputLog:[],dmg:1}};
}
test('actual facade bootstrap carries exact saved instance into fight and saves before schedule',async()=>{const x=rig();await x.ui.launch(x.entry,'one');a.equal(x.s.fight[0].raidInstanceId,'one');a.equal(x.s.fight[0].raidEntryRequestId,'entry');a.equal(x.s.fight[0].attemptId,'attempt');a.deepEqual(x.ui.stageAndSchedule(x.packet),{staged:true});a.equal(x.s.scheduled[0].raidInstanceId,'one');a.equal(x.s.calls.length,1);a.equal(x.ui.owned().phase,'result')});
test('manual double launch cannot create another paid intent',async()=>{const x=rig();let release;x.s.send=()=>new Promise(r=>release=r);const first=x.ui.launch(x.entry,'one');await new Promise(r=>setImmediate(r));await a.rejects(x.ui.launch(x.entry,'two'),/held/);release();await first;a.equal(x.rows.length,1);a.equal(x.s.calls.length,1)});
test('result before acknowledged fight and wrong attempt never schedules',async()=>{const x=rig();a.throws(()=>x.ui.stageAndSchedule(x.packet),/No accepted/);await x.ui.launch(x.entry,'one');a.throws(()=>x.ui.stageAndSchedule({...x.packet,attemptId:'other'}),/mismatch/);a.equal(x.slots.size,0);a.equal(x.s.scheduled.length,0)});
test('storage denial holds fight and sends no result; same packet may retry stage',async()=>{const x=rig();await x.ui.launch(x.entry,'one');x.s.deny=true;a.throws(()=>x.ui.stageAndSchedule(x.packet),/Quota/);a.equal(x.ui.owned().phase,'fight');a.equal(x.s.scheduled.length,0);x.s.deny=false;x.ui.stageAndSchedule(x.packet);a.equal(x.s.scheduled.length,1)});
test('scheduling failure retains staged result and prevents replacement launch',async()=>{const x=rig();await x.ui.launch(x.entry,'one');x.s.scheduleThrow=true;a.throws(()=>x.ui.stageAndSchedule(x.packet),/Timer/);a.equal(x.slots.size,1);a.equal(x.ui.owned().phase,'result');await a.rejects(x.ui.launch(x.entry,'two'),/held/);a.equal(x.s.calls.length,1)});
test('visual fight callback failure retains paid owner without replacement',async()=>{const x=rig();x.s.fightThrow=true;await a.rejects(x.ui.launch(x.entry,'one'),/UI/);a.equal(x.ui.owned().id,'one');await a.rejects(x.ui.launch(x.entry,'two'),/held/);a.equal(x.s.calls.length,1)});
test('stale response cannot start visual fight or stage',async()=>{const x=rig();x.s.send=()=>{x.s.current=false};await a.rejects(x.ui.launch(x.entry,'one'),/Stale/);a.equal(x.s.fight.length,0);a.throws(()=>x.ui.stageAndSchedule(x.packet),/Stale/);a.equal(x.s.scheduled.length,0)});
test('discovery exposes saved pending only and resume uses exact recovery mode',async()=>{const x=rig();x.rows.push({v:3,accountId:'actor',guildId:'guild',id:'one',entry:x.entry,state:'pending'});a.deepEqual(await x.ui.discover(),[{id:'one',status:'entry-recovery-only'}]);a.equal(x.s.calls.length,0);await x.ui.resume('one');a.equal(x.s.calls[0].mode,'entry-recovery-only');x.ui.stageAndSchedule(x.packet);a.equal(x.s.scheduled.length,1)});
test('missing recovery instance cannot fall back to a fresh entry',async()=>{const x=rig();await a.rejects(x.ui.resume('missing'),/Resume state/);a.equal(x.s.calls.length,0);a.equal(x.s.fight.length,0);a.equal(x.rows.length,0)});
