'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),A=require(process.env.FRESH_CONTROL?'./facade-before-fresh-binding.cjs':'./composition-facade.cjs'),{validateFreshEntryReply}=require('./fresh-entry-validator.cjs');
function fixture(){const rows=[],slots=new Map(),s={calls:0,current:true};const entry={requestId:'entry',heroIds:['hero']};s.reply={status:200,body:{ok:true,attemptId:'attempt',seed:7,entryBinding:{v:1,accountId:'actor',guildId:'guild',requestId:'entry',heroIds:['hero']}}};
 const directory={list:async()=>rows,insertBounded:async r=>rows.push(r)},storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.get(k)??null,setItem:(k,v)=>slots.set(k,v)};
 const client=A.create({directory,storage,context:()=>({accountId:'actor',guildId:'guild',token:'memory',epoch:s.current?1:2}),locks:{request:async(_n,_o,fn)=>fn({})},legacyWritersQuiescent:async()=>true,transport:async()=>{s.calls++;if(s.send)await s.send();return s.reply},validateFreshEntryReply:async x=>{if(s.validate)await s.validate();return validateFreshEntryReply(x)}});
 return {client,s,entry,rows,slots,packet:{requestId:'result',attemptId:'attempt',inputLog:[],dmg:1}};
}
test('fresh acknowledged attempt stages synchronously with matching binding',async()=>{const x=fixture(),r=await x.client.start(x.entry,'one');x.client.stage(r.row,x.packet);a.equal(x.slots.size,1);a.equal(x.s.calls,1)});
test('fresh result cannot use a different attempt',async()=>{const x=fixture(),r=await x.client.start(x.entry,'one');a.throws(()=>x.client.stage(r.row,{...x.packet,attemptId:'other'}),/binding/);a.equal(x.slots.size,0)});
test('stage before entry reply validation is refused',async()=>{const x=fixture();let release;x.s.send=()=>new Promise(r=>release=r);const started=x.client.start(x.entry,'one');await new Promise(r=>setImmediate(r));a.equal(x.rows.length,1);a.throws(()=>x.client.stage(x.rows[0],x.packet),/binding/);release();await started;a.equal(x.slots.size,0)});
test('missing fresh binding holds saved identity; no replacement enrollment',async()=>{const x=fixture();delete x.s.reply.body.entryBinding;await a.rejects(x.client.start(x.entry,'one'),/binding/);a.equal(x.rows.length,1);await a.rejects(x.client.start(x.entry,'two'),/Recover existing/);a.equal(x.s.calls,1)});
test('wrong squad or account identity refuses fresh reply',async()=>{for(const change of [b=>b.entryBinding.heroIds=['other'],b=>b.entryBinding.accountId='other']){const x=fixture();change(x.s.reply.body);await a.rejects(x.client.start(x.entry,'one'),/identity mismatch/);a.throws(()=>x.client.stage(x.rows[0],x.packet),/binding/);a.equal(x.slots.size,0)}});
test('unknown recovery status cannot grant fresh result writer',async()=>{const x=fixture();x.s.reply={status:409,body:{ok:false,recoveryUnknown:true}};await a.rejects(x.client.start(x.entry,'one'),/binding/);a.throws(()=>x.client.stage(x.rows[0],x.packet),/binding/);a.equal(x.s.calls,1)});
test('session change during authenticated validation prevents writer acceptance',async()=>{const x=fixture();x.s.validate=()=>{x.s.current=false};await a.rejects(x.client.start(x.entry,'one'),/Stale session/);a.equal(x.slots.size,0)});
test('invalid seed or exhausted attempts cannot acknowledge a launch',async()=>{for(const change of [b=>b.seed=-1,b=>b.none=true]){const x=fixture();change(x.s.reply.body);await a.rejects(x.client.start(x.entry,'one'),/binding|shape/);a.equal(x.rows.length,1);a.equal(x.slots.size,0)}});
