'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{test}=require('node:test'),a=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'private-bootstrap-heroes.html'),'utf8'),begin=html.indexOf('const EW_RAID_V3_MODULES='),end=html.indexOf('/* The damage this fight has done to the raid boss:',begin);let source=html.slice(begin,end);
if(process.env.STALE_RENDER_CONTROL){const fixed='render:r=>{if(RAID_SETTLEMENT===pending)RAID_SETTLEMENT=null;if(resultStale(ep))return;raidRenderConfirmed(r,RB,ep)}',old='render:r=>{if(resultStale(ep))return;raidRenderConfirmed(r,RB,ep);if(RAID_SETTLEMENT===pending)RAID_SETTLEMENT=null}';a.equal(source.split(fixed).length,2);source=source.replace(fixed,old)}
function rig(){const s={fight:0,grants:0,scheduled:[],notices:[],trace:[],stageFail:false,choices:[],settled:{status:200,body:{cleanupOnly:true}}},G={guild:{id:'guild'}},ACC={id:'actor',token:'memory'},elements={};
 const context=vm.createContext({G,ACC,CUR:{},navigator:{},TEAM_SIZE:3,console,Promise,Uint8Array,TextEncoder,crypto:require('node:crypto').webcrypto,window:{},indexedDB:{},localStorage:{},s,
  startBattle:()=>s.fight++,squadFor:()=>['hero'],uid8:(()=>{let id=0;return()=>String(++id)})(),resultLater:fn=>{s.trace.push('timer');s.scheduled.push(fn)},resultStale:()=>false,bannerMsg:m=>s.notices.push(m),adoptLedger:()=>s.grants++,setResultVerdict:()=>{},document:{getElementById:id=>elements[id]||(elements[id]={})},escapeHTML:String,updateHubChrome:()=>{},show:()=>{},gameSpeed:1});
 vm.runInContext(source,context);
 const facade={current:()=>true,start:async(entry,id)=>({row:{id,entry},reply:{status:200,body:{ok:true,attemptId:'attempt',seed:7,entryBinding:{heroIds:entry.heroIds},snaps:[{key:'hero'}],boss:{key:'boss',hp:123,lvl:2,def:9,dmgMul:1,tier:4,name:'Boss'},engine:'authored'}}}),resume:async id=>facade.start({requestId:'saved-entry',heroIds:['hero']},id),stage:()=>{s.trace.push('stage');if(s.stageFail)throw Error('Quota refused')},discover:async()=>s.choices,settle:async()=>s.settled};
 context.facade=facade;
 vm.runInContext("const runtime={current:()=>true,facade,bootstrap:EW_RAID_V3_MODULES.bootstrap.create({facade,current:()=>true,onFight:x=>raidStartAccepted(x.reply.body,x.raidInstanceId,x.raidEntryRequestId),scheduleSettlement:x=>raidSettlementRun(x.raidInstanceId,CUR.raid||{})})};RAID_V3={current:()=>true,ready:Promise.resolve(runtime)};",context);
 return {context,s,elements,call:code=>vm.runInContext(code,context),flush:()=>new Promise(r=>setImmediate(r))};
}
test('generated fullHTML hook starts authored fight with recovery CUR identity',async()=>{const x=rig();await x.call('raidLaunch()');a.equal(x.s.fight,1);a.equal(x.context.CUR.raidInstanceId,'raid-2');a.equal(x.context.CUR.raidEntryRequestId,'1');a.equal(x.context.CUR.attemptId,'attempt');a.equal(x.context.CUR.cwaves[0][0].hp,123);a.equal(x.context.CUR.cwaves[0][0].def,9);a.equal(x.context.CUR.engine,'authored')});
test('generated result queue stages before scheduling any settlement',async()=>{const x=rig();await x.call('raidLaunch()');x.call("raidSettlementQueue({attemptId:'attempt',requestId:'result',inputLog:[],dmg:1},CUR.raid)");await x.flush();a.deepEqual(x.s.trace,['stage','timer']);a.equal(x.s.scheduled.length,1)});
test('generated storage refusal schedules nothing and same packet retry remains available',async()=>{const x=rig();await x.call('raidLaunch()');x.s.stageFail=true;x.call("raidSettlementQueue({attemptId:'attempt',requestId:'result',inputLog:[],dmg:1},CUR.raid)");await x.flush();a.equal(x.s.scheduled.length,0);x.s.stageFail=false;x.call('raidResolveRetry()');await x.flush();a.deepEqual(x.s.trace,['stage','stage','timer']);a.equal(x.s.fight,1)});
test('generated confirmed cleanup renders no reward and starts no fight',async()=>{const x=rig();x.s.choices=[{id:'saved',status:'confirmed-cleanup'}];await x.call('raidRecoverSaved()');await x.s.scheduled[0](1);a.equal(x.s.fight,0);a.equal(x.s.grants,0);a.equal(x.elements.resultReward,undefined);a.equal(x.call('RAID_SETTLEMENT'),null);a.match(x.s.notices[0],/No new reward/)});
test('generated authenticated expired cleanup renders no reward and clears owner',async()=>{const x=rig();x.s.choices=[{id:'saved',status:'result-recovery-only'}];x.s.settled={status:200,body:{ok:false,expired:true,settlementBinding:{}}};await x.call('raidRecoverSaved()');await x.s.scheduled[0](1);a.equal(x.s.grants,0);a.equal(x.call('RAID_SETTLEMENT'),null);a.match(x.s.notices[0],/expired/)});
test('generated ambiguous recovery cannot choose a paid entry automatically',async()=>{const x=rig();x.s.choices=[{id:'one',status:'entry-recovery-only'},{id:'two',status:'entry-recovery-only'}];await x.call('raidRecoverSaved()');a.equal(x.s.fight,0);a.equal(x.s.scheduled.length,0);a.match(x.s.notices[0],/Multiple saved/)});
test('generated real factory default quiescence gate holds before storage enrollment or network',async()=>{const x=rig();let calls=0;x.context.navigator.locks={request:async(_n,_o,fn)=>fn({})};x.context.fetch=async()=>{calls++;throw Error('Unexpected network')};x.context.localStorage={length:0,key:()=>null,getItem:()=>null};x.context.indexedDB.open=()=>{const q={result:{transaction:()=>{throw Error('Unexpected directory enrollment')},close:()=>{}}};setImmediate(()=>q.onsuccess());return q};x.call('RAID_V3=null');await x.call('raidLaunch()');a.equal(calls,0);a.equal(x.s.fight,0);a.match(x.s.notices[0],/not proven quiescent/)});
test('confirmed response on stale result screen retires matching UI owner without reward adoption',async()=>{const x=rig();x.s.choices=[{id:'saved',status:'result-recovery-only'}];x.s.settled={status:200,body:{ok:true,ledger:{gold:999},dmg:1}};x.context.resultStale=()=>true;await x.call('raidRecoverSaved()');await x.s.scheduled[0](1);a.equal(x.call('RAID_SETTLEMENT'),null);a.equal(x.s.grants,0);a.equal(x.elements.resultReward,undefined)});
