'use strict';const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.join(__dirname,'../shady-gold-v942/snapshot'),server=path.join(root,'server.js'),leader=path.join(root,'tests/guild-leadership.test.cjs'),saved=fs.readFileSync(server),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
assert.equal(hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');assert(!fs.existsSync(leader));assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
async function run(){let f,copied=false;try{
 fs.copyFileSync(path.join(__dirname,'../guild-raid-settlement-binding-v942/payload/server.js'),server);
 const file=path.join(root,'tests/private-composition-http.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(fs.readFileSync(path.join(__dirname,'../guild-raid-recovery-only-v942/tests.cjs'),'utf8').split('const E=')[0].replace('root=process.env.GUILD_FIXTURE_ROOT','root='+JSON.stringify(root)).replace("path.join(root,'tests/guild-leadership.test.cjs')",JSON.stringify(path.join(__dirname,'../guild-leadership-v942/tests.cjs')))+'\nmodule.exports={setup};',file);({f}=await m.exports.setup());
 const A=require('./composition-facade.cjs'),slots=new Map(),rows=new Map(),calls=[],copy=x=>JSON.parse(JSON.stringify(x));let lost=true,lostResult=true,retireFail=true;
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.get(k)??null,setItem:(k,v)=>slots.set(k,v)};
 const directory={list:async(a,n)=>[...rows.values()].filter(x=>x.accountId===a).slice(0,n).map(copy),insertBounded:async r=>{assert(!rows.has(r.id));rows.set(r.id,copy(r))},markConfirmed:async(r,p)=>{const own=rows.get(r.id);assert.equal(own.state,'pending');rows.set(r.id,{...own,state:'confirmed',confirmedPacket:copy(p)})},retireConfirmed:async r=>{assert.equal(rows.get(r.id).state,'confirmed');if(retireFail)throw Error('Retirement interrupted');rows.delete(r.id)}};
 const session={accountId:'fixture-user',guildId:'own-guild',token:'generic-fixture-token',epoch:1};const {createTransport}=require('../guild-raid-response-binding-v942/transport.cjs');
 const authenticatedTransport=createTransport({context:()=>session,fetch:async(route,options)=>{const r=await f.call(route,JSON.parse(options.body),options.headers['x-token']);return {status:r.status,json:async()=>r.body};}});
 const transport=async p=>{calls.push({mode:p.mode,packet:copy(p.packet)});const reply=await authenticatedTransport(p);if(lost){lost=false;throw Error('Committed reply lost')}if(p.mode==='result-recovery-only'&&lostResult){lostResult=false;throw Error('Committed result reply lost')}return reply;};
 const {validateEntryReply}=require('../guild-raid-response-binding-v942/validator.cjs'),{validateSettlement}=require('../guild-raid-settlement-binding-v942/validator.cjs');const validateSettlementReply=x=>validateSettlement({...x,digest:async raw=>hash(raw)});
 const deps={directory,storage,locks:{request:async(k,o,fn)=>fn({})},transport,legacyWritersQuiescent:async()=>true,validateEntryReply,validateSettlementReply};
 function fresh(){return vm.runInNewContext("A.create({...deps,context:()=>({...session})})",{A,deps,session})}
 const E={requestId:'composition-entry',heroIds:['vael']};await assert.rejects(fresh().start(E,'entry-instance'),/Committed reply lost/);assert.equal(rows.size,1);const committed=f.bytes(),attempt=f.disk().guilds['own-guild'].raid.att['fixture-user'].id;
 await f.stop();await f.launch();assert.equal(calls.length,1);const recovery=await fresh().recover('entry-instance');assert.equal(recovery.reply.status,200);assert.equal(recovery.reply.body.resumed,true);assert.equal(recovery.reply.body.attemptId,attempt);assert.deepEqual(calls.map(x=>x.mode),['fresh-entry','entry-recovery-only']);assert.deepEqual(calls[0].packet,calls[1].packet);assert.equal(f.bytes(),committed);assert.equal(f.disk().users['fixture-user'].raidDay.n,1);
 await assert.rejects(fresh().recover('missing-instance'),/No recoverable/);assert.equal(calls.length,2);assert.equal(f.bytes(),committed);
 const resumedClient=fresh(),resumed=await resumedClient.resume('entry-instance'),P={requestId:'result',attemptId:attempt,inputLog:[],dmg:10};resumedClient.stage(resumed.row,P);assert.equal(slots.size,1,'Synchronous result stage before any delayed send');
 await assert.rejects(resumedClient.settle('entry-instance'),/Committed result reply lost/);assert.equal(rows.size,1);const settled=f.bytes(),txs=f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length;assert.equal(txs,1);await f.stop();await f.launch();const count=calls.length;
 await assert.rejects(fresh().settle('entry-instance'),/Retirement interrupted/);assert.equal(calls.length,count+1);assert.deepEqual(calls.at(-2).packet,calls.at(-1).packet);assert.equal(rows.get('entry-instance').state,'confirmed');assert.equal(JSON.parse([...slots.values()][0]).confirmed,true);
 // Lose the terminal slot after committed confirmation, then reload/restart.
 // Discovery must recreate the exact fence before retirement, without HTTP.
 slots.clear();await f.stop();await f.launch();retireFail=false;const final=await fresh().settle('entry-instance');assert.equal(final.body.cleanupOnly,true);assert.equal(calls.length,count+1);assert.equal(f.bytes(),settled);assert.equal(f.disk().users['fixture-user'].raidDay.n,1);assert.equal(f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,1);assert.equal(rows.size,0);assert.equal(slots.size,1);const terminal=JSON.parse([...slots.values()][0]);assert.equal(terminal.confirmed,true);assert.deepEqual(terminal.packet,P);assert.throws(()=>resumedClient.stage(resumed.row,P),/Immutable slot conflict/);await assert.rejects(fresh().settle('entry-instance'),/No staged result/);assert.equal(calls.length,count+1);
 fs.writeFileSync(path.join(__dirname,'integration-results.json'),JSON.stringify({at:new Date().toISOString(),pass:true,serverHash:hash(fs.readFileSync(server)),validatorHash:hash(fs.readFileSync(path.join(__dirname,'../guild-raid-settlement-binding-v942/validator.cjs'))),facadeHash:hash(fs.readFileSync(path.join(__dirname,'composition-facade.cjs'))),hybridHash:hash(fs.readFileSync(path.join(__dirname,'hybrid-adapter.cjs'))),calls,entryCount:1,raidTransactions:txs,pendingRows:0,retainedTerminalMarkers:1,scope:'Actual private HTTP authenticated bound result confirmation, lost committed replies/server restarts; injected retirement failure then freshVM cleanup-only recovery recreates missing terminal marker with ZERO additional network and one entry/grant. Storage/directory/locks/quiescence are models, not native HTML.',open:'Native cleanup/permissions/quota/legacy compatibility/bootstrap/package remain OPEN.'},null,2));console.log('PASS interrupted confirmed retirement/restart/missing terminal marker cleanup-only ZERO further network; one entry/grant');
}finally{if(f)await f.stop();fs.writeFileSync(server,saved);assert.equal(hash(fs.readFileSync(server)),hash(saved));}}
run().catch(e=>{console.error(e);process.exitCode=1});
