'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
if(fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'))throw Error('Shutdown');
const src=n=>fs.readFileSync(path.join(__dirname,n),'utf8'),h=src('hybrid-adapter.cjs'),a=src('composition-facade.cjs'),d=fs.readFileSync(path.join(__dirname,'../guild-raid-discovery-design-v942/native-directory.cjs'),'utf8'),hash=x=>crypto.createHash('sha256').update(x).digest('hex'),session=crypto.randomUUID();
const hashes={hybrid:hash(h),facade:hash(a),directory:hash(d)};let reports=[];
const html=`<!doctype html><meta charset="utf-8"><title>Private confirmed cleanup recovery</title><style>body{font:16px system-ui;margin:25px;background:#142033;color:white}button{padding:12px;margin:6px}pre{white-space:pre-wrap}</style><h1>Private confirmed cleanup recovery</h1><p>Native browser storage only. Synthetic committed confirmations; no game or paid requests.</p><button id="prepare">Prepare interrupted confirmations</button><button id="recover">Recover persisted confirmations</button><pre id="out">Opening</pre><script>
const H=(()=>{const module={exports:{}};${h};return module.exports})();
const D=(()=>{const module={exports:{}};${d};return module.exports})();
const HybridOuter=H,A=(()=>{const module={exports:{}},require=n=>HybridOuter;${a};return module.exports})();
const session=${JSON.stringify(session)},hashes=${JSON.stringify(hashes)},P={requestId:'result',attemptId:'attempt',inputLog:[],dmg:10};let db,results=[],calls=0;
const assert=(v,m)=>{if(!v)throw Error(m)},deny=async fn=>{let refused=false;try{await fn()}catch{refused=true}assert(refused,'expected refusal')};
const row=accountId=>({v:3,accountId,guildId:'guild',id:'slot',entry:{requestId:'entry',heroIds:['hero']},state:'pending'});
async function show(extra={}){const data={session,hashes,results,calls,...extra};document.getElementById('out').textContent=JSON.stringify(data,null,2);await fetch('/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)})}
function facade(accountId,directory=D.create(db),storage=localStorage){return A.create({directory,storage,context:()=>({accountId,guildId:'guild',token:'synthetic-memory-only',epoch:1}),locks:navigator.locks,legacyWritersQuiescent:async()=>true,validateSettlementReply:async()=>true,transport:async()=>{calls++;throw Error('Forbidden network')}})}
async function test(name,fn){try{await fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:String(e)})}await show()}
document.getElementById('prepare').onclick=async()=>{document.getElementById('prepare').disabled=true;const b=D.create(db);for(const account of ['existing','missing','denied','aborted']){const r=row(account);await b.insertBounded(r,4);await b.markConfirmed(r,P);if(account==='existing')localStorage.setItem(H.key(r),JSON.stringify({v:3,accountId:account,guildId:'guild',instanceId:'slot',entryRequestId:'entry',packet:P,confirmed:true}))}await show({prepared:true,persistedAccounts:4})};
document.getElementById('recover').onclick=async()=>{document.getElementById('recover').disabled=true;
for(const account of ['existing','missing'])await test('native persisted '+account+' marker cleanup-only zero transport',async()=>{assert((await D.create(db).list(account,5))[0].state==='confirmed','missing persisted confirmation');const reply=await facade(account).settle('slot');assert(reply.body.cleanupOnly===true,'not cleanup only');assert((await D.create(db).list(account,5)).length===0,'not retired');const marker=JSON.parse(localStorage.getItem(H.key(row(account))));assert(marker.confirmed===true&&JSON.stringify(marker.packet)===JSON.stringify(P),'terminal fence');assert(calls===0,'network called')});
await test('native confirmed row survives simulated marker write denial and retry',async()=>{const storage={get length(){return localStorage.length},key:i=>localStorage.key(i),getItem:k=>localStorage.getItem(k),setItem:()=>{throw Error('Injected storage denial')}};await deny(()=>facade('denied',D.create(db),storage).settle('slot'));assert((await D.create(db).list('denied',5))[0].state==='confirmed','lost confirmation');await facade('denied').settle('slot');assert((await D.create(db).list('denied',5)).length===0,'retry failed');assert(calls===0,'network')});
await test('native retirement transaction abort preserves confirmation and terminal fence',async()=>{const wrapper={transaction(name,mode){const t=db.transaction(name,mode);const open=t.objectStore.bind(t);t.objectStore=name=>{const s=open(name),del=s.delete.bind(s);s.delete=key=>{const q=del(key);q.addEventListener('success',()=>t.abort());return q};return s};return t}};const abortD=D.create(wrapper),b=D.create(db);await deny(()=>facade('aborted',abortD).settle('slot'));assert((await b.list('aborted',5))[0].state==='confirmed','abort retired');assert(JSON.parse(localStorage.getItem(H.key(row('aborted')))).confirmed===true,'fence absent');await facade('aborted').settle('slot');assert((await b.list('aborted',5)).length===0,'retry failed');assert(calls===0,'network')});await show({complete:true})};
const open=indexedDB.open('codex-confirmed-cleanup-'+session,1);open.onupgradeneeded=()=>{const s=open.result.createObjectStore('slots',{keyPath:['accountId','id']});s.createIndex('account','accountId')};open.onsuccess=()=>{db=open.result;show({ready:true,secureContext:isSecureContext,webLocks:!!navigator.locks})};
</script>`;
new(require('node:vm').Script)(html.match(/<script>([\s\S]*)<\/script>/)[1]);
const server=http.createServer(async(req,res)=>{if(req.url==='/shutdown'){res.end('Stopped');server.close(()=>process.exit(0));server.closeAllConnections();return}if(req.url==='/report'&&req.method==='POST'){let raw='';for await(const b of req){raw+=b;if(raw.length>200000){res.writeHead(413).end();return}}reports.push(JSON.parse(raw));fs.writeFileSync(path.join(__dirname,'native-evidence.json'),JSON.stringify({session,hashes,reports},null,2));res.end('Saved');return}res.setHeader('content-type','text/html');res.end(html)});server.listen(0,'127.0.0.1',()=>console.log(JSON.stringify({url:'http://127.0.0.1:'+server.address().port,session,hashes})));setTimeout(()=>{server.close(()=>process.exit(0));server.closeAllConnections()},240000).unref();
