'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),P=require('./presentation.cjs');
function rig(settle){const p={},s={owner:p,current:true,render:0,notice:0};const ui=P.create({facade:{settle,current:()=>s.current},current:()=>s.current,owner:()=>s.owner,setOwner:x=>s.owner=x,pending:p,render:()=>s.render++,notice:()=>s.notice++});return{s,ui,p};}
test('cleanup-only clears its UI owner without reward rendering',async()=>{const r=rig(async()=>({status:200,body:{cleanupOnly:true}}));a.deepEqual(await r.ui.recover('x'),{cleanupOnly:true});a.equal(r.s.owner,null);a.equal(r.s.render,0);a.equal(r.s.notice,1);});
test('cleanup-only with ledger/reward fields is rejected and retains UI owner',async()=>{const r=rig(async()=>({status:200,body:{cleanupOnly:true,ledger:{gold:999}}}));await a.rejects(r.ui.recover('x'),/Invalid/);a.equal(r.s.owner,r.p);a.equal(r.s.render,0);});
test('stale session after facade await cannot mutate UI',async()=>{let r;r=rig(async()=>{r.s.current=false;return{status:200,body:{cleanupOnly:true}};});await a.rejects(r.ui.recover('x'),/Stale/);a.equal(r.s.owner,r.p);a.equal(r.s.notice,0);});
test('replacement pending owner cannot be cleared by an old reply',async()=>{let r;const replacement={};r=rig(async()=>{r.s.owner=replacement;return{status:200,body:{cleanupOnly:true}};});await a.rejects(r.ui.recover('x'),/Stale/);a.equal(r.s.owner,replacement);});
test('same controller manual double click is singleflight',async()=>{let release,n=0;const r=rig(()=>{n++;return new Promise(res=>release=res);});const first=r.ui.recover('x');await a.rejects(r.ui.recover('x'),/already/);release({status:200,body:{cleanupOnly:true}});await first;a.equal(n,1);});
test('confirmed settlement follows existing reward renderer once',async()=>{const r=rig(async()=>({status:200,body:{ok:true,ledger:{gold:1}}}));a.deepEqual(await r.ui.recover('x'),{presented:true});a.equal(r.s.render,1);a.equal(r.s.notice,0);});
test('facade failure leaves pending owner held without fresh fallback',async()=>{let n=0;const r=rig(async()=>{n++;throw Error('Held409');});await a.rejects(r.ui.recover('x'),/Held409/);a.equal(r.s.owner,r.p);a.equal(r.s.render,0);a.equal(n,1);});
