'use strict';const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),A=require(process.env.ORIGINAL? './facade-original.cjs':'./composition-facade.cjs'),H=require(process.env.ORIGINAL?'./hybrid-original.cjs':'./hybrid-adapter.cjs'),copy=x=>JSON.parse(JSON.stringify(x));
const E={requestId:'entry',heroIds:['hero']},P={requestId:'result',attemptId:'attempt',inputLog:[],dmg:1},R={v:3,accountId:'actor',guildId:'guild',id:'one',entry:E,state:'pending'};
function fixture(){const rows=new Map([['one',copy(R)]]),slots=new Map([[H.key(R),JSON.stringify({v:3,accountId:'actor',guildId:'guild',instanceId:'one',entryRequestId:'entry',packet:P})]]),f={calls:0,retireFail:true,writeFail:false,current:true};
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.get(k)??null,setItem:(k,v)=>{if(f.writeFail)throw Error('Storage denied');slots.set(k,v)}};
 const directory={list:async()=>[...rows.values()].map(copy),markConfirmed:async(r,p)=>rows.set(r.id,{...copy(r),state:'confirmed',confirmedPacket:copy(p)}),retireConfirmed:async r=>{if(f.retireFail)throw Error('Retire interrupted');rows.delete(r.id)},insertBounded:async()=>{throw Error('No fresh entry')}};
 f.client=()=>A.create({storage,directory,context:()=>({accountId:'actor',guildId:'guild',token:'memory-only',epoch:f.current?1:2}),locks:{request:async(k,o,fn)=>fn({})},transport:async()=>{f.calls++;return {status:200,body:{ok:true}}},validateSettlementReply:async()=>true,legacyWritersQuiescent:async()=>true});
 f.h=()=>H.create(directory,storage,{isCurrent:()=>f.current,legacyCheck:async()=> 'clear'});f.rows=rows;f.slots=slots;f.storage=storage;f.directory=directory;return f;
}
test('interrupted confirmed retirement resumes cleanup only with no second network call',async()=>{const f=fixture();await assert.rejects(f.client().settle('one'),/Retire interrupted/);assert.equal(f.calls,1);assert.equal(f.rows.get('one').state,'confirmed');f.retireFail=false;const r=await f.client().settle('one');assert.equal(r.body.cleanupOnly,true);assert.equal(f.calls,1);assert.equal(f.rows.size,0);assert.equal(JSON.parse([...f.slots.values()][0]).confirmed,true)});
test('missing terminal slot is reconstructed before retiring confirmed directory row',async()=>{const f=fixture();f.rows.set('one',{...copy(R),state:'confirmed',confirmedPacket:copy(P)});f.slots.clear();f.retireFail=false;await f.h().cleanup({accountId:'actor',guildId:'guild'},'one');assert.equal(f.rows.size,0);assert.equal(JSON.parse(f.slots.get(H.key(R))).confirmed,true)});
test('terminal marker write failure leaves confirmed row available to retry',async()=>{const f=fixture();f.rows.set('one',{...copy(R),state:'confirmed',confirmedPacket:copy(P)});f.writeFail=true;f.retireFail=false;await assert.rejects(f.h().cleanup({accountId:'actor',guildId:'guild'},'one'),/Storage denied/);assert.equal(f.rows.size,1);f.writeFail=false;await f.h().cleanup({accountId:'actor',guildId:'guild'},'one');assert.equal(f.rows.size,0)});
test('conflicting confirmed packet refuses retirement',async()=>{const f=fixture();f.rows.set('one',{...copy(R),state:'confirmed',confirmedPacket:{...P,dmg:2}});f.retireFail=false;await assert.rejects(f.h().cleanup({accountId:'actor',guildId:'guild'},'one'),/conflict/);assert.equal(f.rows.size,1)});
test('unknown result never sends or creates new entry',async()=>{const f=fixture();await assert.rejects(f.client().settle('unknown'),/No staged result/);assert.equal(f.calls,0);assert.equal(f.rows.size,1)});
test('cleanup edge missing-marker storage denial preserves confirmation and sends nothing',async()=>{const f=fixture();f.rows.set('one',{...copy(R),state:'confirmed',confirmedPacket:copy(P)});f.slots.clear();f.writeFail=true;f.retireFail=false;await assert.rejects(f.client().settle('one'),/Storage denied/);assert.equal(f.calls,0);assert.equal(f.rows.get('one').state,'confirmed');assert.equal(f.slots.size,0)});
test('cleanup edge missing-marker readback failure refuses retirement',async()=>{const f=fixture();f.rows.set('one',{...copy(R),state:'confirmed',confirmedPacket:copy(P)});f.slots.clear();f.retireFail=false;f.storage.setItem=()=>{};await assert.rejects(f.client().settle('one'),/Cleanup readback/);assert.equal(f.calls,0);assert.equal(f.rows.size,1)});
test('cleanup edge stale session after discovery cannot write or retire confirmation',async()=>{const f=fixture();f.rows.set('one',{...copy(R),state:'confirmed',confirmedPacket:copy(P)});f.slots.clear();f.retireFail=false;const c=f.client(),list=f.directory.list;f.directory.list=async()=>{const rows=await list();f.current=false;return rows};await assert.rejects(c.settle('one'),/Stale/);assert.equal(f.calls,0);assert.equal(f.rows.size,1);assert.equal(f.slots.size,0)});
test('cleanup edge reconstructed terminal marker fences old enrolled writer after retirement',async()=>{const f=fixture();f.rows.clear();f.slots.clear();f.retireFail=false;f.directory.insertBounded=async r=>f.rows.set(r.id,copy(r));const old=f.h(),row=await old.enroll({accountId:'actor',guildId:'guild'},E,'one');old.stage(row,P);f.rows.set('one',{...row,state:'confirmed',confirmedPacket:copy(P)});f.slots.clear();await f.client().settle('one');assert.throws(()=>old.stage(row,P),/Immutable slot conflict/);assert.equal(f.calls,0);assert.equal(f.rows.size,0);assert.equal(JSON.parse(f.slots.get(H.key(R))).confirmed,true)});
