'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../server.js'),'utf8');
const slice=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a)));
function fixture(){const user={id:'u',wallet:10},other={id:'v',wallet:20},DB={users:{u:user,v:other},idem:{},feedback:[],reports:[],watch:{}};let disk=JSON.stringify(DB),fail='',writes=0,renames=0,pg=0,clock=1000;
const context={DB,DB_FILE:'fixture.json',PG_BOOT_PENDING:false,_worldSettlementPlanning:null,Date:{now:()=>clock},console:{error(){},log(){}},fs:{writeFileSync(p,s){writes++;if(fail==='write')throw Error('write fault');context.stagedText=s;},renameSync(p,to){renames++;if(fail==='rename')throw Error('rename fault');disk=context.stagedText;}},pgSave(){pg++;if(fail==='pg')throw Error('replica fault');},_adoptUser(id,draft){const live=DB.users[id];for(const k of Object.keys(live))if(!(k in draft))delete live[k];Object.assign(live,draft);}};
vm.createContext(context);vm.runInContext(slice('function saveDB(','function writeDB(')+slice('function durableCommit(','function worldSettlementDurable('),context);
return {context,DB,user,other,get disk(){return disk;},fail(x){fail=x;},clock(x){clock=x;},counts:()=>({writes,renames,pg})};}
const clone=x=>JSON.parse(JSON.stringify(x));
test('Generic commit write/rename fail do not publish actor, declared collections or receipt; retry/replay once, identity retained',()=>{for(const fault of ['write','rename']){const f=fixture(),before=clone(f.DB),disk=f.disk;const plan=(draft,staged)=>{draft.wallet-=3;staged.feedback.push({signal:'s'});staged.reports.push({report:'r'});return {ok:true,wallet:draft.wallet};};f.fail(fault);const bad=f.context.durableCommit(f.user,'u:key',plan);assert.equal(bad.storageFailed,true);assert.deepEqual(f.DB,before);assert.equal(f.disk,disk);assert.equal(f.context._worldSettlementPlanning,null);f.fail('');const good=f.context.durableCommit(f.user,'u:key',plan);assert.equal(good.wallet,7);assert.equal(f.DB.users.u,f.user);assert.equal(f.other.wallet,20);assert.deepEqual(clone(JSON.parse(f.disk)),clone(f.DB));const committed=f.disk;assert.deepEqual(f.context.durableCommit(f.user,'u:key',()=>{throw Error('must not rerun');}),good);assert.equal(f.disk,committed);}});
test('Generic invalid/refused/throwing/async/nested planners restore context, do not reserve receipt; boot/time gates',()=>{const f=fixture(),before=clone(f.DB),disk=f.disk;const refused=f.context.durableCommit(f.user,'bad',(draft)=>{draft.wallet=0;return {ok:false,error:'refused'};});assert.equal(refused.ok,false);assert.deepEqual(f.DB,before);assert.equal(f.disk,disk);assert.throws(()=>f.context.durableCommit(f.user,'throw',()=>{throw Error('planner');}),/planner/);assert.equal(f.context._worldSettlementPlanning,null);assert.throws(()=>f.context.durableCommit(f.user,'async',async()=>({ok:true})),/synchronous/);assert.throws(()=>f.context.durableCommit(f.user,'promise',()=>Promise.resolve({ok:true})),/synchronous/);assert.equal(f.context._worldSettlementPlanning,null);assert.throws(()=>f.context.durableCommit(f.user,'opts',()=>({ok:true}),{fields:['users']}),/staged fields/);assert.throws(()=>f.context.durableCommit(f.user,'opts',()=>({ok:true}),{fields:['watch','watch']}),/staged fields/);assert.throws(()=>f.context.durableCommit(f.user,'nested',()=>f.context.durableCommit(f.user,'inner',()=>({ok:true}))),/Nested/);assert.equal(f.context._worldSettlementPlanning,null);f.context.PG_BOOT_PENDING=true;assert.equal(f.context.durableCommit(f.user,'boot',()=>{throw Error('must not run');}).storageFailed,true);f.context.PG_BOOT_PENDING=false;f.DB.idem.time={t:2000,resp:{ok:true}};assert.equal(f.context.durableCommit(f.user,'time',()=>({ok:true})).ok,false);});
test('Generic extra fields and PG failure keep one local commit; throwing writer does not mutate DB',()=>{const f=fixture();f.fail('pg');const out=f.context.durableCommit(f.user,'extra',(draft,staged)=>{staged.watch.u={x:1};return {ok:true};},{fields:['feedback','reports','watch']});assert.equal(out.ok,true);assert.equal(f.DB.watch.u.x,1);assert.equal(JSON.parse(f.disk).watch.u.x,1);const before=clone(f.DB);f.fail('rename');assert.throws(()=>f.context.saveDB({users:{}},'.tmp'),/rename/);assert.deepEqual(clone(f.DB),before);assert.throws(()=>f.context.saveDB({},'../escape'),/suffix/);});
