'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../server.js'),'utf8');
function span(a,b){const i=source.indexOf(a),j=source.indexOf(b,i);assert(i>=0&&j>i);return source.slice(i,j);}
const code=span('const DURABLE_USER_POLICIES=','function worldSettlementDurable(')+span('function _adoptUser(','const DURABLE_USER_POLICIES=')+span('function durableUserCommit(','function worldLocation(')+span('function worldMoveDurable(','function worldTravelState(');
function fixture(){const user={id:'own',value:1},other={id:'other',mail:[]},DB={users:{own:user,other},idem:{}};const writes=[],c={DB,PG_BOOT_PENDING:false,Date:{now:()=>1000},saveDB:(d,s)=>writes.push({db:JSON.parse(JSON.stringify(d)),suffix:s}),console:{error:()=>{}},pgSave:()=>{}};vm.createContext(c);vm.runInContext(code,c);return {c,user,other,writes};}
const proof=[];
{const f=fixture();f.c.DB.idem.k={t:1001,resp:{ok:true,value:8}};let called=false;assert.equal(f.c.worldMoveDurable(f.user,'k',()=>{called=true;} ).value,8);assert.equal(called,false);proof.push('worldMove replays future successful receipt (generic currently rejects backwards clock)');}
{const f=fixture();const r=f.c.worldMoveDurable(f.user,'',u=>{u.value=2;return {ok:1,value:2};});assert.equal(r.ok,1);assert.equal(f.user.value,2);assert.equal(f.writes.length,1);proof.push('worldMove accepts empty internal key and truthy ok1; preserve unless separately approved change');}
{const f=fixture();assert.throws(()=>f.c.durableUserCommit(f.user,{id:'own'},{},'wrong'),/Unknown durable user transaction/);assert.throws(()=>f.c.durableUserCommit(f.user,{id:'own'},{},'world-move',[{id:'other'}]),/Related accounts require world-war/);assert.throws(()=>f.c.durableUserCommit(f.user,{id:'own'},{},'quest-chain',[],{meta:{}}),/Invalid quest diagnostic fields/);f.c.PG_BOOT_PENDING=true;assert.equal(f.c.durableUserCommit(f.user,{id:'own'},{},'world-war').error,'World storage restore pending.');f.c.PG_BOOT_PENDING=false;f.c.saveDB=()=>{throw Error('rename');};assert.equal(f.c.durableUserCommit(f.user,{id:'own'},{},'world-war').error,'World save failed. Retry the same request.');assert.equal(f.user.value,1);proof.push('Exact tag/related/extra whitelist exceptions and boot/save reply strings captured');}
{const f=fixture();const receipts={k:{t:1000,resp:{ok:true}}};assert.equal(f.c.durableUserCommit(f.user,{id:'own',value:2},receipts,'world-city-settlement',[{id:'other',mail:[1]}],{watch:{own:[]},feedback:[1],reports:[2],meta:{rollSecret:'fixture'}}).ok,true);assert.equal(f.c.DB.users.own,f.user);assert.equal(f.c.DB.users.other,f.other);assert.equal(f.other.mail.length,1);assert.equal(f.c.DB.idem,receipts);assert.equal(f.writes[0].suffix,'.durable-commit.tmp');assert.equal(f.writes[0].db.meta.rollSecret,'fixture');proof.push('Prepared multi-account settlement/meta/diagnostics commits once and preserves live references/receipt object');}
console.log(JSON.stringify({base:'v939 2fe63a53b5ca75f00f5228f2b29f69004ddfee06',status:'Four baseline compatibility groups PASS; not a patch',proof},null,2));
