'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),net=require('node:net'),os=require('node:os');
const root=path.resolve(__dirname,'..'),cases=require('./durable-route-cases.cjs'),T=require(path.join(root,'server/temple-of-ash.js')),start=Date.parse('2026-10-02T04:00:00-04:00'),token='generic-fixture-token';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'emberweave-durable-route-')),file=path.join(dir,'db.json');
const user={id:'fixture-user',name:'Generic Fixture',created:start-1000,rank:1,coins:0,team:['vael'],wall:['vael'],roster:{},qc:{wish:0},led:{v:1,migratedAt:start-1000,rev:1,gold:100000,gems:100000,px:1000,hero:{vael:{xp:0,stars:1,pips:0,ref:0}},unlocked:{vael:true},frags:{},camp:{cleared:20,stars:{},att:null},stam:{v:60,ts:start},temple:T.newState(),txs:[],quests:{claimed:{},chainStep:0},pool:{goldUsedDay:'2026-10-02',goldFree:3,goldLast:start,gemFreeDay:'2026-10-02',gemFirstDone:true,pity:39,history:[]}}};
fs.writeFileSync(file,JSON.stringify({users:{[user.id]:user},byName:{'generic fixture':user.id},tokens:{[crypto.createHash('sha256').update(token).digest('hex')]:{id:user.id,iat:start,exp:start+90*86400000}},seeded:true,seedVersion:3,heroIdV:3,guilds:{},idem:{},feedback:[],reports:[],meta:{rollSecret:'generic-test'},watch:{[user.id]:{id:user.id,name:user.name,guildId:null,attacks:[{name:'Old target',eta:1,ret:false}],defends:[],scouts:[],t:start}}}));
fs.writeFileSync(path.join(dir,'clock.cjs'),"const fs=require('node:fs'),RealDate=Date,rename=fs.renameSync;let fail=false;global.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[Number(process.env.FIXTURE_NOW)]));}static now(){return Number(process.env.FIXTURE_NOW);}};Math.random=()=>0.5;fs.renameSync=function(a,b){if(fail&&b===process.env.DB_FILE)throw Error('generic fixture rename failure');return rename.apply(this,arguments);};process.on('message',m=>{fail=m.fail===true;process.send?.({fail});});");
let child,port,log='';const bytes=()=>fs.readFileSync(file,'utf8'),disk=()=>JSON.parse(bytes());
async function launch(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));port=s.address().port;await new Promise(r=>s.close(r));child=cp.spawn(process.execPath,['--require',path.join(dir,'clock.cjs'),path.join(root,'server.js')],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe','ipc'],env:{...process.env,DATABASE_URL:'',PORT:String(port),DB_FILE:file,FIXTURE_NOW:String(start),NODE_ENV:'test',GAME_URL:'http://127.0.0.1:1'}});child.stdout.on('data',x=>log+=x);child.stderr.on('data',x=>log+=x);for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error(log);try{await fetch('http://127.0.0.1:'+port+'/api/manifest');return;}catch{}await wait(50);}throw Error('readiness');}
async function stop(){if(child&&child.exitCode===null)await new Promise(r=>{child.once('exit',r);child.kill();});child=null;}
async function inject(fail){await new Promise((r,j)=>{const timer=setTimeout(()=>j(Error('fault timeout')),3000);child.once('message',()=>{clearTimeout(timer);r();});child.send({fail});});}
async function call(route,packet){const response=await fetch('http://127.0.0.1:'+port+route,{method:packet?'POST':'GET',headers:{'content-type':'application/json','x-token':token},body:packet?JSON.stringify(packet):undefined});return {status:response.status,body:await response.json()};}
return {launch,stop,inject,call,bytes,disk,log:()=>log};}
for(const row of cases)test('Actual HTTP durable route list: '+row.name,async()=>{const f=await fixture();try{
await f.launch();await f.call('/api/ledger');await f.call(row.observe);await wait(300);const beforeMemory=(await f.call(row.observe)).body;await wait(250);const before=f.bytes();await f.inject(true);
const failed=await f.call(row.route,row.packet),afterMemory=(await f.call(row.observe)).body;await wait(300);
console.log(JSON.stringify({route:row.route,failure:failed.status,diskUnchanged:f.bytes()===before,memoryUnchanged:JSON.stringify(afterMemory)===JSON.stringify(beforeMemory)}));
assert.equal(failed.status,503,'Failed rename must return503: '+row.route);assert.equal(f.bytes(),before,'No disk commit: '+row.route);assert.deepEqual(afterMemory,beforeMemory,'No memory publication: '+row.route);if(row.receipt)assert.equal(f.disk().idem[row.receipt],undefined);
await f.inject(false);const success=await f.call(row.route,row.packet);assert.equal(success.status,200);row.assertSaved(f.disk(),success.body,assert);if(row.receipt)assert.deepEqual(f.disk().idem[row.receipt].resp,success.body);const committed=f.bytes();const replay=await f.call(row.route,row.packet);assert.deepEqual(replay.body,success.body);assert.equal(f.bytes(),committed,'Same request commits once');await f.stop();await f.launch();assert.deepEqual((await f.call(row.route,row.packet)).body,success.body);assert.equal(f.bytes(),committed,'Restart retains original receipt/state');
}catch(e){console.error(f.log().slice(-1500));throw e;}finally{await f.stop();}});
