'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),net=require('node:net'),os=require('node:os');
const root=path.resolve(__dirname,'..'),cases=[],T=require(path.join(root,'server/temple-of-ash.js')),start=Date.parse('2026-10-02T04:00:00-04:00'),token='generic-fixture-token';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(legacy=true){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'emberweave-durable-route-')),file=path.join(dir,'db.json');
const user={id:'fixture-user',name:'Generic Fixture',created:start-1000,rank:1,coins:0,team:['vael'],wall:['vael'],roster:{},qc:{wish:0},led:{v:1,migratedAt:start-1000,rev:1,gold:100000,gems:100000,px:1000,hero:{vael:{xp:0,stars:1,pips:0,ref:0}},unlocked:{vael:true},frags:{},camp:{cleared:20,stars:{},att:null},stam:{v:60,ts:start},temple:T.newState(),txs:[],quests:{claimed:{},chainStep:0},pool:{goldUsedDay:'2026-10-02',goldFree:3,goldLast:start,gemFreeDay:'2026-10-02',gemFirstDone:true,pity:39,history:[]}}};
fs.writeFileSync(file,JSON.stringify({users:{[user.id]:user},byName:{'generic fixture':user.id},tokens:{[crypto.createHash('sha256').update(token).digest('hex')]:{id:user.id,iat:start,exp:start+90*86400000}},seeded:true,seedVersion:3,heroIdV:3,guilds:{},idem:{},feedback:[],reports:[],meta:{rollSecret:'generic-test'},watch:{[user.id]:{id:user.id,name:user.name,guildId:null,attacks:[{name:'Old target',eta:1,ret:false}],defends:[],scouts:[],t:start}}}));
fs.writeFileSync(path.join(dir,'clock.cjs'),"const fs=require('node:fs'),RealDate=Date,rename=fs.renameSync;let fail=false;global.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[Number(process.env.FIXTURE_NOW)]));}static now(){return Number(process.env.FIXTURE_NOW);}};Math.random=()=>0.5;fs.renameSync=function(a,b){if(fail&&b===process.env.DB_FILE)throw Error('generic fixture rename failure');return rename.apply(this,arguments);};process.on('message',m=>{fail=m.fail===true;process.send?.({fail});});");
let child,port,log='';const bytes=()=>fs.readFileSync(file,'utf8'),disk=()=>JSON.parse(bytes());
async function launch(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));port=s.address().port;await new Promise(r=>s.close(r));child=cp.spawn(process.execPath,['--require',path.join(dir,'clock.cjs'),path.join(root,'server.js')],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe','ipc'],env:{...process.env,DATABASE_URL:'',PORT:String(port),DB_FILE:file,FIXTURE_NOW:String(start),ALLOW_LEGACY_MINE_GRANTS:legacy?'1':'0',NODE_ENV:'test',GAME_URL:'http://127.0.0.1:1'}});child.stdout.on('data',x=>log+=x);child.stderr.on('data',x=>log+=x);for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error(log);try{await fetch('http://127.0.0.1:'+port+'/api/manifest');return;}catch{}await wait(50);}throw Error('readiness');}
async function stop(){if(child&&child.exitCode===null)await new Promise(r=>{child.once('exit',r);child.kill();});child=null;}
async function inject(fail){await new Promise((r,j)=>{const timer=setTimeout(()=>j(Error('fault timeout')),3000);child.once('message',()=>{clearTimeout(timer);r();});child.send({fail});});}
async function call(route,packet){const response=await fetch('http://127.0.0.1:'+port+route,{method:packet?'POST':'GET',headers:{'content-type':'application/json','x-token':token},body:packet?JSON.stringify(packet):undefined});return {status:response.status,body:await response.json()};}
return {launch,stop,inject,call,bytes,disk,log:()=>log};}

test('No daily mining limit: all four resources exceed 60; clamp/replay/restart retained',async()=>{const f=await fixture();try{await f.launch();await f.call('/api/ledger');for(const res of ['iron','crystal','silver','coal']){for(let i=0;i<6;i++){const packet={requestId:res+i,res,amount:999};const r=await f.call('/api/world/mine',packet);assert.equal(r.status,200,'61st unit must not be refused');assert.equal(r.body.granted,15);if(i>=4)assert.equal(r.body.capLeft,null);assert.deepEqual((await f.call('/api/world/mine',packet)).body,r.body);}assert.equal(f.disk().users['fixture-user'].led.acad.res[res],90);}const last={requestId:'coal5',res:'coal',amount:999},before=f.bytes();await f.stop();await f.launch();assert.equal((await f.call('/api/world/mine',last)).body.granted,15);assert.equal(f.bytes(),before);assert.equal((await f.call('/api/world/mine',{requestId:'floor',res:'iron',amount:2.9})).body.granted,2);assert.equal((await f.call('/api/world/mine',{requestId:'min',res:'iron',amount:0})).body.granted,1);assert.equal((await f.call('/api/world/mine',{requestId:'invalid',res:'gold',amount:15})).status,400);}finally{await f.stop();}});
test('Legacy mine grants remain disabled by default',async()=>{const f=await fixture(false);try{await f.launch();assert.equal((await f.call('/api/world/mine',{requestId:'retired',res:'iron',amount:15})).status,410);}finally{await f.stop();}});
test('Client mine info does not advertise an unauthorized daily farming limit',()=>{const html=fs.readFileSync(path.join(root,'emberweave-heroes.html'),'utf8');assert(!html.includes('per haul · 60/day cap'));assert(html.includes('per haul</span>'));});
