'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),net=require('node:net'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'emberweave-pool-durable-')),file=path.join(dir,'db.json'),start=Date.parse('2026-10-02T04:00:00-04:00');
const token='fixture-pool-token',foreignToken='fixture-foreign-token',hash=x=>crypto.createHash('sha256').update(x).digest('hex'),T=require(path.join(root,'server/temple-of-ash.js'));
const u={id:'pool-user',name:'Pool Fixture',created:start-1000,rank:1,coins:0,team:['vael'],wall:['vael'],roster:{},qc:{wish:0},led:{v:1,migratedAt:start-1000,rev:1,gold:100000,gems:100000,px:1000,hero:{vael:{xp:0,stars:1,pips:0,ref:0}},unlocked:{vael:true},frags:{},camp:{cleared:20,stars:{},att:null},stam:{v:60,ts:start},temple:T.newState(),txs:[],pool:{goldUsedDay:'2026-10-02',goldFree:3,goldLast:start,gemFreeDay:'2026-10-02',gemFirstDone:true,pity:39,history:[]}}};
const foreign=JSON.parse(JSON.stringify(u));foreign.id='foreign';foreign.name='Foreign';foreign.role='admin'; // own diagnostic observer only; actor stays non-admin
fs.writeFileSync(file,JSON.stringify({users:{[u.id]:u,[foreign.id]:foreign},byName:{'pool fixture':u.id,foreign:foreign.id},tokens:{[hash(token)]:{id:u.id,iat:start,exp:start+90*86400000},[hash(foreignToken)]:{id:foreign.id,iat:start,exp:start+90*86400000}},seeded:true,seedVersion:3,heroIdV:3,guilds:{},meta:{rollSecret:'pool-durable-fixture'},feedback:[],reports:[],idem:{}}));
fs.writeFileSync(path.join(dir,'clock.cjs'),"'use strict';const fs=require('node:fs'),RealDate=Date,rename=fs.renameSync,write=fs.writeFileSync;let clock=Number(process.env.FIXTURE_NOW),fail='';global.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[clock]));}static now(){return clock;}};Math.random=()=>0.5;fs.renameSync=function(a,b){if(fail==='rename'&&b===process.env.DB_FILE)throw Error('fixture rename failure');return rename.apply(this,arguments);};fs.writeFileSync=function(a){if(fail==='write'&&String(a).startsWith(process.env.DB_FILE+'.'))throw Error('fixture write failure');return write.apply(this,arguments);};process.on('message',m=>{clock=m.now;fail=m.fail||'';process.send?.({clock});});");
let child,port,log='',now=start;
fs.appendFileSync(path.join(dir,'clock.cjs'),"process.on('message',m=>{if(Number.isFinite(m.random))Math.random=()=>m.random;});");
async function launch(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));port=s.address().port;await new Promise(r=>s.close(r));child=cp.spawn(process.execPath,['--require',path.join(dir,'clock.cjs'),path.join(root,'server.js')],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe','ipc'],env:{...process.env,PORT:String(port),DB_FILE:file,DATABASE_URL:'',NODE_ENV:'test',FIXTURE_NOW:String(now),GAME_URL:'http://127.0.0.1:1'}});child.stdout.on('data',x=>log+=x);child.stderr.on('data',x=>log+=x);for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error(log);try{await fetch('http://127.0.0.1:'+port+'/api/manifest');return;}catch{}await new Promise(r=>setTimeout(r,50));}throw Error('readiness timeout');}
async function stop(){if(child&&child.exitCode===null)await new Promise(r=>{child.once('exit',r);child.kill();});child=null;}
async function fault(fail='',t=now,random=0.5){now=t;await new Promise((r,j)=>{const timer=setTimeout(()=>j(Error('fault timeout')),3000);child.once('message',()=>{clearTimeout(timer);r();});child.send({now,fail,random});});}
async function call(p,b,auth=token){const r=await fetch('http://127.0.0.1:'+port+p,{method:b?'POST':'GET',headers:{'content-type':'application/json',...(auth?{'x-token':auth}:{})},body:b?JSON.stringify(b):undefined});return {status:r.status,data:await r.json()};}
const disk=()=>JSON.parse(fs.readFileSync(file,'utf8'));
const relevant=d=>({user:d.users[u.id],foreign:d.users[foreign.id],idem:d.idem,feedback:d.feedback,reports:d.reports});
(async()=>{try{
await launch();await fault();assert.equal((await call('/api/pool/wish',{pool:'gem',requestId:'auth'},null)).status,401);
assert.equal((await call('/api/pool/wish',{pool:'gem'})).status,400);
// Warm ordinary read initializers and let their pre-existing saves finish before injection.
await call('/api/ledger');await call('/api/pool/state');await new Promise(r=>setTimeout(r,300));
const packet={pool:'gem',n:1,requestId:'paid-pity-rename',id:foreign.id,gems:0,results:[{type:'hero',hero:'konwu'}]};
const baseline=relevant(disk()),memory=(await call('/api/pool/state')).data;await new Promise(r=>setTimeout(r,250));
const before=fs.readFileSync(file,'utf8');await fault('rename');const failed=await call('/api/pool/wish',packet),after=(await call('/api/pool/state')).data;
await new Promise(r=>setTimeout(r,300));
console.log(JSON.stringify({failure:failed.status,ok:failed.data.ok,diskUnchanged:before===fs.readFileSync(file,'utf8'),memoryUnchanged:JSON.stringify(memory)===JSON.stringify(after)}));
assert.equal(failed.status,503,'Paid pity wish failed rename must not acknowledge200');assert.equal(failed.data.storageFailed,true);assert.equal(fs.readFileSync(file,'utf8'),before);assert.deepEqual(after,memory,'Failed wish must not expose spend/pity/reward in memory');assert.deepEqual(relevant(disk()),baseline);
await fault();const paid=await call('/api/pool/wish',packet);assert.equal(paid.status,200);assert.equal(paid.data.cost,300);assert.equal(paid.data.free,false);assert.equal(paid.data.results[0].pity,true);assert.equal(disk().users[u.id].qc.wish,1);assert.equal(disk().users[u.id].led.pool.history.length,1);assert.deepEqual(disk().users[foreign.id],baseline.foreign);
const committed=relevant(disk());assert.deepEqual((await call('/api/pool/wish',packet)).data,paid.data);assert.deepEqual(relevant(disk()),committed);
await stop();await launch();assert.deepEqual((await call('/api/pool/wish',packet)).data,paid.data);assert.deepEqual(relevant(disk()),committed);
const second={pool:'gold',n:10,requestId:'gold-ten-write'};await call('/api/pool/state');await new Promise(r=>setTimeout(r,250));const b2=fs.readFileSync(file,'utf8'),m2=(await call('/api/pool/state')).data;await new Promise(r=>setTimeout(r,250));await fault('write');assert.equal((await call('/api/pool/wish',second)).status,503);assert.deepEqual((await call('/api/pool/state')).data,m2);assert.equal(fs.readFileSync(file,'utf8'),b2);
await fault();const ten=await call('/api/pool/wish',second);assert.equal(ten.status,200);assert.equal(ten.data.cost,9000);assert.equal(ten.data.results.length,10);assert.equal(disk().users[u.id].qc.wish,11);assert.equal(disk().users[u.id].led.pool.history.length,2);
const invalid={pool:'unknown',requestId:'invalid'};assert.equal((await call('/api/pool/wish',invalid)).status,400);assert.equal(disk().idem[u.id+':wish:invalid'],undefined);
// Force the ordinary Diamond glyph branch, not just a guaranteed pity hero.
const glyph={pool:'gem',n:1,requestId:'ordinary-glyph'};await fault('rename');const gp=fs.readFileSync(file,'utf8'),gl=(await call('/api/ledger')).data;
assert.equal((await call('/api/pool/wish',glyph)).status,503);assert.deepEqual((await call('/api/ledger')).data,gl);assert.equal(fs.readFileSync(file,'utf8'),gp);
await fault();const g=await call('/api/pool/wish',glyph);assert.equal(g.status,200);assert.equal(g.data.results[0].type,'glyphFrag');assert.deepEqual((await call('/api/pool/wish',glyph)).data,g.data);
// Seed a legitimate prior gem gain so the forced currency roll crosses the existing
// detector threshold. The signal/report must commit with the reward, never leak on503.
await stop();const alarmSeed=disk();alarmSeed.users[u.id].gainLog=[{t:now,res:'gems',n:2000,r:'fixture-prior'}];alarmSeed.users[u.id].gainDay={k:'2026-10-02',gems:2000};alarmSeed.feedback=[];alarmSeed.reports=[];fs.writeFileSync(file,JSON.stringify(alarmSeed));await launch();await fault('',now,0.99);await call('/api/pool/state');await new Promise(r=>setTimeout(r,250));const alarmBefore=fs.readFileSync(file,'utf8'),alarmMemory=(await call('/api/ledger')).data;await new Promise(r=>setTimeout(r,250));await fault('rename',now,0.99);
const alarm={pool:'gem',n:1,requestId:'currency-detector'};assert.equal((await call('/api/pool/wish',alarm)).status,503);assert.deepEqual((await call('/api/ledger')).data,alarmMemory);assert.equal(fs.readFileSync(file,'utf8'),alarmBefore);
assert.equal((await call('/api/ember/feedback',null,foreignToken)).data.items.length,0,'Failed wish must not publish diagnostic feedback');
assert.equal((await call('/api/admin/reports',null,foreignToken)).data.reports.length,0,'Failed wish must not publish a detector report');
await fault('',now,0.99);const ar=await call('/api/pool/wish',alarm);assert.equal(ar.status,200);assert.equal(ar.data.results[0].type,'gems');assert.equal(disk().feedback.length,1);assert.equal(disk().reports.length,1);const alarmDone=relevant(disk());assert.deepEqual((await call('/api/pool/wish',alarm)).data,ar.data);assert.deepEqual(relevant(disk()),alarmDone);
await fault('',start+86400000);const free=await call('/api/pool/wish',{pool:'gold',n:1,requestId:'nextdayfree'});assert.equal(free.status,200);assert.equal(free.data.cost,0);assert.equal(free.data.free,true);assert.equal(disk().users[u.id].led.pool.goldFree,1);
console.log('PASS actual HTTP paid300 diamond+pity, gold9000 ten-roll, next-day free, rename/write503 nonpublication, successful receipt exact retry/restart, foreign/forged payload isolation, no invalid success receipt. No prices/rewards/odds changes.');
}finally{await stop();}})().catch(e=>{console.error(e);console.error(log.slice(-1800));process.exitCode=1;});
