'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../server.js'),'utf8').replace(/\r\n/g,'\n');
function fixture(){const begin=source.indexOf('function questChainDurable(user,rid){');assert(begin>=0,'Quest durable fix must exist');const end=source.indexOf('function durableUserCommit(',begin),stop=source.indexOf('function worldLocation(',end);assert(end>begin&&stop>end);
 const user={id:'own',led:{quests:{claimed:{},chainStep:0},camp:{cleared:6},frags:{},gems:0,txs:[]}},other={id:'other',led:{quests:{claimed:{},chainStep:0},camp:{cleared:6},frags:{},gems:0,txs:[]}};
 const ctx={DB:{users:{own:user,other},idem:{}},PG_BOOT_PENDING:false,_worldSettlementPlanning:null,Date:{now:()=>1000},console:{log(){},error(){}},DB_FILE:'fixture',fail:false,bytes:null,pgSave(){},ensureLedger:u=>u.led,
 questChainStepsSrv:()=>[{node:1,frags:2},{node:6,gems:20}],creditFrags(u,l,h,n){l.frags[h]=(l.frags[h]||0)+n;},creditGems(u,l,n){l.gems+=n;},ledTx(u,s,g){u.led.txs.push({s,g});},ledgerView:u=>JSON.parse(JSON.stringify(u.led)),_adoptUser(id,draft){Object.assign(ctx.DB.users[id],draft);},fs:{writeFileSync(p,bytes){ctx.pending=bytes;},renameSync(){if(ctx.fail)throw Error('fixture rename failure');ctx.bytes=ctx.pending;}}};
 vm.createContext(ctx);vm.runInContext(source.slice(begin,stop),ctx);return ctx;
}
test('Quest durable failed commit neither publishes actor nor receipt; retry/replay grants once',()=>{const c=fixture(),before=JSON.stringify(c.DB);c.fail=true;assert.equal(c.questChainDurable(c.DB.users.own,'retry').storageFailed,true);assert.equal(JSON.stringify(c.DB),before);assert.equal(c.bytes,null);assert.equal(c._worldSettlementPlanning,null);c.fail=false;const live=c.DB.users.own,r=c.questChainDurable(live,'retry');assert.equal(r.step,1);assert.equal(c.DB.users.own,live);assert.equal(live.led.frags.vex,2);assert.equal(JSON.parse(c.bytes).idem['own:qchain:retry'].resp.step,1);assert.equal(c.questChainDurable(live,'retry'),r);assert.equal(live.led.frags.vex,2);assert.equal(c.DB.users.other.led.quests.chainStep,0);});
test('Quest gates and corrupt steps fail closed without cached failure; pending restore refuses',()=>{const c=fixture(),u=c.DB.users.own;u.led.camp.cleared=0;assert.equal(c.questChainDurable(u,'gate').ok,false);assert.equal(c.DB.idem['own:qchain:gate'],undefined);u.led.camp.cleared=6;assert.equal(c.questChainDurable(u,'gate').step,1);u.led.quests.chainStep=-1;assert.equal(c.questChainDurable(u,'bad').ok,false);u.led.quests.chainStep=1;c.PG_BOOT_PENDING=true;assert.equal(c.questChainDurable(u,'gem').storageFailed,true);c.PG_BOOT_PENDING=false;assert.equal(c.questChainDurable(u,'gem').got.gems,20);assert.equal(u.led.gems,20);assert.equal(c.questChainDurable(u,'done').ok,false);});
test('Quest diagnostics are staged and saved with the receipt; backwards receipt clock does not double-grant',()=>{const c=fixture(),u=c.DB.users.own;c.DB.feedback=[];c.DB.reports=[];c.creditFrags=(a,l,h,n)=>{l.frags[h]=(l.frags[h]||0)+n;c._worldSettlementPlanning.db.feedback.push({kind:'fixture-alarm'});c._worldSettlementPlanning.db.reports.push({kind:'fixture-report'});};c.fail=true;assert.equal(c.questChainDurable(u,'alarms').storageFailed,true);assert.equal(c.DB.feedback.length,0);assert.equal(c.DB.reports.length,0);c.fail=false;assert.equal(c.questChainDurable(u,'alarms').ok,true);assert.equal(c.DB.feedback.length,1);assert.equal(c.DB.reports.length,1);assert.equal(JSON.parse(c.bytes).feedback.length,1);c.Date.now=()=>999;assert.equal(c.questChainDurable(u,'alarms').ok,false);assert.equal(u.led.frags.vex,2);assert.throws(()=>c.durableUserCommit(u,u,c.DB.idem,'quest-chain',[],{meta:{}}),/Invalid quest diagnostic fields/);});
