'use strict';const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),root=path.join(__dirname,'../shady-gold-v942/snapshot'),server=path.join(root,'server.js'),saved=fs.readFileSync(server),leader=path.join(root,'tests/guild-leadership.test.cjs');assert.equal(hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');assert(!fs.existsSync(leader));
async function run(){assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));let f;
try{fs.copyFileSync(path.join(__dirname,'../guild-leadership-v942/tests.cjs'),leader);fs.copyFileSync(path.join(__dirname,'../guild-raid-resolve-v942/payload/combined/server.js'),server);
const name=path.join(root,'tests/private-raid-client-integration.cjs'),m=new Module(name);m.filename=name;m.paths=Module._nodeModulePaths(path.dirname(name));m._compile(fs.readFileSync(path.join(__dirname,'../guild-raid-resolve-v942/tests.cjs'),'utf8').split("for(const kind of ['kill','no-kill','expired'])")[0]+'\nmodule.exports={setup};',name);({f}=await m.exports.setup('no-kill'));
const cm=new Module(__filename);cm.filename=__filename;cm.paths=Module._nodeModulePaths(__dirname);cm._compile(fs.readFileSync(path.join(__dirname,'tests.cjs'),'utf8').split("test('Double launch")[0]+'\nmodule.exports={fixture};',__filename);const client=cm.exports.fixture(),c=client.c;const html=fs.readFileSync(path.join(__dirname,'payload/combined/emberweave-heroes.html'),'utf8');c.ACC.id='fixture-user';c.ACC.token='generic-fixture-token';c.G.guild.id='own-guild';let dropStart=true,dropResolve=true;const packets=[];
c.fetch=async(route,options)=>{const packet=JSON.parse(options.body);packets.push({route,packet});const reply=await f.call(route,packet,options.headers['x-token']);if(route.endsWith('/start')&&dropStart){dropStart=false;throw Error('Actual committed entry reply lost');}if(route.endsWith('/resolve')&&dropResolve){dropResolve=false;throw Error('Actual committed settlement reply lost');}return{json:async()=>reply.body};};c.handleSignedOutElsewhere=()=>{throw Error('unexpected auth')};const a=html.indexOf('async function api('),z=html.indexOf('let _kickedNotified=',a);vm.runInContext(html.slice(a,z),c);
await c.raidLaunch();assert.equal(client.effects.battles,0);const charged=f.disk().users['fixture-user'].raidDay.n;await c.raidLaunch();assert.equal(client.effects.battles,1);assert.equal(f.disk().users['fixture-user'].raidDay.n,charged);assert.deepEqual(packets[0].packet,packets[1].packet);
c.finishRaid();await Promise.all(client.effects.results);assert.equal(client.els.resultTitle.textContent,'RESULT UNCONFIRMED');const committed=f.bytes(),txs=f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length;assert.equal(txs,1);c.raidResolveRetry();await Promise.all(client.effects.results);assert.notEqual(client.els.resultTitle.textContent,'RESULT UNCONFIRMED');assert.equal(client.effects.adopt.length,1);assert.equal(f.bytes(),committed);assert.deepEqual(packets[2].packet,packets[3].packet);assert.equal(f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,1);
await f.stop();await f.launch();assert.equal((await f.call('/api/guild/raid/resolve',packets[3].packet)).body.ok,true);assert.equal(f.bytes(),committed);fs.writeFileSync(path.join(__dirname,'integration-results.json'),JSON.stringify({at:new Date().toISOString(),pass:true,chargedEntryCount:charged,raidTransactions:txs,packets,scope:'Extracted actual client launch/settlement + actual api + private HTTP/frozen-squad replay, synthetic render stubs, dropped committed replies. NOT physical UI, reload recovery, full canonical bot/Brain or deployment.'},null,2));console.log('PASS actual client/api/privateHTTP lost entry and settlement reply recovery, restart; no duplicate charge/grant');
}finally{if(f)await f.stop();fs.writeFileSync(server,saved);fs.unlinkSync(leader);assert.equal(hash(fs.readFileSync(server)),hash(saved));}}
run().catch(e=>{console.error(e);process.exitCode=1;});
