'use strict';const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const local=path.join(__dirname,'payload/combined/emberweave-heroes.html'),html=fs.readFileSync(process.env.RAID_CLIENT_HTML||(fs.existsSync(local)?local:path.resolve(__dirname,'../emberweave-heroes.html')),'utf8');
function fixture(){const effects={packets:[],banners:[],adopt:[],battles:0,shows:[],results:[]},waiting=[],els={};let seq=0;
const c={G:{guild:{id:'guild'}},ACC:{id:'actor',token:'token'},CUR:{mode:'graid',attemptId:'attempt',raid:{name:'Boss',tier:1}},TEAM_SIZE:5,INPUT_LOG:[{t:1}],units:[{team:'enemy',_raidBoss:true,alive:false}],gameSpeed:1,squadFor:()=>['vael'],uid8:()=>String(++seq),bannerMsg:x=>effects.banners.push(x),api:(...args)=>{effects.packets.push(JSON.parse(JSON.stringify(args)));return new Promise((resolve,reject)=>waiting.push({resolve,reject}));},startBattle:()=>effects.battles++,raidDamageDone:()=>1234,resultLater:fn=>effects.results.push(fn(1)),resultStale:()=>false,adoptLedger:x=>effects.adopt.push(x),setResultVerdict:()=>{},escapeHTML:x=>String(x),document:{getElementById:id=>els[id]||(els[id]={textContent:'',innerHTML:'',className:''})},updateHubChrome:()=>{},show:x=>effects.shows.push(x)};
vm.createContext(c);const a=html.indexOf('let RAID_START_PENDING='),b=html.indexOf('function raidDamageDone()',a);if(a>=0)vm.runInContext(html.slice(a,b),c);else{const x=html.indexOf('async function raidLaunch(){'),y=html.indexOf('function raidDamageDone()',x);vm.runInContext(html.slice(x,y),c);}
const x=html.indexOf("  if(CUR.mode==='graid' && CUR.attemptId){"),y=html.indexOf("  if(CUR.mode==='well')",x);vm.runInContext('function finishRaid(){'+html.slice(x,y)+'}',c);
return{c,effects,els,reply:r=>waiting.shift().resolve(r),reject:()=>waiting.shift().reject(Error('lost reply')),flush:()=>new Promise(r=>setImmediate(r))};}
test('Double launch is singleflight and lost response retries exact stable intent',async()=>{const f=fixture();const first=f.c.raidLaunch();const second=f.c.raidLaunch();assert.equal(f.effects.packets.length,1);f.reject();await first;await second;await f.flush();const next=f.c.raidLaunch();assert.deepEqual(f.effects.packets[1][2],f.effects.packets[0][2]);f.reply({attemptId:'saved-attempt',boss:{key:'boss',hp:1},seed:3,snaps:[]});await next;assert.equal(f.effects.battles,1);assert.equal(f.c.CUR.attemptId,'saved-attempt');});
for(const[label,change]of [['account',c=>c.ACC={id:'other',token:'other'}],['id',c=>c.ACC.id='other'],['token',c=>c.ACC.token='other'],['game',c=>c.G={guild:{id:'other'}}]])test('Launch '+label+' switch ignores delayed start',async()=>{const f=fixture();const p=f.c.raidLaunch();change(f.c);f.reply({attemptId:'old',boss:{key:'boss',hp:1}});await p;assert.equal(f.effects.battles,0);assert.equal(f.c.CUR.attemptId,'attempt');});
test('Lost settlement keeps bound packet; retry click singleflight then confirms server award without local grant',async()=>{const f=fixture();f.c.finishRaid();f.reject();await f.flush();assert.equal(f.els.resultTitle.textContent,'RESULT UNCONFIRMED');assert.match(f.els.resultReward.innerHTML,/Retry same result/);f.c.raidResolveRetry();f.c.raidResolveRetry();assert.equal(f.effects.packets.length,2);assert.deepEqual(f.effects.packets[1][2],f.effects.packets[0][2]);f.reply({ok:true,dmg:100,killed:true,reward:{gold:800,gems:18,guildCoins:300,tier:1},ledger:{gold:100800}});await f.flush();assert.equal(f.els.resultTitle.textContent,'BOSS FELLED');assert.equal(f.effects.adopt.length,1);f.c.raidResolveRetry();assert.equal(f.effects.packets.length,2);});
for(const[label,change]of [['account',c=>c.ACC={id:'other',token:'other'}],['id',c=>c.ACC.id='other'],['token',c=>c.ACC.token='other'],['guild',c=>c.G.guild.id='other']])test('Settlement '+label+' switch prevents adoption and result UI',async()=>{const f=fixture();f.c.finishRaid();change(f.c);f.reply({ok:true,dmg:100,ledger:{gold:900000}});await f.flush();assert.equal(f.effects.adopt.length,0);assert.equal(f.effects.shows.length,0);assert.equal(f.els.resultTitle,undefined);});
test('Expired settlement is explicit and clears retry;409 stays unconfirmed and never starts new raid',async()=>{for(const reply of [{ok:false,expired:true,error:'expired'},{ok:false,error:'Raid receipt does not match'}]){const f=fixture();f.c.finishRaid();f.reply(reply);await f.flush();assert.equal(f.els.resultTitle.textContent,reply.expired?'RAID EXPIRED':'RESULT UNCONFIRMED');assert.equal(f.effects.battles,0);assert.equal(f.effects.adopt.length,0);if(reply.expired){f.c.raidResolveRetry();assert.equal(f.effects.packets.length,1);}else{await f.c.raidLaunch();assert.equal(f.effects.packets.length,1);assert.match(f.effects.banners[0],/pending raid result/);}}});
test('Changed result epoch refuses stale ledger adoption as well as UI',async()=>{const f=fixture();f.c.resultStale=()=>true;f.c.finishRaid();f.reply({ok:true,dmg:123,ledger:{gold:900000}});await f.flush();assert.equal(f.effects.adopt.length,0);assert.equal(f.effects.shows.length,0);});
test('Lost launch cannot retry at ten-minute boundary or backward client clock',async()=>{for(const offset of [600000,-1]){const f=fixture();let now=1000000;f.c.Date={now:()=>now};const first=f.c.raidLaunch();f.reject();await first;now+=offset;await f.c.raidLaunch();assert.equal(f.effects.packets.length,1);assert.match(f.effects.banners.at(-1),/window closed/);}});
test('Incomplete launch reply is not a playable fight and keeps original intent',async()=>{const f=fixture();const p=f.c.raidLaunch();f.reply({});await p;assert.equal(f.effects.battles,0);const next=f.c.raidLaunch();assert.deepEqual(f.effects.packets[1][2],f.effects.packets[0][2]);f.reply({none:true});await next;assert.equal(f.effects.battles,0);});
