'use strict';
const fs=require('node:fs'),path=require('node:path'),a=require('node:assert/strict'),crypto=require('node:crypto'),{planCase}=require('./case-outbox-model.cjs'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');a(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
const flag=(accountId,i,stage='guild-raid:wintercrag:tier:1')=>({v:1,kind:'raid-damage-mismatch',playerTruth:true,accountId,stage,attemptId:'attempt-'+i,packetHash:hash('packet-'+i),playerDamage:12345,replayDamage:4,t:1790928000000+i,engine:'synthetic'}),actor=n=>({id:'owner',raidMismatchFlags:Array.from({length:n},(_,i)=>flag('owner',i))});const checks=[];
for(const n of [0,1,2]){a.equal(planCase(actor(n),{}).caseDraft,null);checks.push('No case before three flags: '+n);}
const users={a:{id:'other-a',raidMismatchFlags:[flag('other-a',0),flag('other-a',1)]},b:{id:'other-b',raidMismatchFlags:[flag('other-b',0,'different-stage')]},owner:actor(3),unknown:{id:'unknown',raidMismatchFlags:[{stage:'guild-raid:wintercrag:tier:1'}]}};
const three=actor(3),before=JSON.stringify({three,users}),draft=planCase(three,users);a.equal(draft.caseDraft.triggerFlag,3);a.equal(draft.caseDraft.otherPlayersSameStage,1);a.equal(draft.caseDraft.specialistDispatch,false);a.equal(JSON.stringify({three,users}),before);a.deepEqual(planCase(three,users),draft);checks.push('Three flags draft stable case; distinct other players counted once, unknown history excluded, no mutation');
const four=planCase(actor(4),users);a.equal(four.caseDraft.id,draft.caseDraft.id);a.equal(four.caseDraft.status,'pending-review');a.equal(four.caseDraft.specialistDispatch,false);a.equal(four.caseDraft.laterFlags.length,1);checks.push('Fourth retains same pending case and later flag, does not fabricate review or dispatch');
const bad=actor(3);bad.raidMismatchFlags[0]={unknown:true};a.equal(planCase(bad,users).held,true);const duplicate=actor(3);duplicate.raidMismatchFlags[2]=duplicate.raidMismatchFlags[0];a.equal(planCase(duplicate,users).held,true);a.equal(planCase({id:'owner',raidMismatchFlags:{}},users).held,true);checks.push('Malformed/nonarray/duplicate histories held unchanged, never discarded');
const evidence={atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),modelSHA256:hash(fs.readFileSync(path.join(__dirname,'case-outbox-model.cjs'))),helperSHA256:hash(fs.readFileSync(__filename)),checks,limits:'Executable isolated design/model only; not server integrated, not actual HTTP/Ember delivery or review/specialist proof. No source game/Brain edits, no policy authorization/deployment claim.'};fs.writeFileSync(path.join(__dirname,'case-outbox-model-certificate.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence));
