'use strict';const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict'),P=require('./patch.cjs'),root=path.join(__dirname,'../shady-gold-v942/snapshot'),file=path.join(root,'server.js'),saved=fs.readFileSync(file),files=['guild-leadership.test.cjs','private-self-raid.cjs'];assert.equal(P.hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');assert(!fs.existsSync(path.join(root,'tests',files[0])));
async function run(){assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));const passed=[];
try{fs.copyFileSync(path.join(__dirname,'../guild-leadership-v942/tests.cjs'),path.join(root,'tests',files[0]));fs.copyFileSync(path.join(__dirname,'payload/combined/server.js'),file);const name=path.join(root,'tests',files[1]),m=new Module(name);m.filename=name;m.paths=Module._nodeModulePaths(path.dirname(name));m._compile(fs.readFileSync(path.join(__dirname,'tests.cjs'),'utf8').split("for(const kind of ['kill','no-kill','expired'])")[0]+'\nmodule.exports={setup,packet};',name);
const {setup,packet}=m.exports;
{const{f}=await setup('no-kill');try{const entered=await f.call('/api/guild/raid/start',{requestId:'actual-replay',heroIds:['vael']});assert.equal(entered.status,200);assert(entered.body.snaps.length);const p={...packet,attemptId:entered.body.attemptId,inputLog:[],dmg:999999};const before=f.bytes();await f.inject(true);assert.equal((await f.call('/api/guild/raid/resolve',p)).status,503);assert.equal(f.bytes(),before);await f.inject(false);const out=await f.call('/api/guild/raid/resolve',p);assert.equal(out.status,200);assert.equal(out.body.incident,null,'Actual replay, not fallback claim');assert(out.body.dmg<999999);const d=f.disk();assert.equal(d.guilds['own-guild'].raid.att['fixture-user'],undefined);assert.equal(d.users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,1);const committed=f.bytes();const retry=await f.call('/api/guild/raid/resolve',{...p,requestId:'new-key-after-consumed'});assert.equal(retry.body.ok,false);assert.equal(f.bytes(),committed);await f.stop();await f.launch();assert.deepEqual((await f.call('/api/guild/raid/resolve',p)).body,out.body);passed.push('One real frozen-squad replay fault/retry/restart; forged fallback claim unused; consumed attempt cannot pay with fresh request key. NOT full canonical run.');}finally{await f.stop();}}
{const{f}=await setup('kill');try{const first=await f.call('/api/guild/raid/resolve',packet);const before=f.bytes();const altered=await f.call('/api/guild/raid/resolve',{...packet,dmg:999999,inputLog:[{anything:'different'}]});assert.deepEqual(altered.body,first.body);assert.equal(f.bytes(),before);passed.push('Same attempt/request retry keeps committed result despite altered damage/transcript, with no second award.');}finally{await f.stop();}}
fs.writeFileSync(path.join(__dirname,'self-review-results.json'),JSON.stringify({at:new Date().toISOString(),passed,limitations:['Synthetic private HTTP/tempDB only; one real engine operation not full canonical bot/Brain.','Legacy unbound receipts deliberately409; not backward-compatible PASS. Phil must approve deployment transition.','Pruning by other routes remains; unknown consumed attempt refuses rather than grant.','No client UI/session/reset/multi-instance/PG/fsync/phone or production claim.']},null,2));console.log('PASS '+passed.length+' supplemental boundaries');
}finally{fs.writeFileSync(file,saved);fs.unlinkSync(path.join(root,'tests',files[0]));assert.equal(P.hash(fs.readFileSync(file)),P.hash(saved));}}
run().catch(e=>{console.error(e);process.exitCode=1;});
