'use strict';const fs=require('node:fs'),vm=require('node:vm'),a=require('node:assert/strict'),crypto=require('node:crypto');const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),copy=x=>JSON.parse(JSON.stringify(x));
const control=process.env.STAGE_CONTROL==='1',html=fs.readFileSync(__dirname+(control?'/../guild-raid-canonical-namespace-v948/private-client-namespaced.html':'/private-client-locked-stage.html'),'utf8');a.equal(hash(html),control?'ea8540e8afc23e8d541d104bb92b7e750c99555341ca224f8f1defa8a7a2d20e':'6559a3d50837800f46a5593c874895f666b472492ac57fff46d2725d3df14d7f');const b=html.indexOf('const EW_RAID_V3_MODULES='),e=html.indexOf('// PRIVATE guarded v3 cutover.',b),M=vm.runInNewContext(html.slice(b,e)+'\nEW_RAID_V3_MODULES;'),results=[];
const E={requestId:'r3:2026-10-02:stage',heroIds:['vael']},P={requestId:'result-stage',attemptId:'attempt-stage',inputLog:[],dmg:1};
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(err){results.push({name,status:'FAIL',error:err.message});}}
async function site(){const rows=new Map(),slots=new Map();let held=false,network=0,current=true;const directory={async list(){return copy([...rows.values()])},async insertBounded(r){M.directory.row(r);rows.set(r.id,copy(r))}};
const storage={get length(){return slots.size},key:i=>[...slots.keys()][i],getItem:k=>slots.get(k)||null,setItem:(k,v)=>slots.set(k,v)};
const ctx=()=>({accountId:'A',guildId:'G',token:current?'token':'changed',epoch:1});const f=M.facade.create({directory,storage,context:ctx,locks:{async request(n,o,fn){return fn(held?null:{name:n})}},transport:async()=>{network++;return {status:200,body:{ok:true,attemptId:P.attemptId}}},legacyWritersQuiescent:async()=>true,validateFreshEntryReply:async({entry,scope})=>({...scope,entryRequestId:entry.requestId,entry:copy(entry),attemptId:P.attemptId})});const accepted=await f.start(E,'instance');return{f,accepted,rows,slots,setHeld:x=>held=x,change:()=>current=false,network:()=>network};}
(async()=>{
await test('stage refuses held account lock before any slot write/network',async()=>{const s=await site();s.setHeld(true);await a.rejects(Promise.resolve().then(()=>s.f.stage(s.accepted.row,P)),/Busy recovery/);a.equal(s.slots.size,0);a.equal(s.network(),1);});
await test('stale writer cannot stage after its directory row is retired',async()=>{const s=await site();s.rows.clear();await a.rejects(Promise.resolve().then(()=>s.f.stage(s.accepted.row,P)),/Stage directory changed/);a.equal(s.slots.size,0);});
await test('successful guarded stage saves exact packet with no result network',async()=>{const s=await site();await s.f.stage(s.accepted.row,P);a.equal(s.slots.size,1);a.deepEqual(JSON.parse([...s.slots.values()][0]).packet,P);a.equal(s.network(),1);});
for(const fail of [false,true])await test('bootstrap '+(fail?'stage failure retains fight/no schedule':'awaits successful stage before scheduling'),async()=>{let release,schedule=0;const row={id:'instance',entry:E};const f={current:()=>true,start:async()=>({row,reply:{status:200,body:{ok:true,attemptId:P.attemptId}}}),resume(){},discover:async()=>[],stage:()=>new Promise((r,j)=>{release=fail?()=>j(Error('Injected stage quota')):()=>r({stored:true})})};const boot=M.bootstrap.create({facade:f,current:()=>true,onFight(){},scheduleSettlement(){schedule++}});await boot.launch(E,'instance');const pending=Promise.resolve().then(()=>boot.stageAndSchedule(P));await Promise.resolve();a.equal(schedule,0,'must not schedule before stage settles');a.equal(boot.owned().phase,'fight');const second=Promise.resolve().then(()=>boot.stageAndSchedule(P));await a.rejects(second,/No accepted fight owner/);release();if(fail){await a.rejects(pending,/Injected stage quota/);a.equal(boot.owned().phase,'fight');a.equal(schedule,0);}else{await pending;a.equal(boot.owned().phase,'result');a.equal(schedule,1);}});
fs.writeFileSync(__dirname+(control?'/original-controls.json':'/certificate.json'),JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),clientSHA256:hash(html),results,scope:'Actual embedded facade/bootstrap in VM with modeled directory/storage/locks and injected asynchronous stage. Not native locks/IDB/DOM/actualHTTP or complete closure integration.'},null,2));console.log(JSON.stringify(results,null,2));if(!control&&results.some(x=>x.status!=='PASS'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
