'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),a=require('node:assert/strict'),{verify}=require('./verify.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'payload');a(!fs.existsSync(out),'Refuse existing package, preserve evidence');fs.mkdirSync(out);
const inputs=[['guild-raid-entry-closed-directory-v948/private-client-entry-closure.html','private-client-entry-closure.html'],['guild-raid-period-closure-v948/private-server-period-closure.js','private-server-period-closure.js'],...['integrated-certificate.json','closure-http-certificate.json','html-bootstrap-certificate.json','legacy-boundary-certificate.json','facade-certificate.json','hybrid-certificate.json'].map(f=>['guild-raid-entry-closed-directory-v948/'+f,f])];
const files=inputs.map(([p,name])=>{const bytes=fs.readFileSync(path.join(root,p));fs.copyFileSync(path.join(root,p),path.join(out,name));return {name,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};});
const manifest={kind:'private-review-evidence',atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),baseCommit:'bbbc3a662a4f106153abafafec691cc6d70149a0',baseStatus:'Historical exact source base; live baseline has NOT been independently reverified for deployment.',deployApproved:false,installable:false,totalBytes:files.reduce((n,f)=>n+f.bytes,0),files,scope:'Self-contained bounded exact source-pair/evidence inspection, not whole game clone or deployment package. No installer or live targets. Source server dependencies/assets remain outside; do not run this payload as a full game.',open:['Native IDB/WebLocks/current UI/physical phone','Real legacy-writers quiescence provider and compatibility','Quota/terminal-marker retention policy','Current integration/fullsuite and canonical bots','Guild authored fight rule/contribution balance/Q5/Q6/Q9','Official hourly Markdown/checklist/blueprints and archive reconciliation','Same exact integrated artifact explicit dual approval plus backup/rollback/deploy verification']};
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2));fs.copyFileSync(__dirname+'/verify.cjs',out+'/verify.cjs');
const result=verify(out,manifest),controls=[];for(const [name,change]of [['source-hash mismatch',m=>m.files[0].sha256='0'.repeat(64)],['approval flag contamination',m=>m.deployApproved=true]]){const m=structuredClone(manifest);change(m);a.throws(()=>verify(out,m));controls.push({name,status:'EXPECTED_REFUSAL'});}
const cert={atET:manifest.atET,result,controls,manifestSHA256:crypto.createHash('sha256').update(fs.readFileSync(out+'/manifest.json')).digest('hex'),scope:'Package bytes/parse and rejection checks only. No completed gameplay suite rerun; no native/balance/release assertion.'};fs.writeFileSync(__dirname+'/package-certificate.json',JSON.stringify(cert,null,2));console.log(JSON.stringify(cert,null,2));
