'use strict';const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),a=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.join(__dirname,'../shady-gold-v942/snapshot'),server=path.join(root,'server.js'),saved=fs.readFileSync(server),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
a.equal(hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');a(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
const original=process.env.RETAIN_CONTROL==='1',candidate=path.join(__dirname,original?'../guild-raid-strict-start-v948/private-server-strict-start.js':'private-server-retained-attempt.js');let f;const calls=[];let failure=null;
async function main(){try{
 fs.copyFileSync(candidate,server);const file=path.join(root,'tests/private-retained-raid.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));
 m._compile(fs.readFileSync(path.join(__dirname,'../guild-raid-recovery-only-v942/tests.cjs'),'utf8').split('const E=')[0].replace('root=process.env.GUILD_FIXTURE_ROOT','root='+JSON.stringify(root)).replace("path.join(root,'tests/guild-leadership.test.cjs')",JSON.stringify(path.join(__dirname,'../guild-leadership-v942/tests.cjs')))+'\nmodule.exports={setup};',file);({f}=await m.exports.setup());
 const call=async(route,p)=>{const r=await f.call(route,p);calls.push({route,packet:p,status:r.status,body:r.body});return r};
 const E={requestId:'retained-first',heroIds:['vael']},first=await call('/api/guild/raid/start',E),second=await call('/api/guild/raid/start',{...E,requestId:'retained-second'});a.equal(first.body.ok,true);a.equal(second.body.ok,true);a.notEqual(first.body.attemptId,second.body.attemptId);a.equal(f.disk().users['fixture-user'].raidDay.n,2);
 await f.stop();await f.launch();const before=f.bytes(),old=await call('/api/guild/raid/start',{...E,recoverOnly:true});a.equal(old.status,200,'overwritten paid snapshot must remain recoverable');for(const k of ['attemptId','seed','snaps','boss','engine'])a.deepEqual(old.body[k],first.body[k]);a.equal(f.bytes(),before);
 const P={requestId:'retained-result-one',attemptId:first.body.attemptId,inputLog:[],dmg:10};await f.inject(true);const fault=await call('/api/guild/raid/resolve',P);a.equal(fault.status,503);a.equal(f.bytes(),before);await f.inject(false);
 a.equal((await call('/api/guild/raid/resolve',P)).body.ok,true);a.equal(f.disk().guilds['own-guild'].raid.att['fixture-user'].id,second.body.attemptId);a.equal(f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,1);
 await f.stop();await f.launch();a.equal((await call('/api/guild/raid/resolve',P)).body.ok,true);a.equal(f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,1);
 const paid=f.bytes(),duplicate=await call('/api/guild/raid/resolve',{...P,requestId:'retained-new-result-id'});a.equal(duplicate.body.ok,false);a.equal(f.bytes(),paid);
 const next=await call('/api/guild/raid/start',{...E,requestId:'retained-second',recoverOnly:true});a.equal(next.body.attemptId,second.body.attemptId);
 a.equal((await call('/api/guild/raid/resolve',{...P,requestId:'retained-result-two',attemptId:second.body.attemptId})).body.ok,true);a.equal(f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,2);a.equal(f.disk().users['fixture-user'].raidDay.n,2);
 console.log('PASS realHTTP: two allowed paid entries, firstsnapshot recovery/restart/fault, oldsettlement preserves newslot, exactreceipt once and attempt-level replay refused, secondsettlement once');
 }catch(e){failure={name:e.name,message:e.message};throw e}finally{if(f)await f.stop();fs.writeFileSync(server,saved);a.equal(hash(fs.readFileSync(server)),hash(saved));fs.writeFileSync(path.join(__dirname,original?'original-control.json':'http-certificate.json'),JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),status:failure?'FAILED_EXPECTED_IF_ORIGINAL':'PASS_PRIVATE_REAL_HTTP_COMPONENT',serverSHA256:hash(fs.readFileSync(candidate)),calls,failure,fixtureRestored:true,scope:'Actual owned private HTTP synthetic account; no native/fullsuite/balance or deployment approval.'},null,2));console.log('Owned fixture child stopped/restored')}}main().catch(e=>{console.error(e);process.exitCode=1});
