'use strict';
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),root=path.join(__dirname,'../shady-gold-v942/snapshot'),server=path.join(root,'server.js'),saved=fs.readFileSync(server),leader=path.join(root,'tests/guild-leadership.test.cjs');
assert.equal(hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');assert(!fs.existsSync(leader));
async function run(){assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));let f,copied=false;
try{
fs.copyFileSync(path.join(__dirname,'../guild-leadership-v942/tests.cjs'),leader);copied=true;fs.copyFileSync(path.join(__dirname,'../guild-raid-resolve-v942/payload/combined/server.js'),server);
const name=path.join(root,'tests/private-journal-integration.cjs'),m=new Module(name);m.filename=name;m.paths=Module._nodeModulePaths(path.dirname(name));m._compile(fs.readFileSync(path.join(__dirname,'../guild-raid-resolve-v942/tests.cjs'),'utf8').split("for(const kind of ['kill','no-kill','expired'])")[0]+'\nmodule.exports={setup};',name);({f}=await m.exports.setup('no-kill'));
const htmlPath=path.join(__dirname,'payload/combined/emberweave-heroes.html'),html=fs.readFileSync(htmlPath,'utf8');process.env.RAID_CLIENT_HTML=htmlPath;
const cm=new Module(__filename);cm.filename=__filename;cm.paths=Module._nodeModulePaths(__dirname);cm._compile(fs.readFileSync(path.join(__dirname,'tests.cjs'),'utf8').split("const key='ew_raid_pending_v1_actor';")[0]+'\nmodule.exports={setup};',__filename);
const shared=new Map(),packets=[];let dropStart=true,dropResolve=true;
function fresh(){const client=cm.exports.setup(shared),c=client.c;c.ACC.id='fixture-user';c.ACC.token='generic-fixture-token';c.G.guild.id='own-guild';
c.fetch=async(route,options)=>{const packet=JSON.parse(options.body);packets.push({route,packet});const reply=await f.call(route,packet,options.headers['x-token']);if(route.endsWith('/start')&&dropStart){dropStart=false;throw Error('Committed entry reply lost');}if(route.endsWith('/resolve')&&dropResolve){dropResolve=false;throw Error('Committed settlement reply lost');}return{json:async()=>reply.body};};
c.handleSignedOutElsewhere=()=>{throw Error('Unexpected auth')};const a=html.indexOf('async function api('),z=html.indexOf('let _kickedNotified=',a);assert(a>0&&z>a);vm.runInContext(html.slice(a,z),c);return client;}
const first=fresh();await first.c.raidLaunch();assert.equal(first.effects.battles,0);const charged=f.disk().users['fixture-user'].raidDay.n;assert.equal(shared.size,1);
await f.stop();await f.launch();const second=fresh();assert.equal(packets.length,1,'Reload does not send automatically');await second.c.raidLaunch();assert.equal(second.effects.battles,1);assert.equal(f.disk().users['fixture-user'].raidDay.n,charged);assert.deepEqual(packets[0].packet,packets[1].packet);
second.c.finishRaid();await Promise.all(second.effects.results);assert.equal(second.els.resultTitle.textContent,'RESULT UNCONFIRMED');const committed=f.bytes(),txs=f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length;assert.equal(txs,1);assert.equal(shared.size,1);
await f.stop();await f.launch();const third=fresh();assert.equal(packets.length,3,'Settlement reload also remains manual');third.c.INPUT_LOG=[];third.c.raidDamageDone=()=>999999;third.c.raidRecoverSaved();third.c.raidRecoverSaved();await Promise.all(third.effects.results);assert.equal(packets.length,4,'Double recovery click is singleflight');assert.deepEqual(packets[2].packet,packets[3].packet);assert.equal(third.effects.adopt.length,1);assert.equal(f.bytes(),committed);assert.equal(shared.size,0);assert.equal(f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,1);
fs.writeFileSync(path.join(__dirname,'integration-results.json'),JSON.stringify({at:new Date().toISOString(),pass:true,htmlSHA256:hash(html),chargedEntryCount:charged,raidTransactions:txs,packets,scope:'Fresh VM per reload with shared account journal, extracted actual API and handlers, private HTTP/frozen-squad replay; dropped committed replies then server restart before each manual recovery. Double click singleflight. Synthetic rendering/timers/storage, NOT actual browser/phone/full canonical bot/Brain/deployment.'},null,2));console.log('PASS freshVM journal + actualAPI/privateHTTP entry and result reload/restart; one charge/raidtx, double-click singleflight');
}finally{if(f)await f.stop();fs.writeFileSync(server,saved);if(copied)fs.unlinkSync(leader);assert.equal(hash(fs.readFileSync(server)),hash(saved));}}
run().catch(e=>{console.error(e);process.exitCode=1;});
