'use strict';const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
const plan=JSON.parse(fs.readFileSync(path.join(__dirname,'spans.json'))),prior=path.join(__dirname,'../guild-raid-client-v942/payload/combined'),html=fs.readFileSync(path.join(__dirname,'payload/combined/emberweave-heroes.html'),'utf8');assert.equal(hash(html),plan.output);
const runner=fs.readFileSync(path.join(prior,'tests/run_all_tests.sh'),'utf8'),ro='node --test tests/guild-raid-client.test.cjs || FAILED=1',rn=ro+'\nnode --test tests/guild-raid-journal.test.cjs || FAILED=1';assert.equal(runner.split(ro).length,2);
const old=fs.readFileSync(path.join(prior,'tests/guild-raid-client.test.cjs'),'utf8'),anchor='vm.createContext(c);',insert="const journalStore=new Map();c.localStorage={getItem:k=>journalStore.has(k)?journalStore.get(k):null,setItem:(k,v)=>journalStore.set(k,v),removeItem:k=>journalStore.delete(k)};vm.createContext(c);";assert.equal(old.split(anchor).length,2);const compatible=old.replace(anchor,insert);
const prefix=compatible.split("test('Double launch")[0],j=fs.readFileSync(path.join(__dirname,'tests.cjs'),'utf8');let journal=prefix+j.slice(j.indexOf('function setup(')).replace('m.exports.fixture()','fixture()').replace("fs.readFileSync(process.env.RAID_CLIENT_HTML,'utf8')","fs.readFileSync(process.env.RAID_CLIENT_HTML||local,'utf8')");
const outs={'emberweave-heroes.html':html,'tests/run_all_tests.sh':runner.replace(ro,rn),'tests/guild-raid-client.test.cjs':compatible,'tests/guild-raid-journal.test.cjs':journal};
const previous=fs.existsSync(path.join(__dirname,'manifest.json'))?JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.json'))).variants[0].output:{};
const base={'emberweave-heroes.html':plan.base,'tests/run_all_tests.sh':hash(runner),'tests/guild-raid-client.test.cjs':hash(old),'tests/guild-raid-journal.test.cjs':null},output={};for(const[f,s]of Object.entries(outs)){output[f]=hash(s);if(f==='emberweave-heroes.html')continue;const dest=path.join(__dirname,'payload/combined',f);fs.mkdirSync(path.dirname(dest),{recursive:true});if(fs.existsSync(dest))assert.equal(hash(fs.readFileSync(dest)),previous[f],'Preserve intervening edits');fs.writeFileSync(dest,s);}
fs.writeFileSync(path.join(__dirname,'manifest.json'),JSON.stringify({status:'PRIVATE_COMPONENT_TESTED_NOT_REVIEW_READY_NOT_SHIPPED',variants:[{name:'combined',base,output}]},null,2));fs.writeFileSync(path.join(__dirname,'spans.json'),JSON.stringify({'emberweave-heroes.html':plan.spans,'tests/run_all_tests.sh':[[ro,rn]],'tests/guild-raid-client.test.cjs':[[anchor,insert]]},null,2));for(const f of ['patch.cjs','install.cjs'])fs.copyFileSync(path.join(__dirname,'../guild-client-session-v942',f),path.join(__dirname,f));
const env={...process.env,RAID_CLIENT_HTML:path.join(__dirname,'payload/combined/emberweave-heroes.html'),API_SESSION_HTML:path.join(__dirname,'payload/combined/emberweave-heroes.html'),GUILD_CLIENT_HTML:path.join(__dirname,'payload/combined/emberweave-heroes.html')};
const files=['payload/combined/tests/guild-raid-client.test.cjs','payload/combined/tests/guild-raid-journal.test.cjs','../api-session-v942/tests.cjs','../guild-client-session-v942/tests.cjs'].map(f=>path.join(__dirname,f));const r=cp.spawnSync(process.execPath,['--test','--test-reporter=tap',...files],{env,windowsHide:true,encoding:'utf8',timeout:15000});fs.writeFileSync(path.join(__dirname,'composition.log'),r.stdout+r.stderr);assert.ifError(r.error);assert.equal(r.status,0,r.stdout+r.stderr);const proof={at:new Date().toISOString(),pass:Number(r.stdout.match(/# pass (\d+)/)?.[1]),fail:Number(r.stdout.match(/# fail (\d+)/)?.[1]),scope:'15journal+14prior handler assertions (only storage harness supplied)+23adjacent on changed candidate; not full canonical run'};fs.writeFileSync(path.join(__dirname,'composition.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));
