'use strict';const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const prefix=fs.readFileSync(path.join(__dirname,'../guild-raid-client-v942/tests.cjs'),'utf8').split("test('Double launch")[0],name=path.join(__dirname,'journal-vm-fixture.cjs'),m=new Module(name);m.filename=name;m.paths=Module._nodeModulePaths(__dirname);m._compile(prefix+'\nmodule.exports={fixture};',name);
function setup(shared=new Map(),failure=null){const f=m.exports.fixture();f.c.localStorage={getItem:k=>{if(failure==='get')throw Error('read denied');return shared.has(k)?shared.get(k):null;},setItem:(k,v)=>{if(failure==='set')throw Error('quota');shared.set(k,v);},removeItem:k=>{if(failure==='remove')throw Error('remove denied');shared.delete(k);}};return{...f,shared};}
const key='ew_raid_pending_v1_actor';
test('Actual delayed result timer has saved complete settlement before callback; cancellation keeps recovery',async()=>{const f=setup(),callbacks=new Map();let timer=0;f.c.setTimeout=fn=>{callbacks.set(++timer,fn);return timer;};f.c.clearTimeout=id=>callbacks.delete(id);const html=fs.readFileSync(process.env.RAID_CLIENT_HTML,'utf8'),a=html.indexOf('let _resultTimer='),z=html.indexOf('function cancelResult()',a),end=html.indexOf('\n',z);assert(a>=0&&z>a);vm.runInContext(html.slice(a,end),f.c);f.c.finishRaid();assert.equal(f.effects.packets.length,0);assert.equal(JSON.parse(f.shared.get(key)||'null')?.kind,'resolve','Must persist transcript before the actual800ms timer');f.c.cancelResult();assert.equal(callbacks.size,0);const fresh=setup(f.shared);fresh.c.raidRecoverSaved();assert.equal(fresh.effects.packets[0][2].attemptId,'attempt');fresh.reply({ok:true,dmg:1,ledger:{gold:100},reward:{guildCoins:0}});await fresh.flush();});
test('Double saved-result recovery click retains one active settlement request',async()=>{const f=setup();f.c.finishRaid();f.reject();await f.flush();const fresh=setup(f.shared);fresh.c.raidRecoverSaved();fresh.c.raidRecoverSaved();assert.equal(fresh.effects.packets.length,1,'Recovery must reuse the active settlement queue');fresh.reply({ok:true,dmg:1,ledger:{gold:100},reward:{guildCoins:0}});await fresh.flush();assert.equal(fresh.effects.adopt.length,1);});
test('Journal helpers exist before outbound network; baseline lacks reload recovery',()=>{const f=setup();assert.equal(typeof f.c.raidJournalRead,'function');assert.equal(typeof f.c.raidRecoverSaved,'function');});
test('Entry identity is persisted before the first request can leave',async()=>{const f=setup();const p=f.c.raidLaunch();const written=f.shared.has(key);f.reject();await p.catch(()=>{});assert.equal(written,true,'Reload must have the exact intent even when this first reply is lost');});
test('Lost entry reload retains original squad/request and only manual recovery sends',async()=>{const f=setup();const p=f.c.raidLaunch();assert.equal(f.effects.packets.length,1);const saved=JSON.parse(f.shared.get(key));assert.equal(saved.kind,'start');assert.equal(saved.accountId,'actor');assert.equal(saved.guildId,'guild');assert(!JSON.stringify(saved).includes('token'));f.reject();await p;const fresh=setup(f.shared);assert.equal(fresh.effects.packets.length,0);const retry=fresh.c.raidLaunch();assert.deepEqual(fresh.effects.packets[0][2],f.effects.packets[0][2]);fresh.reply({attemptId:'saved',boss:{key:'boss',hp:1},seed:1,snaps:[]});await retry;assert.equal(fresh.effects.battles,1);assert(f.shared.has(key),'Entry retained during battle until settlement saved');});
test('Settlement reload uses complete original transcript/damage/intent and clears only after confirmed reply',async()=>{const f=setup();f.c.finishRaid();f.reject();await f.flush();const original=f.effects.packets[0][2],saved=JSON.parse(f.shared.get(key));assert.equal(saved.kind,'resolve');const fresh=setup(f.shared);fresh.c.INPUT_LOG=[];fresh.c.raidDamageDone=()=>999999;fresh.c.raidRecoverSaved();assert.deepEqual(fresh.effects.packets[0][2],original);fresh.reply({ok:true,dmg:100,ledger:{gold:100},raid:{hp:1,max:2,attemptsLeft:2},reward:{guildCoins:2}});await fresh.flush();assert.equal(fresh.effects.adopt.length,1);assert.equal(f.shared.has(key),false);});
for(const failure of ['get','set'])test('Storage '+failure+' failure refuses entry and settlement before network',async()=>{const f=setup(new Map(),failure);await f.c.raidLaunch();assert.equal(f.effects.packets.length,0);f.c.finishRaid();await f.flush();assert.equal(f.effects.packets.length,0);assert.equal(f.els.resultTitle.textContent,'RESULT UNCONFIRMED');});
for(const raw of ['{',JSON.stringify({v:2}), 'x'.repeat(160001)])test('Corrupt journal refuses new entry and is preserved '+raw.length,async()=>{const s=new Map([[key,raw]]),f=setup(s);await f.c.raidLaunch();assert.equal(f.effects.packets.length,0);assert.equal(s.get(key),raw);assert.equal(f.c.raidJournalRead().blocked,true);});
test('Journal from another guild refuses instead of deleting or charging; other account cannot recover it',async()=>{const f=setup();const p=f.c.raidLaunch();f.reject();await p;const raw=f.shared.get(key);const other=setup(f.shared);other.c.G.guild.id='other';await other.c.raidLaunch();assert.equal(other.effects.packets.length,0);assert.equal(f.shared.get(key),raw);other.c.ACC.id='other';assert.equal(other.c.raidJournalRead(),null);other.c.raidRecoverSaved();assert.equal(other.effects.packets.length,0);});
test('Retained expired entry cannot turn into a new charge after reload',async()=>{const f=setup();let now=1000000;f.c.Date={now:()=>now};const p=f.c.raidLaunch();f.reject();await p;const fresh=setup(f.shared);fresh.c.Date={now:()=>now+600001};await fresh.c.raidLaunch();assert.equal(fresh.effects.packets.length,0);assert.match(fresh.effects.banners.at(-1),/window closed/);assert(f.shared.has(key));});
test('Unknown/pruned409 and expired settlement recovery never automatically creates fresh intent',async()=>{for(const reply of [{ok:false,error:'No matching raid battle.'},{ok:false,error:'Raid receipt does not match.'},{ok:false,expired:true,error:'Expired'}]){const f=setup();f.c.finishRaid();f.reply(reply);await f.flush();assert.equal(f.effects.battles,0);assert.equal(f.effects.adopt.length,0);assert.equal(f.shared.has(key),!reply.expired);}});
test('Cleanup storage failure keeps receipt identity for safe future confirmation',async()=>{const f=setup(new Map(),'remove');f.c.finishRaid();const packet=f.effects.packets[0][2];f.reply({ok:true,dmg:1,ledger:{gold:100},reward:{guildCoins:0}});await f.flush();assert(f.shared.has(key));const fresh=setup(f.shared);fresh.c.raidRecoverSaved();assert.deepEqual(fresh.effects.packets[0][2],packet);fresh.reply({ok:true,dmg:1,ledger:{gold:100},reward:{guildCoins:0}});await fresh.flush();assert.equal(f.shared.has(key),false);});
