'use strict';const test=require('node:test'),assert=require('node:assert/strict'),A=require('./composition-facade.cjs');const copy=x=>JSON.parse(JSON.stringify(x));
function fixture(){const slots=new Map(),rows=new Map(),calls=[],f={session:{accountId:'actor',guildId:'guild',token:'fixture-memory-only',epoch:1},quiescent:true,busy:false,gate:null};
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.get(k)??null,setItem:(k,v)=>slots.set(k,v)};
 const directory={list:async(a,n)=>{if(f.gate)await f.gate;return [...rows.values()].filter(x=>x.accountId===a).slice(0,n).map(copy)},insertBounded:async r=>{if([...rows.values()].some(x=>x.accountId===r.accountId&&x.entry.requestId===r.entry.requestId))throw Error('Duplicate');rows.set(r.id,copy(r))},markConfirmed:async()=>{},retireConfirmed:async()=>{}};
 const opts={directory,storage,context:()=>f.session,locks:{request:async(k,o,fn)=>{if(f.busy)return fn(null);f.busy=true;try{return await fn({})}finally{f.busy=false}}},transport:async p=>{calls.push(copy(p));if(f.lost)throw Error('Lost reply');return f.reply||{ok:true}},legacyWritersQuiescent:async()=>f.quiescent};f.slots=slots;f.rows=rows;f.calls=calls;f.newClient=()=>A.create(opts);return f;}
const E={requestId:'entry',heroIds:['hero']},P={requestId:'result',attemptId:'attempt',inputLog:[],dmg:10};
test('1000 unrelated keys permit bounded legacy inspection',async()=>{const f=fixture();for(let i=0;i<1000;i++)f.slots.set('unrelated'+i,'x');await f.newClient().start(E,'one');assert.equal(f.calls.length,1);assert.equal(f.calls[0].mode,'fresh-entry')});
test('legacy canonical including corrupt value refuses without paid transport',async()=>{const f=fixture();f.slots.set('ew_raid_pending_v1_actor','bad');await assert.rejects(f.newClient().start(E,'one'),/unresolved/);assert.equal(f.calls.length,0)});
test('legacy stage even malformed suffix refuses',async()=>{const f=fixture();f.slots.set('ew_raid_pending_v1_actor_result_BAD','bad');await assert.rejects(f.newClient().start(E,'one'),/stage unresolved/);assert.equal(f.rows.size,0)});
test('unproven old writers refuse; cannot assume empty equals quiescent',async()=>{const f=fixture();f.quiescent=false;await assert.rejects(f.newClient().start(E,'one'),/quiescent/);assert.equal(f.calls.length,0)});
test('global inspection over4096 refuses, no independence claim above bound',async()=>{const f=fixture();for(let i=0;i<4097;i++)f.slots.set('key'+i,'x');await assert.rejects(f.newClient().start(E,'one'),/bound/);assert.equal(f.calls.length,0)});
test('session epoch changes across DB await refuse transport',async()=>{const f=fixture();let release;f.gate=new Promise(r=>release=r);const c=f.newClient(),q=c.start(E,'one');await new Promise(r=>setImmediate(r));f.session={...f.session,epoch:2};release();await assert.rejects(q,/Stale/);assert.equal(f.calls.length,0)});
test('lost paid response retains instance; recovery sends exact entry only',async()=>{const f=fixture();f.lost=true;await assert.rejects(f.newClient().start(E,'one'),/Lost/);assert.equal(f.rows.size,1);f.lost=false;await f.newClient().recover('one');assert.deepEqual(f.calls.map(x=>x.mode),['fresh-entry','entry-recovery-only']);assert.deepEqual(f.calls[1].packet,E)});
test('result recovery denial never creates fresh paid intent',async()=>{const f=fixture(),c=f.newClient(),s=await c.start(E,'one');c.stage(s.row,P);f.reply={ok:false,status:409,error:'Unknown'};const r=await f.newClient().recover('one');assert.equal(r.reply.status,409);assert.deepEqual(f.calls.map(x=>x.mode),['fresh-entry','result-recovery-only']);assert.deepEqual(f.calls[1].packet,P);assert.equal(f.rows.size,1)});
test('repeated click during busy lock produces only one transport',async()=>{const f=fixture();f.busy=true;await assert.rejects(f.newClient().start(E,'one'),/Busy/);assert.equal(f.calls.length,0);f.busy=false;await f.newClient().start(E,'one');await assert.rejects(f.newClient().start(E,'two'),/Recover existing/);assert.equal(f.calls.length,1)});
