'use strict';const test=require('node:test'),assert=require('node:assert/strict'),a=require('./hybrid-adapter.cjs');const copy=x=>JSON.parse(JSON.stringify(x));
const S={accountId:'actor',guildId:'guild'},E={requestId:'entry',heroIds:['hero']},P={requestId:'result',attemptId:'attempt',inputLog:[],dmg:10};
// Serialized commit model, not native DB. Directory dependency is not yet implemented.
function fixture(){const rows=new Map(),slots=new Map(),f={rows,slots,current:true,legacy:'clear',denied:false,retireDenied:false,commitGate:null,reads:[]};let chain=Promise.resolve();
 const serial=fn=>{const q=chain.then(fn);chain=q.catch(()=>{});return q;};
 const d={list:async(account,max)=>{f.reads.push({account,max});return [...rows.values()].filter(r=>r.accountId===account).slice(0,max).map(copy);},insertBounded:r=>serial(async()=>{if(f.commitGate)await f.commitGate;if(f.denied)throw Error('Enrollment aborted');const own=[...rows.values()].filter(x=>x.accountId===r.accountId);if(own.length>=4)throw Error('Capacity');if(own.some(x=>x.id===r.id||x.entry.requestId===r.entry.requestId))throw Error('Duplicate intent');rows.set(r.accountId+'|'+r.id,copy(r));}),markConfirmed:(r,p)=>serial(()=>{const old=rows.get(r.accountId+'|'+r.id);if(!old||JSON.stringify(old)!==JSON.stringify(r))throw Error('Changed directory');rows.set(r.accountId+'|'+r.id,{...copy(r),state:'confirmed',confirmedPacket:copy(p)});}),retireConfirmed:r=>serial(()=>{if(f.retireDenied)throw Error('Retire aborted');const old=rows.get(r.accountId+'|'+r.id);if(!old||old.state!=='confirmed')throw Error('Not confirmed');rows.delete(r.accountId+'|'+r.id);})};
 const storage={getItem:k=>slots.get(k)??null,setItem:(k,v)=>{if(f.denied)throw Error('Quota fixture');slots.set(k,v);},removeItem:k=>slots.delete(k)};
 f.newContext=()=>a.create(d,storage,{isCurrent:()=>f.current,legacyCheck:async()=>f.legacy});return f;}
test('Paid callback waits for committed enrollment, abort sends none',async()=>{const f=fixture(),h=f.newContext();let release,paid=0;f.commitGate=new Promise(r=>release=r);const wait=h.enroll(S,E,'one').then(()=>paid++);await Promise.resolve();await Promise.resolve();assert.equal(paid,0);f.denied=true;release();await assert.rejects(wait,/aborted/);assert.equal(paid,0);assert.equal(f.rows.size,0);});
test('Synchronous completion survives destroying writer context before delayed send',async()=>{const f=fixture(),h=f.newContext(),r=await h.enroll(S,E,'one');h.stage(r,P);const recovered=await f.newContext().recover(S);assert.equal(recovered[0].status,'result-recovery-only');assert.deepEqual(recovered[0].packet,P);});
test('Unrelated slots do not affect bounded account discovery',async()=>{const f=fixture(),h=f.newContext(),r=await h.enroll(S,E,'one');for(let i=0;i<1000;i++)f.slots.set('unrelated'+i,'x');h.stage(r,P);assert.equal((await h.recover(S)).length,1);assert(f.reads.every(r=>r.max===5&&r.account==='actor'));assert.equal(f.slots.size,1001);});
test('Repeated enrollment of same paid intent refuses rather than new instance',async()=>{const f=fixture(),h=f.newContext();await h.enroll(S,E,'one');await assert.rejects(h.enroll(S,E,'two'),/Duplicate/);assert.equal(f.rows.size,1);});
test('Empty enrolled slot is entry recovery only, no paid fallback',async()=>{const f=fixture(),h=f.newContext();await h.enroll(S,E,'one');assert.equal((await f.newContext().recover(S))[0].status,'entry-recovery-only');});
test('Changed packet refuses without overwrite; caller mutation copied',async()=>{const f=fixture(),h=f.newContext(),r=await h.enroll(S,E,'one'),p=copy(P);h.stage(r,p);p.dmg=99;await assert.rejects(async()=>h.stage(r,p),/conflict/);assert.equal((await h.recover(S))[0].packet.dmg,10);});
test('New context cannot acquire completion writer by knowing slot ID',async()=>{const f=fixture(),h=f.newContext(),r=await h.enroll(S,E,'one');assert.throws(()=>f.newContext().stage(r,P),/writer lease/);});
test('Denied result storage holds directory and refuses stage',async()=>{const f=fixture(),h=f.newContext(),r=await h.enroll(S,E,'one');f.denied=true;assert.throws(()=>h.stage(r,P),/Quota/);assert.equal(f.rows.size,1);assert.equal(f.slots.size,0);});
test('Legacy unknown and stale context cannot enroll',async()=>{const f=fixture(),h=f.newContext();f.legacy='unknown';await assert.rejects(h.enroll(S,E,'one'),/Legacy/);f.legacy='clear';f.current=false;await assert.rejects(h.enroll(S,E,'one'),/Stale/);assert.equal(f.rows.size,0);});
test('Unconfirmed cleanup cannot discard completed transcript',async()=>{const f=fixture(),h=f.newContext(),r=await h.enroll(S,E,'one');h.stage(r,P);await assert.rejects(h.cleanup(S,'one'),/Unconfirmed/);assert.equal(f.rows.size,1);assert.equal(f.slots.size,1);});
test('Interrupted cleanup retains confirmed marker, new context safely finishes',async()=>{const f=fixture(),h=f.newContext(),r=await h.enroll(S,E,'one');h.stage(r,P);await h.confirm(S,'one',P);f.retireDenied=true;await assert.rejects(h.cleanup(S,'one'),/Retire/);assert.equal(f.slots.size,1);assert.equal(JSON.parse(f.slots.get(a.key(r))).confirmed,true);assert.equal((await f.newContext().recover(S))[0].status,'confirmed-cleanup');f.retireDenied=false;await f.newContext().cleanup(S,'one');assert.equal(f.rows.size,0);assert.equal(f.slots.size,1);});
test('Old writer cannot recreate an orphan after another context confirms and cleans',async()=>{const f=fixture(),old=f.newContext(),r=await old.enroll(S,E,'one');old.stage(r,P);const fresh=f.newContext();await fresh.confirm(S,'one',P);await fresh.cleanup(S,'one');assert.throws(()=>old.stage(r,P),/conflict/);assert.equal(f.rows.size,0);});
