'use strict';const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');if(fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'))throw Error('Shutdown');
const source=fs.readFileSync(path.join(__dirname,'indexed-adapter.cjs'),'utf8'),session=crypto.randomUUID(),hash=crypto.createHash('sha256').update(source).digest('hex');let reports=[];
const html=`<!doctype html><meta charset="utf-8"><title>Private precommit closure fixture</title><style>body{background:#121923;color:#edf2f8;font:18px system-ui;margin:40px;max-width:1000px}button{padding:14px;margin:8px}pre{white-space:pre-wrap;padding:20px;background:#243247}</style><h1>Private precommit closure fixture</h1><p>Deliberately hold an actual IndexedDB result transaction for at most 20 seconds. No game or paid entry.</p><button id="stage">Stage held result</button><button id="read">Read committed records</button><pre id="out">Opening private database...</pre><script>
const module={exports:{}};${source}
const A=module.exports,session=${JSON.stringify(session)},adapterHash=${JSON.stringify(hash)},database='codex-precommit-'+session;
let db,phase='ready',acknowledged=false,done=false,reads=0,startedAt=null;
const row={v:2,id:'held-result',accountId:'fixture-actor',guildId:'fixture-guild',createdAt:1,entryRequestId:null,packet:{requestId:'held-result',attemptId:'fixture-attempt',inputLog:[],dmg:10}};
async function report(extra={}){const p={session,adapterHash,phase,acknowledged,done,reads,startedAt,at:Date.now(),...extra};document.getElementById('out').textContent=JSON.stringify(p,null,2);await fetch('/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});}
function held(base){return {transaction(name,mode){const tx=base.transaction(name,mode);const stop=Date.now()+20000;return {get error(){return tx.error},set oncomplete(v){tx.oncomplete=v},set onabort(v){tx.onabort=v},set onerror(v){tx.onerror=v},abort:()=>tx.abort(),objectStore(n){const s=tx.objectStore(n);return {index:k=>s.index(k),get:k=>s.get(k),delete:k=>s.delete(k),add:p=>{const q=s.add(p);q.addEventListener('success',()=>{phase='ADD_SUCCEEDED_TRANSACTION_PENDING';report({transactionComplete:false});function pump(){if(Date.now()>=stop)return;reads++;const r=s.get([p.accountId,p.id]);r.onsuccess=pump;}pump();});return q;}}}}}};}
document.getElementById('stage').onclick=async()=>{document.getElementById('stage').disabled=true;startedAt=Date.now();phase='REGISTERING';await report();try{await A.register(held(db),row);phase='COMMITTED_ACKNOWLEDGED';acknowledged=true;done=true;}catch(e){phase='ABORTED';done=true;}await report();};
document.getElementById('read').onclick=async()=>{const rows=await A.discover(db,'fixture-actor','fixture-guild');phase='READ_COMPLETE';await report({committedRows:rows});};
const q=indexedDB.open(database,1);q.onupgradeneeded=()=>{const s=q.result.createObjectStore('results',{keyPath:['accountId','id']});s.createIndex('account','accountId')};q.onerror=()=>{phase='OPEN_FAILED';report({error:String(q.error)})};q.onsuccess=()=>{db=q.result;report()};
</script>`;
new(require('node:vm').Script)(html.match(/<script>([\s\S]*)<\/script>/)[1]);
const server=http.createServer(async(req,res)=>{if(req.url==='/shutdown'){res.end('Stopped');server.close(()=>process.exit(0));server.closeAllConnections();return}if(req.url==='/evidence'){res.setHeader('content-type','application/json');res.end(JSON.stringify({session,adapterHash:hash,reports}));return}if(req.url==='/report'&&req.method==='POST'){let raw='';for await(const b of req){raw+=b;if(raw.length>200000){res.writeHead(413).end();return}}try{reports.push(JSON.parse(raw));res.end('Saved')}catch{res.writeHead(400).end()}return}res.setHeader('content-type','text/html');res.end(html)});
server.listen(0,'127.0.0.1',()=>{const meta={url:'http://127.0.0.1:'+server.address().port,session,adapterHash:hash};fs.writeFileSync(path.join(__dirname,'precommit-session.json'),JSON.stringify(meta,null,2));console.log(JSON.stringify(meta))});setTimeout(()=>{server.close(()=>process.exit(0));server.closeAllConnections()},300000).unref();
