'use strict';const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),a=require('node:assert/strict'),crypto=require('node:crypto');
const original=!!process.env.GUILD_DISCOVERY_CONTROL,html=fs.readFileSync(path.join(__dirname,original?'../guild-raid-ten-slot-v948/private-client-ten-slot.html':'private-client-guild-discovery.html'),'utf8'),b=html.indexOf('const EW_RAID_V3_MODULES='),e=html.indexOf('// PRIVATE guarded v3 cutover.',b),M=vm.runInNewContext(html.slice(b,e)+'\nEW_RAID_V3_MODULES;'),clone=x=>JSON.parse(JSON.stringify(x)),results=[];
const row=(guild,id)=>({v:3,accountId:'actor',guildId:guild,id,entry:{requestId:id,heroIds:['vael']},state:'pending'});
async function run(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(err){results.push({name,status:'FAIL',error:err.message});process.exitCode=1}}
(async()=>{
await run('mixed guild rows discover current guild and preserve other guild without writes',async()=>{const rows=[row('old','old-entry'),row('current','current-entry')],before=JSON.stringify(rows),h=M.hybrid.create({async list(){return clone(rows)}},{getItem:()=>null},{isCurrent:()=>true});a.deepEqual(clone(await h.recover({accountId:'actor',guildId:'current'})).map(x=>x.row.id),['current-entry']);a.equal(JSON.stringify(rows),before);a.deepEqual(clone(await h.recover({accountId:'actor',guildId:'old'})).map(x=>x.row.id),['old-entry'])});
await run('new guild with only previous guild row discovers empty without deleting paid intent',async()=>{const rows=[row('old','old-entry')],h=M.hybrid.create({async list(){return clone(rows)}},{getItem:()=>null},{isCurrent:()=>true});a.deepEqual(clone(await h.recover({accountId:'actor',guildId:'new'})),[]);a.equal(rows.length,1)});
await run('foreign account, invalid guild and total account overflow still hold',async()=>{for(const rows of [[{...row('old','old-entry'),accountId:'foreign'}],[{...row('old','old-entry'),guildId:''}],Array.from({length:5},(_,i)=>row('old','id'+i))]){const h=M.hybrid.create({async list(){return clone(rows)}},{getItem:()=>null},{isCurrent:()=>true});await a.rejects(h.recover({accountId:'actor',guildId:'current'}))}});
const cert={atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),clientSHA256:crypto.createHash('sha256').update(html).digest('hex'),results,scope:'Actual embedded hybrid/row validation with modeled directory read and no writes. NOT native IndexedDB, actual server guild leave/switch, full HTML/browser, balance or deployment.'};fs.writeFileSync(path.join(__dirname,original?'original-control.json':'certificate.json'),JSON.stringify(cert,null,2));console.log(JSON.stringify(cert));})();
