'use strict';const {test}=require('node:test'),a=require('node:assert/strict'),{create}=require(process.env.DAILY_CONTROL?'./ticket-model.cjs':'./daily-model.cjs');
const day0=Date.parse('2026-10-03T23:59:00Z'),day1=Date.parse('2026-10-04T00:00:00Z');
function fixture(){let db={users:{actor:{guildId:'g1'}}},now=day0,fault=false,tail=Promise.resolve();const store={atomic(fn){const p=tail.then(async()=>{const d=structuredClone(db),r=await fn(d);if(fault)throw Error('Save failed');db=d;return r});tail=p.catch(()=>{});return p}};const service=()=>create(store,{context:()=>({accountId:'actor',epoch:1}),clock:()=>now,secret:'isolated-fixture-signing-key'});return {service,read:()=>structuredClone(db),time:t=>now=t,guild:g=>db.users.actor.guildId=g,fault:x=>fault=x}}
const packet=i=>({requestId:'r3-dailytest'+i,heroIds:['fighter']});
test('preparing many tickets does not reserve charges; only three distinct starts accepted',async()=>{const f=fixture(),s=f.service(),tickets=[];for(let i=0;i<4;i++)tickets.push((await s.prepare(packet(i))).ticket);for(let i=0;i<3;i++)a.equal((await s.start(tickets[i])).accepted.spent,true);const r=await s.start(tickets[3]);a.equal(r.terminal?.kind,'exhausted-unspent');a.equal(r.terminal.spent,false);a.deepEqual(await f.service().start(tickets[3]),r);a.equal(f.read().users.actor.spent,3)});
test('D-issued ticket started in D+1 consumes D+1 cap, not an extra old-day entitlement',async()=>{const f=fixture(),s=f.service(),tickets=[];for(let i=0;i<4;i++)tickets.push((await s.prepare(packet(i))).ticket);f.time(day1);const first=await s.start(tickets[0]);a.equal(first.accepted.chargeDay,'2026-10-04');a.equal(first.accepted.ticket.claims.period,'2026-10-03');for(let i=1;i<3;i++)await s.start(tickets[i]);a.equal((await s.start(tickets[3])).terminal?.kind,'exhausted-unspent');a.equal(f.read().users.actor.raidDay.n,3)});
test('guild hopping does not replenish player daily cap',async()=>{const f=fixture(),s=f.service();for(let i=0;i<3;i++)await s.start((await s.prepare(packet(i))).ticket);f.guild('g2');const r=await f.service().start((await f.service().prepare(packet(3))).ticket);a.equal(r.terminal?.kind,'exhausted-unspent');a.equal(f.read().users.actor.spent,3)});
test('accepted old-day receipt replay does not reset or charge new-day usage',async()=>{const f=fixture(),s=f.service(),{ticket}=await s.prepare(packet(0)),r=await s.start(ticket);f.time(day1);a.deepEqual(await f.service().start(ticket),r);a.equal(f.read().users.actor.raidDay?.d,'2026-10-03');a.equal(f.read().users.actor.spent,1)});
test('failed daily spend transaction does not consume cap; exact retry consumes once',async()=>{const f=fixture(),s=f.service(),{ticket}=await s.prepare(packet(0)),before=f.read();f.fault(true);await a.rejects(s.start(ticket),/Save failed/);a.deepEqual(f.read(),before);f.fault(false);const r=await f.service().start(ticket);a.deepEqual(await f.service().start(ticket),r);a.equal(f.read().users.actor.raidDay?.n,1);a.equal(f.read().users.actor.spent,1)});
