'use strict';const {test}=require('node:test'),a=require('node:assert/strict'),{create}=require(process.env.PHASE_CONTROL?'./client-phase-model.cjs':'./client-disposition-model.cjs');
const P={requestId:'r3-firstintent',heroIds:['fighter','backup']},Q={requestId:'r3-secondintent',heroIds:['other']};
function fixture(kind='cancelled'){let row=null,fail=false,calls=0,ticket,corrupt=false;const api={async prepare(p){ticket={claims:{requestId:p.requestId,heroIds:structuredClone(p.heroIds)},signature:'fixture-only'};return {status:200,ticket}},async start(t){calls++;const r=kind==='accepted'?{status:200,accepted:{ticket:structuredClone(t),attemptId:'paid-one',spent:true}}:{status:200,terminal:{ticket:structuredClone(t),kind,spent:false,lateStartRefused:true}};if(corrupt)(r.accepted||r.terminal).ticket.claims.requestId='r3-foreignintent';return r}};const journal={async read(){return structuredClone(row)},async save(r){if(fail&&['active','done'].includes(r.phase))throw Error('Final journal save failed');row=structuredClone(r)}};return {client:()=>create(journal,api),read:()=>structuredClone(row),fail:x=>fail=x,corrupt:x=>corrupt=x,calls:()=>calls}}
test('unspent terminal disposition is durable done, not permanent start',async()=>{const f=fixture();await f.client().recover(P);a.equal(f.read().phase,'done')});
test('accepted entry is active, never marked done before the paid fight settles',async()=>{const f=fixture('accepted');await f.client().recover(P);a.equal(f.read().phase,'active')});
test('saved active or done recovery has no repeated start network calls',async()=>{for(const kind of ['accepted','exhausted-unspent']){const f=fixture(kind);await f.client().recover(P);const n=f.calls();await f.client().recover(Q);a.equal(f.calls(),n)}});
test('mismatched reply cannot advance stored journal phase',async()=>{const f=fixture();f.corrupt(true);await a.rejects(f.client().recover(P),/binding/);a.equal(f.read().phase,'start')});
test('disposition save failure retains exact pending ticket for later proof retry',async()=>{const f=fixture();f.fail(true);await a.rejects(f.client().recover(P),/save failed/);a.equal(f.read().phase,'start');f.fail(false);await f.client().recover(Q);a.equal(f.read().phase,'done');a.equal(f.read().intent.requestId,P.requestId)});
if(!process.env.PHASE_CONTROL){test('only explicit new-entry call after unspent done starts a different intent',async()=>{const f=fixture(),c=f.client();await c.recover(P);await c.recover(Q);a.equal(f.calls(),1);await c.startNew(Q);a.equal(f.calls(),2);a.equal(f.read().intent.requestId,Q.requestId)});test('active paid fight prevents explicit new-entry replacement',async()=>{const f=fixture('accepted'),c=f.client();await c.recover(P);a.equal((await c.startNew(Q)).held,true);a.equal(f.calls(),1);a.equal(f.read().intent.requestId,P.requestId)})}
