'use strict';
const {test}=require('node:test'),a=require('node:assert/strict');
const {create}=require(process.env.TICKET_CONTROL?'./ticket-model-before-bounds.cjs':'./ticket-model.cjs');
const P={requestId:'r3-edgerequest',heroIds:['fighter','backup']};
function fixture(){let db={users:{actor:{guildId:'guild'}}},now=100000,epoch=1,fault=false,tail=Promise.resolve();const store={atomic(fn){const p=tail.then(async()=>{const d=structuredClone(db),r=await fn(d);if(fault)throw Error('Save failed');db=d;return r});tail=p.catch(()=>{});return p}};const options={context:()=>({accountId:'actor',epoch}),clock:()=>now,secret:'isolated-fixture-signing-key'};return {service:()=>create(store,options),store,options,read:()=>structuredClone(db),fault:x=>fault=x,epoch:()=>epoch++,prune:()=>delete db.users.actor.raidEntryTickets}}
test('reject unbounded quota and duration before any transaction',()=>{const f=fixture();for(const maxRecords of [0,-1,Infinity,NaN,1.5,65])a.throws(()=>create(f.store,{...f.options,maxRecords}),/Bounded/);for(const sessionMs of [0,-1,Infinity,NaN,1.5,600001])a.throws(()=>create(f.store,{...f.options,sessionMs}),/Bounded/)});
test('race orders converge to one durable disposition',async()=>{for(const cancelFirst of [false,true]){const f=fixture(),s=f.service(),{ticket}=await s.prepare(P);const results=await Promise.all(cancelFirst?[s.cancel(ticket),s.start(ticket)]:[s.start(ticket),s.cancel(ticket)]);a.deepEqual(results[0],results[1]);a.equal(f.read().users.actor.spent||0,cancelFirst?0:1)}});
test('failed start save exposes no accepted receipt or charge; exact retry commits once',async()=>{const f=fixture(),s=f.service(),{ticket}=await s.prepare(P),before=f.read();f.fault(true);await a.rejects(s.start(ticket),/Save failed/);a.deepEqual(f.read(),before);f.fault(false);const r=await f.service().start(ticket);a.deepEqual(await f.service().start(ticket),r);a.equal(f.read().users.actor.spent,1)});
test('failed cancel save gives no terminal proof and leaves prepared ticket recoverable',async()=>{const f=fixture(),s=f.service(),{ticket}=await s.prepare(P),before=f.read();f.fault(true);await a.rejects(s.cancel(ticket),/Save failed/);a.deepEqual(f.read(),before);f.fault(false);a.equal((await f.service().cancel(ticket)).terminal.spent,false)});
test('pruned ticket start and recovery remain held, never mint or charge',async()=>{const f=fixture(),s=f.service(),{ticket}=await s.prepare(P);f.prune();a.equal((await f.service().start(ticket)).status,409);a.equal((await f.service().prepare(P,{recoverOnly:true})).status,409);a.equal(f.read().users.actor.spent,undefined);a.equal(f.read().users.actor.raidEntryTickets,undefined)});
test('session switch refuses retained service before spending',async()=>{const f=fixture(),s=f.service(),{ticket}=await s.prepare(P),before=f.read();f.epoch();await a.rejects(s.start(ticket),/Stale actor/);a.deepEqual(f.read(),before)});
