'use strict';const {test}=require('node:test'),a=require('node:assert/strict'),{create}=require('./ticket-model.cjs');
const P={requestId:'r3-requestone',heroIds:['vael','other']};
function fixture(){let db={users:{actor:{guildId:'guild'}}},now=Date.parse('2026-10-03T23:59:00Z'),fault=false,tail=Promise.resolve();const store={atomic(fn){const p=tail.then(async()=>{const d=structuredClone(db),r=await fn(d);if(fault)throw Error('Save failed');db=d;return r});tail=p.catch(()=>{});return p}};const service=()=>create(store,{context:()=>({accountId:'actor',epoch:1}),clock:()=>now,secret:'isolated-fixture-signing-key'});return {s:service(),reload:service,read:()=>structuredClone(db),time:n=>now=n,guild:g=>db.users.actor.guildId=g,fault:x=>fault=x}}
test('server clock issues ticket; repeat prepare across midnight returns exact prior ticket',async()=>{const f=fixture(),r=await f.s.prepare(P);f.time(Date.parse('2026-10-04T00:00:00Z'));a.deepEqual(await f.reload().prepare(P,{recoverOnly:true}),r);a.equal(r.ticket.claims.period,'2026-10-03');a.equal(f.read().users.actor.spent,undefined)});
test('missing recovery prepare cannot mint a new ticket',async()=>{const f=fixture();a.equal((await f.s.prepare(P,{recoverOnly:true})).status,409);a.equal(f.read().users.actor.raidEntryTickets,undefined)});
test('failed prepare save exposes no ticket and no durable intent',async()=>{const f=fixture(),before=f.read();f.fault(true);await a.rejects(f.s.prepare(P),/Save failed/);a.deepEqual(f.read(),before);f.fault(false);a.equal((await f.s.prepare(P)).status,200)});
test('cancel issued unspent ticket fences delayed start without a charge',async()=>{const f=fixture(),{ticket}=await f.s.prepare(P),r=await f.s.cancel(ticket);a.equal(r.terminal.spent,false);a.deepEqual(await f.reload().start(ticket),r);a.equal(f.read().users.actor.spent,undefined)});
test('paid accepted entry keeps exact receipt across midnight and cancel',async()=>{const f=fixture(),{ticket}=await f.s.prepare(P),r=await f.s.start(ticket);f.time(Date.parse('2026-10-04T00:00:00Z'));a.deepEqual(await f.reload().cancel(ticket),r);a.equal(f.read().users.actor.spent,1)});
test('guild change cancels prepared ticket only; does not refund prior accepted entry',async()=>{for(const paid of [false,true]){const f=fixture(),{ticket}=await f.s.prepare(P);let prior;if(paid)prior=await f.s.start(ticket);f.guild('other-guild');const r=await f.reload().start(ticket);if(paid)a.deepEqual(r,prior);else{a.equal(r.terminal.kind,'guild-changed');a.equal(r.terminal.spent,false)}a.equal(f.read().users.actor.spent||0,paid?1:0)}});
test('expired prepared ticket cannot be spent; boundary itself remains accepted',async()=>{for(const offset of [0,1]){const f=fixture(),{ticket}=await f.s.prepare(P);f.time(ticket.claims.expiresAt+offset);const r=await f.s.start(ticket);if(offset)a.equal(r.terminal.kind,'expired-unspent');else a.equal(r.accepted.spent,true)}});
test('tampered clock, squad order, actor and signature fail without mutation',async()=>{const f=fixture(),{ticket}=await f.s.prepare(P),before=f.read();for(const change of [t=>t.claims.issuedAt++,t=>t.claims.heroIds.reverse(),t=>t.claims.accountId='victim',t=>t.signature='fake']){const t=structuredClone(ticket);change(t);await a.rejects(f.s.start(t));a.deepEqual(f.read(),before)}});
test('new-protocol legacy no-ticket entry refused without spending',async()=>{const f=fixture();a.equal((await f.s.legacyV3Start(P)).status,426);a.equal(f.read().users.actor.spent,undefined)});
