'use strict';const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.join(__dirname,'../shady-gold-v942/snapshot'),server=path.join(root,'server.js'),leader=path.join(root,'tests/guild-leadership.test.cjs'),saved=fs.readFileSync(server),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
assert.equal(hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');assert(!fs.existsSync(leader));assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
async function run(){let f,copied=false;try{
 fs.copyFileSync(path.join(__dirname,'../guild-leadership-v942/tests.cjs'),leader);copied=true;fs.copyFileSync(path.join(__dirname,'payload/server.js'),server);
 const file=path.join(root,'tests/private-composition-http.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(fs.readFileSync(path.join(__dirname,'tests.cjs'),'utf8').split('const E=')[0].replace('root=process.env.GUILD_FIXTURE_ROOT','root='+JSON.stringify(root))+'\nmodule.exports={setup};',file);({f}=await m.exports.setup());
 const A=require('../guild-raid-discovery-design-v942/composition-facade.cjs'),slots=new Map(),rows=new Map(),calls=[],copy=x=>JSON.parse(JSON.stringify(x));let lost=true;
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.get(k)??null,setItem:(k,v)=>slots.set(k,v)};
 const directory={list:async(a,n)=>[...rows.values()].filter(x=>x.accountId===a).slice(0,n).map(copy),insertBounded:async r=>{assert(!rows.has(r.id));rows.set(r.id,copy(r))},markConfirmed:async()=>{},retireConfirmed:async()=>{}};
 const transport=async p=>{assert(['fresh-entry','entry-recovery-only'].includes(p.mode));const body={...p.packet,...(p.mode==='entry-recovery-only'?{recoverOnly:true}:{})};calls.push({mode:p.mode,packet:copy(p.packet),body});const reply=await f.call('/api/guild/raid/start',body);if(lost){lost=false;throw Error('Committed reply lost')}return reply;};
 const deps={directory,storage,locks:{request:async(k,o,fn)=>fn({})},transport,legacyWritersQuiescent:async()=>true};
 function fresh(){return vm.runInNewContext("A.create({...deps,context:()=>({accountId:'fixture-user',guildId:'own-guild',token:'memory-only-fixture',epoch:1})})",{A,deps})}
 const E={requestId:'composition-entry',heroIds:['vael']};await assert.rejects(fresh().start(E,'entry-instance'),/Committed reply lost/);assert.equal(rows.size,1);const committed=f.bytes(),attempt=f.disk().guilds['own-guild'].raid.att['fixture-user'].id;
 await f.stop();await f.launch();assert.equal(calls.length,1);const recovery=await fresh().recover('entry-instance');assert.equal(recovery.reply.status,200);assert.equal(recovery.reply.body.resumed,true);assert.equal(recovery.reply.body.attemptId,attempt);assert.deepEqual(calls.map(x=>x.mode),['fresh-entry','entry-recovery-only']);assert.deepEqual(calls[0].packet,calls[1].packet);assert.equal(calls[1].body.recoverOnly,true);assert.equal(f.bytes(),committed);assert.equal(f.disk().users['fixture-user'].raidDay.n,1);
 await assert.rejects(fresh().recover('missing-instance'),/No recoverable/);assert.equal(calls.length,2);assert.equal(f.bytes(),committed);
 // Recovery currently exposes no validated writer lease for the resumed battle.
 const recoveredRow=rows.get('entry-instance');assert.throws(()=>fresh().stage(recoveredRow,{requestId:'result',attemptId:attempt,inputLog:[],dmg:10}),/No writer lease/);
 fs.writeFileSync(path.join(__dirname,'integration-results.json'),JSON.stringify({at:new Date().toISOString(),pass:true,serverHash:hash(fs.readFileSync(server)),facadeHash:hash(fs.readFileSync(path.join(__dirname,'../guild-raid-discovery-design-v942/composition-facade.cjs'))),calls,entryCount:1,scope:'Fresh VM facade instances + actual private HTTP/restart, model storage/locks and injected quiescence. Not native/full HTML or settlement/grant proof.',open:'Resumed battle writer lease/bootstrap validation not implemented; new VM cannot stage its result. Unknown manual instance refused without transport; no automatic sends.'},null,2));console.log('PASS private facade freshVM entry lost reply/restart strict recovery one attempt; confirmed resumed-result writer lease dependency remains OPEN');
}finally{if(f)await f.stop();fs.writeFileSync(server,saved);if(copied)fs.unlinkSync(leader);assert.equal(hash(fs.readFileSync(server)),hash(saved));}}
run().catch(e=>{console.error(e);process.exitCode=1});
