'use strict';const test=require('node:test'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict'),root=process.env.GUILD_FIXTURE_ROOT;
async function setup(kind='valid'){
 const file=path.join(root,'tests/private-recovery-only-fixture.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));
 let s=fs.readFileSync(path.join(root,'tests/guild-leadership.test.cjs'),'utf8').split("for(const kind of ['stale','missing'])")[0];
 s=s.replace("u.guildId='own-guild';","u.guildId='own-guild';u.led.skill={vael:[1,1,1,1]};u.led.skillImported=1790928000000;");
 if(kind==='expired'){
  const raid={level:1,max:400000,hp:400000,kills:0,contrib:{},used:{'fixture-user':1},day:'2026-10-02',att:{'fixture-user':{id:'expired-attempt',reqId:'entry',startedAt:1790928000000-600001,bossKey:'skarrn',bossLvl:1,bossHp:400000,tier:1,seed:1,snaps:null}}};
  s=s.replace('level:1,exp:0,log:[],reqs:[]',`level:1,exp:0,log:[],reqs:[],raid:${JSON.stringify(raid)}`);
 }
 m._compile(s+'\nmodule.exports={setup};',file);return m.exports.setup('valid');
}
const E={requestId:'entry',heroIds:['vael']};
test('unknown/pruned recovery request refuses409 without new attempt or mutation',async()=>{const{f}=await setup();try{const before=f.bytes();const r=await f.call('/api/guild/raid/start',{...E,recoverOnly:true});assert.equal(r.status,409);assert.equal(r.body.recoveryUnknown,true);assert.equal(f.bytes(),before);assert.equal(f.disk().guilds['own-guild'].raid,undefined)}finally{await f.stop()}});
test('expired matching entry recovery refuses409 and retains old attempt',async()=>{const{f}=await setup('expired');try{const before=f.bytes();const r=await f.call('/api/guild/raid/start',{...E,recoverOnly:true});assert.equal(r.status,409);assert.equal(r.body.recoveryUnknown,true);assert.equal(f.bytes(),before);assert.equal(f.disk().guilds['own-guild'].raid.att['fixture-user'].id,'expired-attempt')}finally{await f.stop()}});
test('wrong recovery intent does not replace another open attempt',async()=>{const{f}=await setup();try{await f.call('/api/guild/raid/start',E);const before=f.bytes();const r=await f.call('/api/guild/raid/start',{...E,requestId:'other',recoverOnly:true});assert.equal(r.status,409);assert.equal(f.bytes(),before);assert.equal(f.disk().users['fixture-user'].raidDay.n,1)}finally{await f.stop()}});
test('nonboolean recovery modes reject400 before resume or fresh consumption',async()=>{const{f}=await setup();try{await f.call('/api/guild/raid/start',E);const before=f.bytes();for(const recoverOnly of ['true','false',0,1,null,[],{}]){assert.equal((await f.call('/api/guild/raid/start',{...E,recoverOnly})).status,400);assert.equal(f.bytes(),before)}}finally{await f.stop()}});
test('committed entry reply lost: manual strict recovery after restart resumes same frozen fight once',async()=>{const{f}=await setup();try{const first=await f.call('/api/guild/raid/start',E);assert.equal(first.status,200);assert(first.body.attemptId);const before=f.bytes();await f.stop();await f.launch();const r=await f.call('/api/guild/raid/start',{...E,recoverOnly:true});assert.equal(r.status,200);assert.equal(r.body.resumed,true);for(const k of ['attemptId','seed','snaps','engine'])assert.deepEqual(r.body[k],first.body[k]);assert.equal(f.bytes(),before);assert.equal(f.disk().users['fixture-user'].raidDay.n,1);assert.equal(f.disk().guilds['own-guild'].raid.used['fixture-user'],1)}finally{await f.stop()}});
test('explicit fresh intent remains authorized historical behavior; false is not recovery mode',async()=>{const{f}=await setup();try{await f.call('/api/guild/raid/start',E);const r=await f.call('/api/guild/raid/start',{...E,requestId:'fresh-second',recoverOnly:false});assert.equal(r.status,200);assert.equal(f.disk().users['fixture-user'].raidDay.n,2)}finally{await f.stop()}});
