'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),Module=require('node:module'),a=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.join(__dirname,'../shady-gold-v942/snapshot'),server=path.join(root,'server.js'),saved=fs.readFileSync(server),hash=x=>crypto.createHash('sha256').update(x).digest('hex'),clone=x=>JSON.parse(JSON.stringify(x));
a.equal(hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');a(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
const html=fs.readFileSync(path.join(__dirname,process.env.INTEGRATED_CONTROL?'../guild-raid-rebase-v948/private-client-v948.html':'private-client-ten-slot.html'),'utf8'),b=html.indexOf('const EW_RAID_V3_MODULES='),e=html.indexOf('// PRIVATE guarded v3 cutover.',b);a(b>0&&e>b);
a.equal(hash(html),process.env.INTEGRATED_CONTROL?'a16689865954f8d2a9add81b21749cbbea0702aeb7d97608eaa478d404781552':'9da6e0554c1c754f60adec9d25bbf4aad39310d545829a45c5bf6a853c5085b6');
const serverSource=fs.readFileSync(path.join(__dirname,'private-server-retained-attempt.js'));a.equal(hash(serverSource),'c44be6449a11d557522d1d6c5035c879214f762a7f5bb289ae0a313450caa75d');
let f,failure=null;const calls=[],rows=new Map(),slots=new Map();let loseEntry=true,loseResult=true,locked=false;
const heroes=Object.keys(JSON.parse(fs.readFileSync(path.join(root,'hero_base.json'),'utf8'))).slice(0,10);a.equal(heroes.length,10);
function client(){const M=vm.runInNewContext(html.slice(b,e)+'\nEW_RAID_V3_MODULES;');
 const directory={async list(account){return clone([...rows.values()].filter(r=>r.accountId===account))},async insertBounded(row,cap){M.directory.row(row);a(rows.size<cap);a(!rows.has(row.id));rows.set(row.id,clone(row))},async markConfirmed(row,p){a.deepEqual(rows.get(row.id),clone(row));rows.set(row.id,{...clone(row),state:'confirmed',confirmedPacket:clone(p)})},async retireConfirmed(row){a.equal(rows.get(row.id).state,'confirmed');rows.delete(row.id)}};
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i],getItem:k=>slots.has(k)?slots.get(k):null,setItem:(k,v)=>slots.set(k,v)};
 const context=()=>({accountId:'fixture-user',guildId:'own-guild',token:'generic-fixture-token',epoch:1});
 const transport=M.transport.createTransport({context,fetch:async(route,opt)=>{const packet=JSON.parse(opt.body),reply=await f.call(route,packet,opt.headers['x-token']);calls.push({route,packet,status:reply.status,body:reply.body});return {status:reply.status,async json(){if(route.endsWith('/start')&&!packet.recoverOnly&&loseEntry){loseEntry=false;throw Error('Injected committed entry reply lost')}if(route.endsWith('/resolve')&&loseResult){loseResult=false;throw Error('Injected committed result reply lost')}return clone(reply.body)}}}});
 return M.facade.create({directory,storage,context,transport,locks:{async request(name,opt,fn){if(locked)return fn(null);locked=true;try{return await fn({name})}finally{locked=false}}},legacyWritersQuiescent:async()=>true,validateEntryReply:M.entry.validateEntryReply,validateFreshEntryReply:M.fresh.validateFreshEntryReply,validateSettlementReply:x=>M.settlement.validateSettlement({...x,digest:async raw=>hash(raw)})});
}
(async()=>{try{
 fs.writeFileSync(server,serverSource);const file=path.join(root,'tests/private-ten-slot-integrated.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));
 let source=fs.readFileSync(path.join(__dirname,'../guild-raid-recovery-only-v942/tests.cjs'),'utf8').split('const E=')[0].replace('root=process.env.GUILD_FIXTURE_ROOT','root='+JSON.stringify(root));
 const leadership=fs.readFileSync(path.join(__dirname,'../guild-leadership-v942/tests.cjs'),'utf8').split("for(const kind of ['stale','missing'])")[0].replace("u.guildId='own-guild';", "u.guildId='own-guild';for(const k of "+JSON.stringify(heroes)+"){u.led.unlocked[k]=true;u.led.hero[k]={xp:0,stars:1,pips:0,ref:0};}");
 source=source.replace("fs.readFileSync(path.join(root,'tests/guild-leadership.test.cjs'),'utf8')",JSON.stringify(leadership));m._compile(source+'\nmodule.exports={setup};',file);({f}=await m.exports.setup());
 const E={requestId:'integrated-ten-entry',heroIds:heroes};let c=client();await a.rejects(c.start(E,'ten-slot-instance'),/Injected committed entry reply lost/);a.equal(f.disk().users['fixture-user'].raidDay.n,1);a.equal(calls.length,1);a.equal(calls[0].body.snaps.length,10);
 await f.stop();await f.launch();c=client();const resumed=await c.resume('ten-slot-instance');a.deepEqual(clone(resumed.row.entry),E);for(const k of ['attemptId','seed','snaps','boss'])a.deepEqual(clone(resumed.reply.body[k]),clone(calls[0].body[k]));a.equal(calls[1].packet.recoverOnly,true);
 const P={requestId:'integrated-ten-result',attemptId:resumed.reply.body.attemptId,inputLog:[],dmg:10};c.stage(resumed.row,P);await a.rejects(c.settle('ten-slot-instance'),/Injected committed result reply lost/);a.equal(f.disk().users['fixture-user'].led.txs.filter(t=>t.src==='guild-raid').length,1);
 await f.stop();await f.launch();c=client();const result=await c.settle('ten-slot-instance');a.equal(result.body.ok,true);a.deepEqual(calls[2].packet,P);a.deepEqual(calls[3].packet,P);a.equal(rows.size,0);a.equal([...slots.values()].filter(v=>JSON.parse(v).confirmed===true).length,1);a.equal(f.disk().users['fixture-user'].raidDay.n,1);a.equal(f.disk().users['fixture-user'].led.txs.filter(t=>t.src==='guild-raid').length,1);
 console.log('PASS actual embedded current ten-slot modules + private HTTP: lost committed entry/result, fresh VMs and server restarts, exact packets, one charge/grant, terminal marker');
 }catch(err){failure={message:err.message};throw err}finally{if(f)await f.stop();fs.writeFileSync(server,saved);a.equal(hash(fs.readFileSync(server)),hash(saved));fs.writeFileSync(path.join(__dirname,process.env.INTEGRATED_CONTROL?'integrated-original-control.json':'integrated-certificate.json'),JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),status:failure?'FAIL':'PASS_EMBEDDED_VM_AND_ACTUAL_PRIVATE_HTTP',clientSHA256:hash(html),serverSHA256:hash(serverSource),heroes,calls,failure,fixtureRestored:true,scope:'Actual embedded current modules/validators and authenticated actual private HTTP. Storage/locks are in-memory models, NOT native IndexedDB/WebLocks/DOM/full combat/phone or fullsuite. Synthetic ten owned heroes, injected unreadable replies and fresh VMs/server restarts. Test-only legacy quiescence true; not production authority or release approval.'},null,2));console.log('Owned fixture stopped/restored')}})().catch(err=>{console.error(err);process.exitCode=1});
