'use strict';
const fs=require('node:fs'),path=require('node:path'),a=require('node:assert/strict'),vm=require('node:vm'),crypto=require('node:crypto'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
a(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
const source=fs.readFileSync(path.join(__dirname,'../guild-raid-entry-closed-directory-v948/private-client-entry-closure.html'),'utf8');a.equal(hash(source),'c4f330ca4ae0df11f56caa2fab3db6d6483adcaddb0a970c02953ae8516ff115');
const old="  const r={v:3,...s,id,entry:p,state:'pending'};\n  // atomic directory implementation must reject duplicate entry identities/cap.";
const next="  const r={v:3,...s,id,entry:p,state:'pending'};\n  // A retired instance still owns its terminal slot. Refuse any occupied key\n  // BEFORE directory enrollment or paid entry, even malformed/unknown bytes.\n  if(storage.getItem(key(r))!==null)throw Error('Instance slot already reserved');\n  if(!current())throw Error('Stale context before enrollment');\n  // atomic directory implementation must reject duplicate entry identities/cap.";
a.equal(source.split(old).length,2);const fixed=source.replace(old,next);let scripts=0;for(const m of fixed.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)){if(m[1].trim()){new vm.Script(m[1]);scripts++}}
fs.writeFileSync(path.join(__dirname,'private-client-instance-reservation.html'),fixed);
fs.writeFileSync(path.join(__dirname,'build-certificate.json'),JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),parentClientSHA256:hash(source),clientSHA256:hash(fixed),inlineScriptsParsed:scripts,spans:1,status:'PRIVATE_SLOT_PREFLIGHT_GUARD_NOT_NATIVE_ACTIVATED_APPROVED_OR_SHIPPED',limits:'Current real quiescence provider absent. Preflight relies caller account Web Lock and captured current session. No marker eviction/migration or gameplay/balance change; native, source-pinned integration/full regression and docs remain OPEN.'},null,2));console.log(hash(fixed));
