'use strict';
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),a=require('node:assert/strict'),crypto=require('node:crypto'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
let s=fs.readFileSync(path.join(__dirname,'../guild-raid-period-fence-v948/http.cjs'),'utf8');a.equal(hash(s),'21fae26ad5aed07ca4f6896b7b8b650c38a10b9208cf0df923876fd1f5025c3d');
s=s.replace("process.env.PERIOD_FENCE_CONTROL?'../guild-raid-expired-identity-v948/private-server-expired-identity.js':'private-server-period-fence.js'","'../guild-raid-period-closure-v948/private-server-period-closure.js'");
const b=s.indexOf('const call=async p=>'),e=s.indexOf('\n}catch(err)',b);a(b>0&&e>b);
s=s.slice(0,b)+String.raw`
const vm=require('node:vm'),clone=x=>JSON.parse(JSON.stringify(x));a.equal(hash(fs.readFileSync(candidate)),'7d2cb9f199382ea77a31ed36bfead8fc03808c9559a40ed5b18bb17c5ef5dbe9');
const html=fs.readFileSync(path.join(__dirname,'private-client-instance-reservation.html'),'utf8');a.equal(hash(html),'28ec2c6d66f33b9d730d3b1d224992e1a1205070affaf23f71be19637ff45283');const mb=html.indexOf('const EW_RAID_V3_MODULES='),me=html.indexOf('// PRIVATE guarded v3 cutover.',mb),M=vm.runInNewContext(html.slice(mb,me)+'\nEW_RAID_V3_MODULES;',{structuredClone});
const scope={accountId:'fixture-user',guildId:'own-guild'},context=()=>({...scope,token:'generic-fixture-token',epoch:1}),slots=new Map(),rows=new Map();let locked=false,inserts=0;
const directory={async list(){a(locked);return clone([...rows.values()])},async insertBounded(r,cap){a(locked);a.equal(cap,4);inserts++;rows.set(r.id,clone(r))}},storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.has(k)?slots.get(k):null,setItem:(k,v)=>slots.set(k,v)};
const transport=M.transport.createTransport({context,fetch:async(route,opt)=>{a(locked);const packet=JSON.parse(opt.body),r=await f.call(route,packet,opt.headers['x-token']);calls.push({route,packet,status:r.status,body:r.body});return {status:r.status,json:async()=>clone(r.body)}}}),make=()=>M.facade.create({directory,storage,context,transport,locks:{async request(name,opt,fn){a(!locked);locked=true;try{return await fn({name})}finally{locked=false}}},legacyWritersQuiescent:async()=>true,validateFreshEntryReply:M.fresh.validateFreshEntryReply});
const before=f.bytes(),E={requestId:'r3:2026-10-02:reserved-slot',heroIds:['vael']},key='codex_private_raid_slot_v3_fixture-user_slot';
for(const raw of ['{"confirmed":true}','{"entryClosed":true}','{malformed','']){slots.set(key,raw);await a.rejects(()=>make().start(E,'slot'),/Instance slot already reserved/);a.equal(calls.length,0);a.equal(inserts,0);a.equal(rows.size,0);a.equal(slots.get(key),raw);a.equal(f.bytes(),before)}
// Retained old instance remains untouched; allocate another instance, not delete it.
const retained=slots.get(key);const paid=await make().start(E,'fresh-slot');a.equal(paid.reply.status,200);a.equal(paid.reply.body.ok,true);a.equal(calls.length,1);a.equal(inserts,1);a.equal(slots.get(key),retained);a.equal(f.disk().users['fixture-user'].raidDay.n,1);a.equal(f.disk().users['fixture-user'].led.txs.filter(t=>t.src==='guild-raid').length,0);
const committed=f.bytes();await f.stop();await f.launch();a.equal(f.bytes(),committed);console.log('PASS four occupied slots refused before enrollment/HTTP with identical whole DB; distinct instance one actual authenticated paid entry and zero grants, restart identical');
`+s.slice(e);
s=s.replace("process.env.PERIOD_FENCE_CONTROL?'original-control.json':'certificate.json'","'http-certificate.json'").replace("calls,failure,fixtureRestored:true","clientSHA256:'28ec2c6d66f33b9d730d3b1d224992e1a1205070affaf23f71be19637ff45283',checks:6,calls,failure,fixtureRestored:true").replace('Actual privateHTTP syntheticaccount/clock. Opt-in namespace ONLY. Client namespace/day acquisition NOTwired; legacy bare IDs unchanged, no native/fullsuite/balance/terminal retirement proof.','Actual embedded candidate facade/hybrid/transport/fresh-validator with private authenticated HTTP server and whole DB bytes/restart. Storage/directory/locks/quiescence modeled, NOT native or real all-writer cutover, no activation/balance/deploy approval. Four zero-transport refusal checks, one distinct-instance paid entry, one restart unchanged check.');
const file=path.join(__dirname,'generated-slot-http.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m._compile(s,file);
