'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),a=require('node:assert/strict'),crypto=require('node:crypto'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),copy=x=>JSON.parse(JSON.stringify(x));
const parent=process.argv.includes('--parent'),file=parent?'../guild-raid-entry-closed-directory-v948/private-client-entry-closure.html':'private-client-instance-reservation.html',html=fs.readFileSync(path.join(__dirname,file),'utf8');
const b=html.indexOf('const EW_RAID_V3_MODULES='),e=html.indexOf('// PRIVATE guarded v3 cutover.',b);a(b>0&&e>b);const M=vm.runInNewContext(html.slice(b,e)+'\nEW_RAID_V3_MODULES;',{structuredClone});
const scope={accountId:'actor',guildId:'guild'},entry={requestId:'r3:2026-10-03:fresh',heroIds:['hero1']};
function rig(occupied=null){const data=new Map();if(occupied!==null)data.set('codex_private_raid_slot_v3_actor_slot',occupied);let row=null,inserts=0,network=0,current=true,readFailure=false,staleOnRead=false;
 const storage={getItem(k){if(readFailure)throw Error('Read denied');if(staleOnRead)current=false;return data.has(k)?data.get(k):null},setItem:(k,v)=>data.set(k,v)},directory={async list(){return row?[copy(row)]:[]},async insertBounded(r,cap){a.equal(cap,4);inserts++;row=copy(r)}};
 const context=()=>({ ...scope,token:'token',epoch:current?1:2 });
 const facade=M.facade.create({directory,storage,context,locks:{async request(n,o,fn){a.equal(n,'ew_raid_pending_v1_actor');a.equal(o.mode,'exclusive');return fn({name:n})}},legacyWritersQuiescent:async()=>true,transport:async request=>{network++;a.equal(request.mode,'fresh-entry');return {status:200,body:{ok:true,attemptId:'attempt'}}},validateFreshEntryReply:async({reply,entry,scope})=>({...scope,entry,entryRequestId:entry.requestId,attemptId:reply.body.attemptId})});
 // Model legacy inspection with bounded empty namespace; no production proof claimed.
 storage.length=data.size;storage.key=i=>[...data.keys()][i]??null;
 return {data,storage,directory,facade,get row(){return copy(row)},get effects(){return {inserts,network}},readDenied(){readFailure=true},staleRead(){staleOnRead=true},hybrid:()=>M.hybrid.create(directory,storage,{isCurrent:()=>current,legacyCheck:async()=> 'clear'})};
}
const cases=[];async function test(name,fn){try{await fn();cases.push({name,status:'PASS'})}catch(e){cases.push({name,status:'FAIL',error:e.message})}}
(async()=>{
 for(const [kind,raw] of [['confirmed','{"confirmed":true}'],['closed','{"entryClosed":true}'],['malformed','{bad'],['empty','']])await test(kind+' occupied terminal/unknown slot refuses before facade directory enrollment or paid transport',async()=>{const r=rig(raw);await a.rejects(()=>r.facade.start(entry,'slot'));a.deepEqual(r.effects,{inserts:0,network:0});a.equal(r.row,null);a.equal(r.data.get('codex_private_raid_slot_v3_actor_slot'),raw)});
 await test('hybrid storage read failure refuses enrollment without a directory mutation',async()=>{const r=rig();r.readDenied();await a.rejects(()=>r.hybrid().enroll(scope,entry,'slot'));a.equal(r.effects.inserts,0);a.equal(r.row,null)});
 await test('context invalidated by slot read refuses before directory transaction',async()=>{const r=rig();const h=r.hybrid();r.staleRead();await a.rejects(()=>h.enroll(scope,entry,'slot'));a.equal(r.effects.inserts,0);a.equal(r.row,null)});
 await test('new unoccupied slot still enrolls once and sends one exact entry',async()=>{const r=rig();const result=await r.facade.start(entry,'slot');a.equal(result.reply.body.ok,true);a.deepEqual(r.effects,{inserts:1,network:1});a.equal(r.row.entry.requestId,entry.requestId)});
 await test('other account marker not adopted or deleted; own fresh entry permitted',async()=>{const r=rig();r.data.set('codex_private_raid_slot_v3_other_slot','retained-other');r.storage.length=r.data.size;await r.facade.start(entry,'slot');a.deepEqual(r.effects,{inserts:1,network:1});a.equal(r.data.get('codex_private_raid_slot_v3_other_slot'),'retained-other')});
 const cert={atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),parentControl:parent,clientSHA256:hash(html),testSHA256:hash(fs.readFileSync(__filename)),pass:cases.filter(x=>x.status==='PASS').length,fail:cases.filter(x=>x.status==='FAIL').length,cases,scope:'Actual embedded facade/hybrid code with MODEL storage/directory/exclusive locks/session/transport. No native IDB/Web Locks or actual server charge. Legacy proof TRUE only fixture injection, not candidate provider. Parent failing assertions naturally witness enrollment/transport despite retained slot. No eviction/migration or balance/deployment approval.'};fs.writeFileSync(path.join(__dirname,parent?'parent-controls.json':'certificate.json'),JSON.stringify(cert,null,2));console.log(JSON.stringify(cert,null,2));process.exitCode=cert.fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=2});
