'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{createTransport}=require('./transport.cjs');
function fixture(){const f={session:{accountId:'actor',guildId:'guild',token:'memory-only',epoch:1},calls:[],status:200,afterFetch:false,afterJSON:false};f.transport=createTransport({context:()=>f.session,fetch:async(route,options)=>{f.calls.push({route,options});if(f.afterFetch)f.session={...f.session,epoch:2};return{status:f.status,json:async()=>{if(f.afterJSON)f.session={...f.session,epoch:2};return{ok:true}}}}});return f}
const entry={mode:'entry-recovery-only',scope:{accountId:'actor',guildId:'guild'},packet:{requestId:'entry',heroIds:['hero']}};
test('strict recovery flag only on captured authenticated start request, packet unchanged',async()=>{const f=fixture();await f.transport(entry);assert.equal(f.calls[0].options.headers['x-token'],'memory-only');assert.equal(JSON.parse(f.calls[0].options.body).recoverOnly,true);assert.equal(entry.packet.recoverOnly,undefined)});
for(const phase of ['before','afterFetch','afterJSON'])test('session changes '+phase+' refuse',async()=>{const f=fixture();if(phase==='before')f.session={...f.session,epoch:2};else f[phase]=true;await assert.rejects(f.transport(entry),/Stale/);assert.equal(f.calls.length,phase==='before'?0:1)});
for(const status of [403,409,503])test('HTTP '+status+' preserved without fresh fallback',async()=>{const f=fixture();f.status=status;assert.equal((await f.transport(entry)).status,status);assert.equal(f.calls.length,1);assert.equal(JSON.parse(f.calls[0].options.body).recoverOnly,true)});
test('foreign scope and unknown mode refuse before network',async()=>{const f=fixture();await assert.rejects(f.transport({...entry,scope:{accountId:'other',guildId:'guild'}}),/scope/);await assert.rejects(f.transport({...entry,mode:'fallback'}),/mode/);assert.equal(f.calls.length,0)});
test('caller recovery flag/token payload refuse before network',async()=>{for(const packet of [{...entry.packet,recoverOnly:false},{...entry.packet,token:'secret'}]){const f=fixture();await assert.rejects(f.transport({...entry,packet}),/fields|secrets/);assert.equal(f.calls.length,0)}});
test('result recovery uses resolve with exact immutable result and no entry fallback',async()=>{const f=fixture(),packet={requestId:'result',attemptId:'attempt',inputLog:[],dmg:1};await f.transport({...entry,mode:'result-recovery-only',packet});assert.equal(f.calls[0].route,'/api/guild/raid/resolve');assert.deepEqual(JSON.parse(f.calls[0].options.body),packet)});
