'use strict';const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
const html=fs.readFileSync(path.join(__dirname,'payload/combined/emberweave-heroes.html'),'utf8'),sha=crypto.createHash('sha256').update(html).digest('hex');assert.equal(sha,'bc71d3b276c22745f7dacfad167ef77510c6f95afeb1c22ec69b8cf927da299d');
const handlers=html.slice(html.indexOf('let RAID_START_PENDING='),html.indexOf('function raidDamageDone(){'));
const timer=html.slice(html.indexOf('let _resultTimer='),html.indexOf('function updateUnsafe(){'));
const log=[];let requests=0,holdResponses=process.argv.includes('--hold-responses');const pendingResponses=[],receipts=new Map();
const page=`<!doctype html><meta charset="utf-8"><title>Isolated raid browser audit</title><h1>Isolated raid browser audit</h1><p>Extracted candidate handlers; synthetic fixture API. No live game or Brain.</p>
<button onclick="holdLock()">Hold account lock</button><button onclick="releaseLock()">Release account lock</button><button onclick="stageResult()">Stage result and cancel timer</button><button onclick="raidRecoverSaved()">Recover saved result</button><button onclick="refreshEvidence()">Refresh evidence</button>
<button onclick="seedConflict()">Seed conflicting fixture results</button><button onclick="seedBound()">Seed 513 unrelated fixture keys</button><button onclick="switchAccount()">Switch fixture account</button>
<p id="banner"></p><h2 id="resultTitle"></h2><div id="resultReward"></div><p id="resultHint"></p><pre id="evidence"></pre>
<script>let ACC={id:'native-fixture',token:'fixture-only'},G={guild:{id:'fixture-guild'}},CUR={},gameSpeed=1;
function bannerMsg(s){document.getElementById('banner').textContent=s;refreshEvidence();}function escapeHTML(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}function adoptLedger(l){window.adopted=l;}function setResultVerdict(){}function updateHubChrome(){refreshEvidence();}function show(){refreshEvidence();}
async function api(route,method,p){const r=await fetch('/fixture',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({route,packet:p,fixtureAccountId:ACC.id})});return r.json();}
${timer}\n${handlers}
let release=null;function holdLock(){navigator.locks.request(raidJournalKey(),{mode:'exclusive',ifAvailable:true},async lock=>{if(!lock){bannerMsg('TEST LOCK BUSY');return;}bannerMsg('TEST LOCK HELD');await new Promise(r=>release=r);release=null;bannerMsg('TEST LOCK RELEASED');});}
function releaseLock(){if(release)release();}function stageResult(){raidSettlementQueue({requestId:'native-result-1',attemptId:'native-attempt',inputLog:[{t:1}],dmg:10},{name:'Fixture Boss',tier:1},Date.now(),null);cancelResult();refreshEvidence();}
function seedConflict(){for(const id of ['conflict-A','conflict-B']){const k=raidJournalKey()+'_result_'+crypto.randomUUID();localStorage.setItem(k,JSON.stringify({v:1,accountId:ACC.id,guildId:G.guild.id,kind:'resolve',createdAt:Date.now(),packet:{requestId:id,attemptId:'native-attempt',inputLog:[{t:1}],dmg:id==='conflict-A'?10:20},entryRequestId:null,RB:{name:'Fixture Boss',tier:1}}));}refreshEvidence();}
function seedBound(){for(let i=0;i<513;i++)localStorage.setItem('fixture-unrelated-'+i,'x');refreshEvidence();}
function switchAccount(){ACC={id:'native-fixture-other',token:'fixture-other-only'};refreshEvidence();}
async function refreshEvidence(){const locks=await navigator.locks.query(),rows=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);rows.push([k,localStorage.getItem(k)]);}document.getElementById('evidence').textContent=JSON.stringify({secure:isSecureContext,webLocks:!!navigator.locks,uuid:typeof crypto.randomUUID,held:locks.held,rows,saved:raidJournalRead(),adopted:window.adopted||null},null,2);}
window.addEventListener('storage',refreshEvidence);refreshEvidence();</script>`;
const server=http.createServer((req,res)=>{if(req.url==='/release-responses'||req.url==='/release-reversed'){holdResponses=false;const sends=pendingResponses.splice(0);if(req.url==='/release-reversed')sends.reverse();for(const send of sends)send();res.end('released');return;}if(req.url==='/shutdown'){for(const send of pendingResponses.splice(0))send();res.end('stopped');server.close(()=>process.exit());return;}if(req.url==='/fixture'&&req.method==='POST'){let raw='';req.on('data',c=>{raw+=c;if(raw.length>200000)req.destroy();});req.on('end',()=>{const p=JSON.parse(raw);requests++;const identity=p.fixtureAccountId+':'+p.packet.requestId;let reply=receipts.get(identity);if(!reply){reply={ok:true,dmg:10,ledger:{gold:100+requests},reward:{guildCoins:1}};receipts.set(identity,reply);}log.push(p);const send=()=>{res.setHeader('content-type','application/json');res.end(JSON.stringify(reply));};if(holdResponses)pendingResponses.push(send);else send();});return;}if(req.url==='/evidence'){res.setHeader('content-type','application/json');res.end(JSON.stringify({sha,requests,uniqueReceipts:receipts.size,pendingResponses:pendingResponses.length,holdResponses,log}));return;}res.setHeader('content-type','text/html');res.end(page);});
server.listen(0,'127.0.0.1',()=>{const url='http://127.0.0.1:'+server.address().port;fs.writeFileSync(path.join(__dirname,'browser-session.json'),JSON.stringify({url,sha,pid:process.pid,started:new Date().toISOString()},null,2));console.log(url);});setTimeout(()=>server.close(()=>process.exit()),600000).unref();
