'use strict';const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.join(__dirname,'../shady-gold-v942/snapshot'),server=path.join(root,'server.js'),leader=path.join(root,'tests/guild-leadership.test.cjs'),saved=fs.readFileSync(server),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
assert.equal(hash(saved),'71202733c70b7e0d5e301918a594214eef1087f7b3cdd8161e152ed6c113de65');assert(!fs.existsSync(leader));assert(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
async function run(){let f,copied=false;try{
 fs.copyFileSync(path.join(__dirname,'../guild-leadership-v942/tests.cjs'),leader);copied=true;fs.copyFileSync(path.join(__dirname,'../guild-raid-recovery-only-v942/payload/server.js'),server);
 const file=path.join(root,'tests/private-composition-http.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(fs.readFileSync(path.join(__dirname,'../guild-raid-recovery-only-v942/tests.cjs'),'utf8').split('const E=')[0].replace('root=process.env.GUILD_FIXTURE_ROOT','root='+JSON.stringify(root))+'\nmodule.exports={setup};',file);({f}=await m.exports.setup());
 const A=require('./composition-facade.cjs'),slots=new Map(),rows=new Map(),calls=[],copy=x=>JSON.parse(JSON.stringify(x));let lost=true,lostResult=true;
 const storage={get length(){return slots.size},key:i=>[...slots.keys()][i]??null,getItem:k=>slots.get(k)??null,setItem:(k,v)=>slots.set(k,v)};
 const directory={list:async(a,n)=>[...rows.values()].filter(x=>x.accountId===a).slice(0,n).map(copy),insertBounded:async r=>{assert(!rows.has(r.id));rows.set(r.id,copy(r))},markConfirmed:async()=>{},retireConfirmed:async()=>{}};
 const transport=async p=>{assert(['fresh-entry','entry-recovery-only','result-recovery-only'].includes(p.mode));assert.deepEqual(p.scope,{accountId:'fixture-user',guildId:'own-guild'});const body={...p.packet,...(p.mode==='entry-recovery-only'?{recoverOnly:true}:{})};calls.push({mode:p.mode,packet:copy(p.packet),body});const reply=await f.call(p.mode==='result-recovery-only'?'/api/guild/raid/resolve':'/api/guild/raid/start',body);if(lost){lost=false;throw Error('Committed reply lost')}if(p.mode==='result-recovery-only'&&lostResult){lostResult=false;throw Error('Committed result reply lost')}return reply;};
 const validateEntryReply=async({reply,entry,scope})=>{assert.equal(reply.status,200);assert.equal(reply.body.ok,true);assert.equal(reply.body.resumed,true);const attempt=f.disk().guilds[scope.guildId].raid.att[scope.accountId];assert.equal(attempt.reqId,entry.requestId);assert.deepEqual(attempt.heroIds,entry.heroIds);assert.equal(reply.body.attemptId,attempt.id);return {...scope,entryRequestId:entry.requestId,entry:copy(entry),attemptId:attempt.id};};
 const deps={directory,storage,locks:{request:async(k,o,fn)=>fn({})},transport,legacyWritersQuiescent:async()=>true,validateEntryReply};
 function fresh(){return vm.runInNewContext("A.create({...deps,context:()=>({accountId:'fixture-user',guildId:'own-guild',token:'memory-only-fixture',epoch:1})})",{A,deps})}
 const E={requestId:'composition-entry',heroIds:['vael']};await assert.rejects(fresh().start(E,'entry-instance'),/Committed reply lost/);assert.equal(rows.size,1);const committed=f.bytes(),attempt=f.disk().guilds['own-guild'].raid.att['fixture-user'].id;
 await f.stop();await f.launch();assert.equal(calls.length,1);const recovery=await fresh().recover('entry-instance');assert.equal(recovery.reply.status,200);assert.equal(recovery.reply.body.resumed,true);assert.equal(recovery.reply.body.attemptId,attempt);assert.deepEqual(calls.map(x=>x.mode),['fresh-entry','entry-recovery-only']);assert.deepEqual(calls[0].packet,calls[1].packet);assert.equal(calls[1].body.recoverOnly,true);assert.equal(f.bytes(),committed);assert.equal(f.disk().users['fixture-user'].raidDay.n,1);
 await assert.rejects(fresh().recover('missing-instance'),/No recoverable/);assert.equal(calls.length,2);assert.equal(f.bytes(),committed);
 const resumedClient=fresh(),resumed=await resumedClient.resume('entry-instance'),P={requestId:'result',attemptId:attempt,inputLog:[],dmg:10};resumedClient.stage(resumed.row,P);assert.equal(slots.size,1,'Synchronous result stage before any delayed send');
 await assert.rejects(resumedClient.recover('entry-instance'),/Committed result reply lost/);const settled=f.bytes(),txs=f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length;assert.equal(txs,1);await f.stop();await f.launch();const count=calls.length;const final=await fresh().recover('entry-instance');assert.equal(calls.length,count+1);assert.equal(final.reply.body.ok,true);assert.deepEqual(calls.at(-2).packet,calls.at(-1).packet);assert.equal(f.bytes(),settled);assert.equal(f.disk().users['fixture-user'].raidDay.n,1);assert.equal(f.disk().users['fixture-user'].led.txs.filter(x=>x.src==='guild-raid').length,1);
 fs.writeFileSync(path.join(__dirname,'integration-results.json'),JSON.stringify({at:new Date().toISOString(),pass:true,serverHash:hash(fs.readFileSync(server)),facadeHash:hash(fs.readFileSync(path.join(__dirname,'composition-facade.cjs'))),hybridHash:hash(fs.readFileSync(path.join(__dirname,'hybrid-adapter.cjs'))),calls,entryCount:1,raidTransactions:txs,scope:'Fresh VM facade instances + actual private HTTP/restart, model storage/locks and injected quiescence. Entry validator checks fixture disk: evidence oracle ONLY, not production validator/auth integration. Synchronous staging proved, no actual game timer/native HTML.',open:'Production authenticated response validator, source guarded bootstrap/package, confirmation/cleanup, native integration and quiescence remain OPEN. Retained pending row deliberately not cleared.'},null,2));console.log('PASS private freshVM resume lease/stage/lost result reply/restart exact packet, one entry and one raid grant transaction; production validator/native integration OPEN');
}finally{if(f)await f.stop();fs.writeFileSync(server,saved);if(copied)fs.unlinkSync(leader);assert.equal(hash(fs.readFileSync(server)),hash(saved));}}
run().catch(e=>{console.error(e);process.exitCode=1});
