'use strict';const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),a=require('node:assert/strict');const hash=x=>crypto.createHash('sha256').update(x).digest('hex');a(!fs.existsSync('C:/Users/Home/AppData/Local/Emberweave/shutdown-requested.json'));
const source=fs.readFileSync(path.join(__dirname,'../guild-raid-expired-identity-v948/private-server-expired-identity.js'),'utf8');a.equal(hash(source),'ba1de8145a4fa71c94fb6193835faad63bf7ef10627afe3cf3b1db9a51232c47');
let out=source;function patch(old,next){a.equal(out.split(old).length,2);out=out.replace(old,next)}
patch('      const currentOpen=r.att[me.id];',`      // Private opt-in namespace. Old periods can never become fresh paid intents.
      const v3Entry=reqId.startsWith('r3:');let spentBook=null,spentEntry=null;
      if(v3Entry){
        const match=/^r3:(\\d{4}-\\d{2}-\\d{2}):[-a-z0-9]{1,24}$/i.exec(reqId);
        if(!match)return send(res,409,{ok:false,entryPeriodHeld:true,error:'That saved raid request has an invalid day. No new attempt was spent.'});
        const oldBook=actor.raidV3Spent;
        if(oldBook!==undefined&&(!oldBook||oldBook.v!==1||typeof oldBook.period!=='string'||!Array.isArray(oldBook.entries)||oldBook.entries.length>3||oldBook.entries.some(x=>!x||typeof x.guildId!=='string'||typeof x.requestId!=='string'||!Array.isArray(x.heroIds))))return send(res,409,{ok:false,error:'Saved raid requests need recovery.'});
        spentBook=oldBook&&oldBook.period===match[1]?oldBook:{v:1,period:r.day,entries:[]};
        spentEntry=spentBook.entries.find(x=>x.requestId===reqId);
        if(spentEntry&&(spentEntry.guildId!==g.id||JSON.stringify(spentEntry.heroIds)!==JSON.stringify(b.heroIds)))return send(res,409,{ok:false,entryUsed:true,error:'That saved raid request belongs to a different squad or guild.'});
      }
      const currentOpen=r.att[me.id];`);
patch("      if(open)return send(res,409,{ok:false,entryExpired:true,error:'This saved raid entry expired. No new attempt was spent. Use a new intent only after recovery is resolved.'});", "      if(v3Entry&&reqId.slice(3,13)!==r.day)return send(res,409,{ok:false,entryPeriodHeld:true,error:'That saved raid request is from a different day. No new attempt was spent.'});\n      if(spentEntry&&!open)return send(res,409,{ok:false,entryUsed:true,error:'That saved raid request was already spent. No new attempt was spent.'});\n      if(open)return send(res,409,{ok:false,entryExpired:true,error:'This saved raid entry expired. No new attempt was spent. Use a new intent only after recovery is resolved.'});");
patch('      const ids=Array.isArray(b.heroIds)?[...new Set(b.heroIds.map(String))].slice(0,10):[];',"      if(v3Entry&&spentBook.entries.length>=3)return send(res,409,{ok:false,error:'Saved raid requests are full for today.'});\n      const ids=Array.isArray(b.heroIds)?[...new Set(b.heroIds.map(String))].slice(0,10):[];");
patch("      const committed=durableUserCommit(me,actor,{...(DB.idem||{})},'guild-raid-recovery',[],{guilds});","      if(v3Entry){spentBook.entries.push({guildId:g.id,requestId:reqId,heroIds:structuredClone(ids)});actor.raidV3Spent=spentBook;}\n      const committed=durableUserCommit(me,actor,{...(DB.idem||{})},'guild-raid-recovery',[],{guilds});");
fs.writeFileSync(path.join(__dirname,'private-server-period-fence.js'),out);fs.copyFileSync(path.join(__dirname,'../guild-raid-expired-identity-v948/private-client-guild-discovery.html'),path.join(__dirname,'private-client-guild-discovery.html'));
fs.writeFileSync(path.join(__dirname,'build-certificate.json'),JSON.stringify({atET:new Date().toLocaleString('sv-SE',{timeZone:'America/New_York'}),serverParentSHA256:hash(source),serverSHA256:hash(out),clientSHA256:hash(fs.readFileSync(path.join(__dirname,'private-client-guild-discovery.html'))),status:'PRIVATE_OPT_IN_PERIOD_FENCE_NOT_CLIENT_WIRED_OR_RELEASE',edits:'Four guarded spans: r3:YYYY-MM-DD:nonce namespace validates authoritative raid day; same-period account-scoped spent-ID/squad/guild record <=3 committed atomically with paid entry, survives expired snapshot pruning/settlement. Past period rejected before charge even after book rotates. Bare legacy IDs unchanged, still require separate quiescence/cutover. No terminal retirement proof or refund.'},null,2));
