'use strict';const test=require('node:test'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict'),root=process.env.GUILD_FIXTURE_ROOT||path.resolve(__dirname,'..');
async function setup(kind='valid'){const file=path.join(root,'tests/private-raid-start-fixture.cjs'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));let s=fs.readFileSync(path.join(root,'tests/guild-leadership.test.cjs'),'utf8').split("for(const kind of ['stale','missing'])")[0];s=s.replace("u.guildId='own-guild';","u.guildId='own-guild';u.led.skill={vael:[1,1,1,1]};u.led.skillImported=1790928000000;");if(kind==='quota')s=s.replace("u.guildId='own-guild';","u.guildId='own-guild';u.raidDay={d:'2026-10-02',n:3};");m._compile(s+'\nmodule.exports={setup};',file);return m.exports.setup(kind);}
const packet={requestId:'private-raid-start',heroIds:['vael']};
test('Raid entry write/rename faults leave guild/counters/account unchanged; same intent retry persists and resumes after restart',async()=>{const{f}=await setup();try{const before=f.bytes(),view=(await f.call('/api/guild/raid')).body,users=structuredClone(f.disk().users),foreign=f.disk().guilds['other-guild'];for(const fault of ['write',true]){await f.inject(fault);assert.equal((await f.call('/api/guild/raid/start',packet)).status,503);assert.equal(f.bytes(),before);assert.deepEqual((await f.call('/api/guild/raid')).body,view);}await f.inject(false);const first=await f.call('/api/guild/raid/start',packet);assert.equal(first.status,200);assert(first.body.attemptId);const disk=f.disk();assert.equal(disk.guilds['own-guild'].raid.att['fixture-user'].id,first.body.attemptId);assert.equal(disk.guilds['own-guild'].raid.used['fixture-user'],1);assert.deepEqual(disk.users['fixture-user'].raidDay,{d:'2026-10-02',n:1});users['fixture-user'].raidDay={d:'2026-10-02',n:1};assert.deepEqual(disk.users,users);assert.deepEqual(disk.guilds['other-guild'],foreign);const after=f.bytes();const again=await f.call('/api/guild/raid/start',packet);assert.equal(again.body.resumed,true);assert.equal(again.body.attemptId,first.body.attemptId);assert.equal(again.body.seed,first.body.seed);assert.deepEqual(again.body.snaps,first.body.snaps);assert.equal(f.bytes(),after);await f.stop();await f.launch();const resumed=await f.call('/api/guild/raid/start',packet);assert.equal(resumed.body.resumed,true);assert.equal(resumed.body.attemptId,first.body.attemptId);assert.equal(f.bytes(),after);}finally{await f.stop();}});
test('Raid immediate success then restart keeps frozen fight/current remaining count',async()=>{const{f}=await setup();try{const first=await f.call('/api/guild/raid/start',packet);assert.equal(first.status,200);await f.stop();await f.launch();const second=await f.call('/api/guild/raid/start',packet);assert.equal(second.body.attemptId,first.body.attemptId);assert.equal(second.body.seed,first.body.seed);assert.equal(f.disk().guilds['own-guild'].raid.used['fixture-user'],1);assert.equal(f.disk().users['fixture-user'].raidDay.n,1);}finally{await f.stop();}});
test('Rejected raid squad does not leak raid initialization into later unrelated commit',async()=>{const{f}=await setup();try{const before=f.bytes();assert.equal(f.disk().guilds['own-guild'].raid,undefined);for(const heroIds of [[],['unowned-hero']]){assert.equal((await f.call('/api/guild/raid/start',{...packet,heroIds})).status,400);assert.equal(f.bytes(),before);}assert.equal((await f.call('/api/guild/contribute',{})).status,200);assert.equal(f.disk().guilds['own-guild'].raid,undefined);}finally{await f.stop();}});
test('Current raid player3/day quota refuses without publishing migrations',async()=>{const{f}=await setup('quota');try{const before=f.bytes();const result=await f.call('/api/guild/raid/start',packet);assert.equal(result.status,200);assert.equal(result.body.none,true);assert.equal(f.bytes(),before);assert.equal((await f.call('/api/guild/contribute',{})).status,200);assert.equal(f.disk().guilds['own-guild'].raid,undefined);assert.equal(f.disk().users['fixture-user'].raidDay.n,3);}finally{await f.stop();}});
test('Unauthenticated and removed members cannot start/resume raid',async()=>{for(const kind of ['valid','removed']){const{f}=await setup(kind);try{const before=f.bytes();assert.equal((await f.call('/api/guild/raid/start',packet,kind==='valid'?null:undefined)).status,kind==='valid'?401:403);assert.equal(f.bytes(),before);}finally{await f.stop();}}});
test('Fresh request while open retains historical charge/replace behavior, not exactly-once policy change',async()=>{const{f}=await setup();try{assert.equal((await f.call('/api/guild/raid/start',packet)).status,200);assert.equal((await f.call('/api/guild/raid/start',{...packet,requestId:'different-private-intent'})).status,200);assert.equal(f.disk().users['fixture-user'].raidDay.n,2);assert.equal(f.disk().guilds['own-guild'].raid.used['fixture-user'],2);}finally{await f.stop();}});
